#!/usr/bin/env bash
#
# ==============================================================================
#  OTCA — OpenTelemetry Certified Associate
#  Domain 4 · Topic 4.1  Context Propagation        (exam weight: 2.5)
#  BREAK & FIX laboratory — disposable VM only
# ==============================================================================
#
#  Reference sources:
#    - OTCA Curriculum (CNCF):
#        https://github.com/cncf/curriculum/raw/master/OTCA_Curriculum.pdf
#    - OpenTelemetry — Context Propagation (concept):
#        https://opentelemetry.io/docs/concepts/context-propagation/
#    - W3C Trace Context (traceparent / tracestate):
#        https://www.w3.org/TR/trace-context/
#    - W3C Baggage:
#        https://www.w3.org/TR/baggage/
#    - OTEL_PROPAGATORS environment variable (SDK config):
#        https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/
#
#  WHAT THIS SCRIPT DOES
#    It builds a throwaway Python venv under /tmp and runs a tiny two-service
#    demo (Service A -> Service B) that carries trace context and baggage across
#    a simulated network boundary using the OpenTelemetry Propagators API.
#    Then it BREAKS context propagation on purpose (via configuration only),
#    shows you the symptom, and leaves it broken for YOU to repair.
#
#  SAFETY
#    Every change lives inside one work directory in /tmp. No system package,
#    no service, no file outside that directory is touched. Deleting the work
#    directory (or running this script with `--clean`) fully undoes everything.
#    Run it ONLY on a lab VM you can throw away.
# ==============================================================================

set -euo pipefail

WORKDIR="/tmp/otca-4.1-context-propagation"

# ----- optional cleanup: `./break_fix.sh --clean` -----------------------------
if [ "${1:-}" = "--clean" ]; then
  rm -rf "$WORKDIR"
  echo "[+] Removed $WORKDIR — lab reset."
  exit 0
fi

# ----- lab confirmation -------------------------------------------------------
if [ "${1:-}" != "-y" ] && [ -t 0 ]; then
  echo "This script deliberately breaks OpenTelemetry context propagation in a"
  echo "sandbox under $WORKDIR. It is meant for a DISPOSABLE lab VM."
  printf "Continue? [y/N] "
  read -r ans
  case "$ans" in
    y|Y|yes|YES) : ;;
    *) echo "Aborted."; exit 1 ;;
  esac
fi

# ----- prerequisites ----------------------------------------------------------
command -v python3 >/dev/null 2>&1 || { echo "ERROR: python3 not found."; exit 1; }

echo "[+] Building sandbox in $WORKDIR"
mkdir -p "$WORKDIR"
cd "$WORKDIR"

if [ ! -x "$WORKDIR/.venv/bin/python" ]; then
  python3 -m venv .venv
  ./.venv/bin/python -m pip install --quiet --disable-pip-version-check --upgrade pip
  echo "[+] Installing opentelemetry-api and opentelemetry-sdk (throwaway venv)..."
  ./.venv/bin/python -m pip install --quiet --disable-pip-version-check \
      opentelemetry-api opentelemetry-sdk
fi

# ----- the instrumented two-service demo (DO NOT EDIT THIS FILE) --------------
# demo.py is deliberately correct. The bug you must fix is NOT in the code; it
# is in the propagation configuration (propagation.env). Real distributed
# tracing breaks the same way in production: the instrumentation is fine, the
# propagator is misconfigured.
cat > demo.py <<'PYEOF'
import os
from opentelemetry import trace, propagate, baggage, context
from opentelemetry.sdk.trace import TracerProvider

trace.set_tracer_provider(TracerProvider())
tracer = trace.get_tracer("otca.topic-4.1.context-propagation")

hex32 = lambda n: format(n, "032x")   # trace_id -> 32 hex chars
hex16 = lambda n: format(n, "016x")   # span_id  -> 16 hex chars

print("=" * 70)
print("OTEL_PROPAGATORS =",
      os.getenv("OTEL_PROPAGATORS", "<unset -> default: tracecontext,baggage>"))
print("=" * 70)

# --- SERVICE A (producer / client) -------------------------------------------
# A starts a span and attaches request-scoped Baggage, then injects the current
# Context into an outgoing carrier (what would be the HTTP request headers).
carrier = {}
token = context.attach(baggage.set_baggage("user.id", "42"))
with tracer.start_as_current_span("A.checkout") as span_a:
    a = span_a.get_span_context()
    a_trace, a_span = hex32(a.trace_id), hex16(a.span_id)
    propagate.inject(carrier)          # writes traceparent/baggage IF a propagator is active
context.detach(token)

print("\n[Service A]  trace_id =", a_trace)
print("[Service A]  span_id  =", a_span)
print("[wire]       headers handed to Service B:")
if carrier:
    for k, v in carrier.items():
        print("               {}: {}".format(k, v))
else:
    print("               << EMPTY -- nothing was injected onto the wire >>")

# --- network boundary --------------------------------------------------------
# In production the carrier crosses the network as HTTP headers. Here we simply
# pass the same dict to Service B, exactly as a server would receive headers.

# --- SERVICE B (consumer / server) -------------------------------------------
# B extracts the incoming Context from the carrier and starts its span inside it.
extracted = propagate.extract(carrier)
b_bag = baggage.get_baggage("user.id", extracted)
with tracer.start_as_current_span("B.charge", context=extracted) as span_b:
    b = span_b.get_span_context()
    b_trace = hex32(b.trace_id)
    b_parent = span_b.parent

print("\n[Service B]  trace_id =", b_trace)
print("[Service B]  parent   =",
      hex16(b_parent.span_id) if b_parent else "<none -- B started a BRAND-NEW trace>")
print("[Service B]  baggage user.id =", b_bag if b_bag is not None else "<lost>")

print("\n" + "-" * 70)
if b_trace == a_trace and b_parent is not None:
    print("RESULT: LINKED  (ok)  -> A and B share ONE trace; B is a child of A;")
    print("                        baggage survived the hop.")
else:
    print("RESULT: BROKEN  (fail) -> A and B are in DIFFERENT traces. The request")
    print("                        looks like two unrelated operations and baggage")
    print("                        never reached B.")
print("-" * 70)
PYEOF

# ----- the misconfiguration = THE BREAK --------------------------------------
# This is the only thing that is wrong. `none` selects the no-op propagator:
# inject() and extract() become silent no-ops, so no context ever crosses the
# boundary. This is the file you are allowed to edit.
echo 'OTEL_PROPAGATORS=none' > propagation.env

# ----- re-runnable harness ---------------------------------------------------
cat > run.sh <<'SHEOF'
#!/usr/bin/env bash
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
set -a
. "$here/propagation.env"       # loads OTEL_PROPAGATORS
set +a
exec "$here/.venv/bin/python" "$here/demo.py"
SHEOF
chmod +x run.sh

# ----- run it broken, so the student sees the symptom ------------------------
echo
echo ">>> Running the demo with the current (broken) configuration..."
echo
bash run.sh || true

# ----- the mission -----------------------------------------------------------
cat <<'EOF'

==============================================================================
YOUR MISSION
==============================================================================
SYMPTOM you just saw:
  * The wire headers handed to Service B are EMPTY -- no `traceparent`.
  * Service A and Service B print DIFFERENT trace_id values.
  * Service B reports parent = <none>, i.e. it opened a brand-new trace.
  * The `user.id` baggage never reached Service B (it was <lost>).
  * RESULT: BROKEN.
  In a real backend (Jaeger, Tempo, ...) this shows up as fragmented traces:
  one logical request appears as several disconnected single-span traces, and
  you cannot follow a request from service to service.

GOAL — make a single `bash run.sh` print:
  * `traceparent: 00-<trace>-<span>-01` (and a `baggage:` header) on the wire,
  * the SAME trace_id for Service A and Service B,
  * Service B parent = Service A's span_id,
  * baggage user.id = 42 preserved,
  * RESULT: LINKED (ok).

CONSTRAINTS
  * Do NOT edit demo.py — the instrumentation is already correct.
  * Fix CONFIGURATION only. Inspect:  cat propagation.env
  * Re-test as many times as you like with:  bash run.sh
  * Reset the whole lab with:  ./break_fix.sh --clean

HINT
  Context propagation only happens if a propagator is actually configured.
  Which OTEL_PROPAGATORS value silences every propagator, and which value is
  the W3C Trace Context + Baggage default the SDK ships with?
==============================================================================
EOF

# ==============================================================================
#  SOLUTION  (step by step — try it yourself before reading)
# ==============================================================================
#
#  1) See what is misconfigured:
#
#        cd /tmp/otca-4.1-context-propagation
#        cat propagation.env
#        # -> OTEL_PROPAGATORS=none
#
#     `none` is the no-op propagator. With it, propagate.inject() writes nothing
#     onto the carrier and propagate.extract() returns an empty Context, so the
#     SpanContext (trace_id / span_id / trace-flags) and the Baggage never cross
#     the A -> B boundary. Each service therefore starts its own root trace.
#
#  2) Restore the standard propagators. The OpenTelemetry SDK default is the
#     W3C Trace Context propagator (carries the `traceparent` header) plus the
#     W3C Baggage propagator (carries the `baggage` header):
#
#        echo 'OTEL_PROPAGATORS=tracecontext,baggage' > propagation.env
#
#     (Equivalently, `unset OTEL_PROPAGATORS` / delete the line falls back to
#     the same built-in default: tracecontext,baggage.)
#
#  3) Re-run and confirm:
#
#        bash run.sh
#
#     Expected, now-correct output:
#        [wire] headers handed to Service B:
#            traceparent: 00-<32-hex trace_id>-<16-hex span_id>-01
#            baggage: user.id=42
#        [Service A] trace_id = <X>
#        [Service B] trace_id = <X>          # SAME as A
#        [Service B] parent   = <A.span_id>  # B is a child of A
#        [Service B] baggage user.id = 42    # baggage preserved
#        RESULT: LINKED (ok)
#
#  4) Why this is the whole point of Topic 4.1:
#       - "Context" (trace_id, span_id, trace-flags, plus Baggage) lives only
#         inside a process. To keep a distributed trace connected it must be
#         serialized on the way OUT (inject, by the producer) and rebuilt on the
#         way IN (extract, by the consumer).
#       - A Propagator is what does that serialization. `tracecontext` encodes
#         the SpanContext into the W3C `traceparent` header (format
#         `version-traceid-parentid-traceflags`, e.g. 00-<32hex>-<16hex>-01);
#         `baggage` encodes key/value Baggage into the W3C `baggage` header.
#       - Misconfiguring OTEL_PROPAGATORS (to `none`, or omitting the one a
#         downstream service expects, e.g. b3 vs tracecontext mismatch) silently
#         severs traces: instrumentation still runs, spans still export, but they
#         no longer share a trace_id. That silent break is exactly what the exam
#         wants you to recognize and repair.
#
#  Optional experiments to deepen understanding:
#     * OTEL_PROPAGATORS=b3multi   -> B3 multi-header format (X-B3-TraceId, ...)
#     * OTEL_PROPAGATORS=b3        -> B3 single-header format (b3: trace-span-...)
#       Both still LINK A and B here because A and B share the global propagator.
#       Now set DIFFERENT propagators for the two sides to reproduce a real
#       cross-vendor mismatch and watch the trace fragment again.
# ==============================================================================