#!/usr/bin/env bash
# =============================================================================
#  MCPA — Model Context Protocol Associate
#  Domain 4: Operating MCP in production
#  Topic 4.4: Auditability & Observability          (exam weight: 6.0)
#
#  BREAK & FIX LAB — "the server that went quiet"
#
#  WHAT THIS SCRIPT DOES
#    It deploys a small but real MCP stack into a self-contained directory:
#
#      * an MCP server  (stdio transport, JSON-RPC 2.0, tools + logging)
#      * an MCP client  (a diagnostic probe that drives a full session)
#      * an audit relay (a long-lived sidecar that persists the audit trail)
#      * a logrotate configuration for that audit trail
#
#    and then breaks FOUR things across the two observability planes that
#    MCP keeps deliberately separate:
#
#      the LOGGING plane — notifications/message, verbosity controlled by the
#                          client through logging/setLevel; for the human.
#      the AUDIT  plane — an append-only JSON Lines record of who called what,
#                          never filtered by the client; for the auditor.
#
#  SAFETY
#    Nothing outside $LAB_ROOT is created, modified or deleted. No root, no
#    systemd units, no network listeners, no package installation, no writes
#    to /etc or /var. The only long-lived process is the audit relay, started
#    from $LAB_ROOT and stopped with "$0 cleanup". It is still meant for a
#    disposable lab VM: you will be editing files and killing processes.
#
#  REQUIREMENTS
#    Linux, bash 4+, python3 >= 3.8, coreutils. logrotate optional (a faithful
#    shell emulation is used when it is absent).
#
#  USAGE
#    ./mcpa-4.4-break-fix.sh                 deploy the stack, break it, brief you
#    ./mcpa-4.4-break-fix.sh check           run the acceptance gate
#    ./mcpa-4.4-break-fix.sh status          show the live state of the stack
#    ./mcpa-4.4-break-fix.sh hints [1-4]     diagnostic hints (commands, not answers)
#    ./mcpa-4.4-break-fix.sh reset           re-deploy the broken stack from scratch
#    ./mcpa-4.4-break-fix.sh cleanup         stop the relay and remove $LAB_ROOT
#
#    Environment: LAB_ROOT=/path/to/lab   (default: $HOME/mcp-audit-lab)
#                 LAB_ASSUME_YES=1        (skip the confirmation prompt)
#
#  The full, step-by-step solution is at the END of this file, commented out.
#  Do not read it until "$0 check" has beaten you at least twice.
# =============================================================================

set -Eeuo pipefail

LAB_ROOT="${LAB_ROOT:-$HOME/mcp-audit-lab}"
LAB_NAME="mcpa-4.4-auditability-observability"
PY_BIN="${PY_BIN:-python3}"

# ---------------------------------------------------------------------------
# Presentation helpers
# ---------------------------------------------------------------------------
if [ -t 1 ] && command -v tput >/dev/null 2>&1 && [ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]; then
    C_BOLD="$(tput bold)"; C_RED="$(tput setaf 1)"; C_GRN="$(tput setaf 2)"
    C_YEL="$(tput setaf 3)"; C_CYA="$(tput setaf 6)"; C_OFF="$(tput sgr0)"
else
    C_BOLD=""; C_RED=""; C_GRN=""; C_YEL=""; C_CYA=""; C_OFF=""
fi

say()  { printf '%s\n' "$*"; }
hdr()  { printf '\n%s%s%s\n' "$C_BOLD$C_CYA" "$*" "$C_OFF"; }
warn() { printf '%s%s%s\n' "$C_YEL" "$*" "$C_OFF" >&2; }
die()  { printf '%s%s%s\n' "$C_RED" "ERROR: $*" "$C_OFF" >&2; exit 1; }
rule() { printf '%s\n' "-----------------------------------------------------------------------"; }

require() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

assert_safe_root() {
    # Refuse to operate on anything that is not clearly a scratch directory.
    case "$LAB_ROOT" in
        /|/home|/root|/usr|/etc|/var|/opt|/tmp) die "refusing to use LAB_ROOT=$LAB_ROOT" ;;
        /*) : ;;
        *)  die "LAB_ROOT must be an absolute path (got: $LAB_ROOT)" ;;
    esac
    [ "$LAB_ROOT" = "$HOME" ] && die "refusing to use your home directory as LAB_ROOT"
    return 0
}

confirm() {
    [ "${LAB_ASSUME_YES:-0}" = "1" ] && return 0
    printf '%s' "This lab writes to ${LAB_ROOT} and starts a background process. Continue? [y/N] "
    local answer=""
    read -r answer || true
    case "$answer" in y|Y|yes|YES) return 0 ;; *) die "aborted by the operator" ;; esac
}

# ---------------------------------------------------------------------------
# Deployment: write the (deliberately faulted) stack to disk
# ---------------------------------------------------------------------------
deploy_tree() {
    mkdir -p "$LAB_ROOT"/{bin,server,client,etc/logrotate.d,var/run,var/log/mcp}
    chmod 0755 "$LAB_ROOT" "$LAB_ROOT/var" "$LAB_ROOT/var/log" "$LAB_ROOT/var/log/mcp" "$LAB_ROOT/var/run"
}

write_env() {
    cat > "$LAB_ROOT/lab.env" <<ENVFILE
# Generated by $LAB_NAME on $(date -u +%Y-%m-%dT%H:%M:%SZ)
LAB_ROOT=$LAB_ROOT
MCP_AUDIT_FIFO=$LAB_ROOT/var/run/audit.fifo
MCP_AUDIT_LOG=$LAB_ROOT/var/log/mcp/audit.jsonl
MCP_RELAY_PID=$LAB_ROOT/var/run/relay.pid
ENVFILE
    chmod 0644 "$LAB_ROOT/lab.env"
}

write_server() {
    cat > "$LAB_ROOT/server/mcp_audit_server.py" <<'SERVER_PY'
#!/usr/bin/env python3
"""records-audit - a minimal MCP server over the stdio transport.

Only the surface the lab needs is implemented, and it is implemented for
real: JSON-RPC 2.0 framed as newline-delimited objects on stdin/stdout.

    initialize
    notifications/initialized
    tools/list
    tools/call            (tool: query_records, with progress notifications)
    logging/setLevel
    ping

Two observability planes are kept apart on purpose:

    LOGGING  ->  notifications/message, RFC 5424 severities, filtered by the
                 level the client selected with logging/setLevel. This is a
                 courtesy to the human driving the session.

    AUDIT    ->  JSON Lines pushed into a FIFO and persisted by the audit
                 relay. It is NOT filtered by the client: an auditor's record
                 that a caller can silence is not a record.

Spec references:
    https://modelcontextprotocol.io/specification/2025-06-18/basic/transports
    https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging
    https://modelcontextprotocol.io/specification/2025-06-18/basic/utilities/progress
"""

import datetime
import json
import os
import sys
import time
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
LAB_ROOT = os.environ.get("LAB_ROOT") or os.path.dirname(HERE)
AUDIT_FIFO = os.environ.get("MCP_AUDIT_FIFO", os.path.join(LAB_ROOT, "var/run/audit.fifo"))

PROTOCOL_VERSION = "2025-06-18"
SERVER_INFO = {"name": "records-audit", "version": "1.4.0"}

# RFC 5424 severities. Lower number == more severe.
SEVERITY = {
    "emergency": 0, "alert": 1, "critical": 2, "error": 3,
    "warning": 4, "notice": 5, "info": 6, "debug": 7,
}

STATE = {
    "min_level": "warning",                  # until the client raises it
    "session_id": uuid.uuid4().hex[:12],
    "principal": "anonymous",
    "initialized": False,
}


# --------------------------------------------------------------------------
# Wire helpers
# --------------------------------------------------------------------------
def _ts() -> str:
    return (
        datetime.datetime.now(datetime.timezone.utc)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def _send(obj: dict) -> None:
    """Write one JSON-RPC message to the transport."""
    sys.stdout.write(json.dumps(obj, separators=(",", ":")) + "\n")
    sys.stdout.flush()


def _console(text: str) -> None:
    """Operator-facing, human-readable line. Not a protocol message."""
    print("%s records-audit[%d]: %s" % (_ts(), os.getpid(), text))


def ok(mid, result):
    return {"jsonrpc": "2.0", "id": mid, "result": result}


def err(mid, code, message, data=None):
    payload = {"code": code, "message": message}
    if data is not None:
        payload["data"] = data
    return {"jsonrpc": "2.0", "id": mid, "error": payload}


# --------------------------------------------------------------------------
# Audit plane
# --------------------------------------------------------------------------
def _audit_write(line: str) -> None:
    """Push one record into the relay FIFO without ever blocking the server.

    O_NONBLOCK on a FIFO opened for writing fails with ENXIO when no reader
    is attached, which is exactly what we want: a dead sink degrades the
    audit trail, it must never wedge the protocol loop.
    """
    try:
        fd = os.open(AUDIT_FIFO, os.O_WRONLY | os.O_NONBLOCK)
    except OSError as exc:
        _console("audit sink unavailable (%s) - record dropped" % exc.strerror)
        return
    try:
        os.write(fd, line.encode("utf-8"))
    except OSError as exc:
        _console("audit write failed: %s" % exc.strerror)
    finally:
        os.close(fd)


def audit(event: str, request_id=None, **fields) -> None:
    """Append one audit record.

    An audit record has to answer four questions: when, what, who, and under
    which request. Anything less is a log line wearing a badge.
    """
    record = {
        "ts": _ts(),
        "event": event,
        "server": SERVER_INFO["name"],
        "transport": "stdio",
    }
    record.update(fields)
    _audit_write(json.dumps(record, separators=(",", ":")) + "\n")


# --------------------------------------------------------------------------
# Logging plane
# --------------------------------------------------------------------------
def log_message(level: str, logger: str, data: dict) -> None:
    """Emit notifications/message if the client's minimum level allows it."""
    if level not in SEVERITY:
        level = "info"
    if SEVERITY[level] > SEVERITY[STATE["min_level"]]:
        return
    _send({
        "jsonrpc": "2.0",
        "method": "notifications/message",
        "params": {"level": level, "logger": logger, "data": data},
    })


def progress(token, done, total, message):
    if token is None:
        return
    _send({
        "jsonrpc": "2.0",
        "method": "notifications/progress",
        "params": {
            "progressToken": token,
            "progress": done,
            "total": total,
            "message": message,
        },
    })


# --------------------------------------------------------------------------
# Tool implementation
# --------------------------------------------------------------------------
TOOLS = [{
    "name": "query_records",
    "title": "Query incident records",
    "description": "Return synthetic incident records from a named dataset.",
    "inputSchema": {
        "type": "object",
        "properties": {
            "dataset": {"type": "string", "description": "Dataset name."},
            "limit": {"type": "integer", "minimum": 1, "maximum": 50},
        },
        "required": ["dataset"],
    },
}]


def _query(args: dict):
    dataset = str(args.get("dataset") or "incidents")
    try:
        limit = int(args.get("limit") or 5)
    except (TypeError, ValueError):
        limit = 5
    limit = max(1, min(limit, 50))
    grades = ["sev1", "sev2", "sev3"]
    return [
        {"id": "%s-%03d" % (dataset, i), "severity": grades[i % 3]}
        for i in range(1, limit + 1)
    ]


# --------------------------------------------------------------------------
# Dispatch
# --------------------------------------------------------------------------
def dispatch(msg: dict):
    mid = msg.get("id")
    method = msg.get("method")
    params = msg.get("params") or {}

    if method == "initialize":
        client = params.get("clientInfo") or {}
        STATE["principal"] = client.get("name") or "anonymous"
        audit(
            "session.initialize",
            request_id=mid,
            client_protocol=params.get("protocolVersion"),
            client_version=client.get("version"),
        )
        log_message("notice", "session", {
            "phase": "initialize",
            "client": STATE["principal"],
            "session_id": STATE["session_id"],
        })
        return ok(mid, {
            "protocolVersion": PROTOCOL_VERSION,
            "capabilities": {
                "tools": {"listChanged": False},
            },
            "serverInfo": SERVER_INFO,
            "instructions": "Query incident records. All calls are audited.",
        })

    if method == "notifications/initialized":
        STATE["initialized"] = True
        return None

    if method == "ping":
        return ok(mid, {})

    if method == "logging/setLevel":
        return err(mid, -32601, "Method not found: logging/setLevel")

    if method == "tools/list":
        audit("tools.list", request_id=mid, count=len(TOOLS))
        return ok(mid, {"tools": TOOLS})

    if method == "tools/call":
        name = params.get("name")
        args = params.get("arguments") or {}
        token = (params.get("_meta") or {}).get("progressToken")

        if name != "query_records":
            audit("tool.error", request_id=mid, tool=name, reason="unknown_tool")
            log_message("error", "tool.dispatch", {"tool": name, "reason": "unknown_tool"})
            return err(mid, -32602, "Unknown tool: %s" % name)

        started = time.monotonic()
        log_message("info", "tool.query_records", {
            "phase": "start",
            "dataset": args.get("dataset"),
            "limit": args.get("limit"),
            "session_id": STATE["session_id"],
            "request_id": mid,
        })
        audit("tool.call", request_id=mid, tool=name, arguments=args, outcome="started")

        rows = _query(args)
        total = len(rows)
        for index in range(total):
            progress(token, index + 1, total, "scanning %s" % args.get("dataset"))

        duration_ms = int((time.monotonic() - started) * 1000)
        log_message("info", "tool.query_records", {
            "phase": "end",
            "rows": total,
            "duration_ms": duration_ms,
            "session_id": STATE["session_id"],
            "request_id": mid,
        })
        audit(
            "tool.call",
            request_id=mid,
            tool=name,
            outcome="ok",
            rows=total,
            duration_ms=duration_ms,
        )
        return ok(mid, {
            "content": [{
                "type": "text",
                "text": json.dumps({"rows": rows}, indent=2),
            }],
            "isError": False,
        })

    if method and method.startswith("notifications/"):
        return None

    return err(mid, -32601, "Method not found: %s" % method)


def main() -> int:
    _console("v%s starting, audit sink %s" % (SERVER_INFO["version"], AUDIT_FIFO))
    audit("server.start", pid=os.getpid(), version=SERVER_INFO["version"])

    for raw in sys.stdin:
        raw = raw.strip()
        if not raw:
            continue
        try:
            msg = json.loads(raw)
        except json.JSONDecodeError as exc:
            _send(err(None, -32700, "Parse error", str(exc)))
            continue
        try:
            response = dispatch(msg)
        except Exception as exc:                      # never die on one request
            audit("server.exception", request_id=msg.get("id"), error=repr(exc))
            log_message("critical", "dispatch", {"error": repr(exc)})
            response = err(msg.get("id"), -32603, "Internal error", repr(exc))
        if response is not None:
            _send(response)

    audit("session.close", reason="stdin_eof")
    _console("stdin closed, exiting")
    return 0


if __name__ == "__main__":
    sys.exit(main())
SERVER_PY
    chmod 0755 "$LAB_ROOT/server/mcp_audit_server.py"
}

write_relay() {
    cat > "$LAB_ROOT/bin/audit-relay.py" <<'RELAY_PY'
#!/usr/bin/env python3
"""audit-relay - a long-lived sidecar that persists the MCP audit trail.

It reads JSON Lines from a FIFO and appends them to the audit log, holding
the log file open for the lifetime of the process. On SIGHUP it closes the
current descriptor and opens the configured path again - which is how a
log-shipping process survives rotation.
"""

import datetime
import json
import os
import signal
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LAB_ROOT = os.environ.get("LAB_ROOT") or os.path.dirname(HERE)
FIFO = os.environ.get("MCP_AUDIT_FIFO", os.path.join(LAB_ROOT, "var/run/audit.fifo"))
LOG = os.environ.get("MCP_AUDIT_LOG", os.path.join(LAB_ROOT, "var/log/mcp/audit.jsonl"))
PIDFILE = os.environ.get("MCP_RELAY_PID", os.path.join(LAB_ROOT, "var/run/relay.pid"))

_reopen_requested = False


def _ts():
    return (
        datetime.datetime.now(datetime.timezone.utc)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )


def _on_hup(signum, frame):
    # Deferred on purpose: the reopen happens immediately before the next
    # write, so no record can be written to the descriptor being retired.
    global _reopen_requested
    _reopen_requested = True
    sys.stderr.write("%s relay: SIGHUP received, reopen scheduled\n" % _ts())
    sys.stderr.flush()


def _on_term(signum, frame):
    sys.stderr.write("%s relay: signal %d, shutting down\n" % (_ts(), signum))
    sys.stderr.flush()
    try:
        os.unlink(PIDFILE)
    except OSError:
        pass
    raise SystemExit(0)


def open_log():
    return os.open(LOG, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o640)


def main():
    global _reopen_requested
    signal.signal(signal.SIGHUP, _on_hup)
    signal.signal(signal.SIGTERM, _on_term)
    signal.signal(signal.SIGINT, _on_term)

    os.makedirs(os.path.dirname(LOG), exist_ok=True)
    if not os.path.exists(FIFO):
        os.mkfifo(FIFO, 0o660)
    with open(PIDFILE, "w") as handle:
        handle.write(str(os.getpid()))

    logfd = open_log()
    sys.stderr.write("%s relay: pid %d, fifo %s -> %s\n" % (_ts(), os.getpid(), FIFO, LOG))
    sys.stderr.flush()

    while True:
        # Opening a FIFO for reading blocks until a writer appears; when the
        # last writer closes we get EOF and loop round to wait for the next.
        with open(FIFO, "r", buffering=1) as fifo:
            while True:
                line = fifo.readline()
                if line == "":
                    break
                if _reopen_requested:
                    os.close(logfd)
                    logfd = open_log()
                    _reopen_requested = False
                    notice = json.dumps({
                        "ts": _ts(),
                        "event": "relay.reopen",
                        "log": LOG,
                        "pid": os.getpid(),
                    }, separators=(",", ":"))
                    os.write(logfd, (notice + "\n").encode("utf-8"))
                if not line.strip():
                    continue
                os.write(logfd, line.encode("utf-8"))


if __name__ == "__main__":
    sys.exit(main())
RELAY_PY
    chmod 0755 "$LAB_ROOT/bin/audit-relay.py"
}

write_relay_ctl() {
    cat > "$LAB_ROOT/bin/relay-ctl.sh" <<'RELAYCTL_SH'
#!/usr/bin/env bash
# relay-ctl.sh {start|ensure|stop|restart|status} - supervise the audit relay.
set -uo pipefail

LAB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY_BIN="${PY_BIN:-python3}"
PIDFILE="$LAB_ROOT/var/run/relay.pid"
FIFO="$LAB_ROOT/var/run/audit.fifo"
RELAY_LOG="$LAB_ROOT/var/log/mcp/relay.log"

relay_pid() {
    [ -f "$PIDFILE" ] || return 1
    local pid
    pid="$(cat "$PIDFILE" 2>/dev/null || true)"
    [ -n "$pid" ] || return 1
    kill -0 "$pid" 2>/dev/null || return 1
    printf '%s\n' "$pid"
}

start_relay() {
    if relay_pid >/dev/null; then
        printf 'relay already running (pid %s)\n' "$(relay_pid)"
        return 0
    fi
    [ -p "$FIFO" ] || mkfifo -m 0660 "$FIFO"
    LAB_ROOT="$LAB_ROOT" nohup "$PY_BIN" "$LAB_ROOT/bin/audit-relay.py" >>"$RELAY_LOG" 2>&1 &
    disown 2>/dev/null || true
    sleep 0.4
    if relay_pid >/dev/null; then
        printf 'relay started (pid %s)\n' "$(relay_pid)"
    else
        printf 'relay failed to start; see %s\n' "$RELAY_LOG" >&2
        return 1
    fi
}

stop_relay() {
    local pid
    if ! pid="$(relay_pid)"; then
        printf 'relay not running\n'
        rm -f "$PIDFILE"
        return 0
    fi
    kill -TERM "$pid" 2>/dev/null || true
    for _ in 1 2 3 4 5 6 7 8 9 10; do
        kill -0 "$pid" 2>/dev/null || break
        sleep 0.2
    done
    kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null
    rm -f "$PIDFILE"
    printf 'relay stopped\n'
}

status_relay() {
    local pid
    if pid="$(relay_pid)"; then
        printf 'relay: running (pid %s)\n' "$pid"
        printf 'open descriptors under var/log/mcp:\n'
        local fd target
        for fd in /proc/"$pid"/fd/*; do
            target="$(readlink "$fd" 2>/dev/null || true)"
            case "$target" in
                *"/var/log/mcp/"*) printf '  fd %-4s -> %s\n' "$(basename "$fd")" "$target" ;;
            esac
        done
    else
        printf 'relay: NOT running\n'
        return 1
    fi
}

case "${1:-status}" in
    start|ensure) start_relay ;;
    stop)         stop_relay ;;
    restart)      stop_relay; start_relay ;;
    status)       status_relay ;;
    *)            printf 'usage: %s {start|ensure|stop|restart|status}\n' "$0" >&2; exit 2 ;;
esac
RELAYCTL_SH
    chmod 0755 "$LAB_ROOT/bin/relay-ctl.sh"
}

write_logrotate_conf() {
    # NOTE: unquoted heredoc - $LAB_ROOT is baked in as an absolute path,
    # which is what a real /etc/logrotate.d drop-in would contain.
    cat > "$LAB_ROOT/etc/logrotate.d/mcp-audit.conf" <<CONF
# MCP audit trail rotation - lab drop-in.
# On a real host this file would live at /etc/logrotate.d/mcp-audit.
$LAB_ROOT/var/log/mcp/audit.jsonl {
    rotate 5
    size 1k
    missingok
    notifempty
    create 0640
}
CONF
    chmod 0644 "$LAB_ROOT/etc/logrotate.d/mcp-audit.conf"
}

write_rotate() {
    cat > "$LAB_ROOT/bin/rotate-now.sh" <<'ROTATE_SH'
#!/usr/bin/env bash
# rotate-now.sh - force one rotation of the audit trail.
#
# Uses the real logrotate binary when it is available, so the configuration
# under etc/logrotate.d is exercised exactly as it would be on a host. When
# logrotate is missing (or refuses), it falls back to a faithful emulation of
# the directives this lab uses: copytruncate, create, rotate N, postrotate.
set -uo pipefail

LAB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="$LAB_ROOT/etc/logrotate.d/mcp-audit.conf"
LOG="$LAB_ROOT/var/log/mcp/audit.jsonl"
STATE="$LAB_ROOT/var/run/logrotate.state"

[ -f "$CONF" ] || { printf 'missing config: %s\n' "$CONF" >&2; exit 1; }
[ -f "$LOG" ]  || : > "$LOG"

run_postrotate() {
    local block
    block="$(sed -n '/^[[:space:]]*postrotate/,/^[[:space:]]*endscript/p' "$CONF" | sed '1d;$d')"
    if [ -n "$block" ]; then
        printf 'emulation: running postrotate block\n'
        printf '%s\n' "$block" | /bin/sh
    fi
}

emulate_rotation() {
    printf 'emulation: rotating %s\n' "$LOG"
    if grep -qE '^[[:space:]]*copytruncate' "$CONF"; then
        cp -p "$LOG" "$LOG.1" 2>/dev/null || true
        : > "$LOG"
        run_postrotate
        return 0
    fi
    local i
    for i in 4 3 2 1; do
        if [ -f "$LOG.$i" ]; then mv -f "$LOG.$i" "$LOG.$((i + 1))"; fi
    done
    mv -f "$LOG" "$LOG.1"
    if grep -qE '^[[:space:]]*create' "$CONF"; then
        : > "$LOG"
        chmod 0640 "$LOG"
    fi
    run_postrotate
}

before_inode="$(stat -c %i "$LOG" 2>/dev/null || echo 0)"

if command -v logrotate >/dev/null 2>&1; then
    printf 'using logrotate: %s\n' "$(command -v logrotate)"
    logrotate --force --state "$STATE" "$CONF" 2>&1 || printf 'logrotate exited %d\n' "$?"
else
    printf 'logrotate not installed on this VM\n'
fi

after_inode="$(stat -c %i "$LOG" 2>/dev/null || echo 0)"
if [ "$before_inode" = "$after_inode" ] && [ ! -f "$LOG.1" ]; then
    printf 'no rotation observed, falling back to emulation\n'
    emulate_rotation
fi

printf 'post-rotation state:\n'
ls -l --time-style=+%%H:%%M:%%S "$LAB_ROOT/var/log/mcp/" | sed 's/^/  /'
ROTATE_SH
    chmod 0755 "$LAB_ROOT/bin/rotate-now.sh"
}

write_probe() {
    cat > "$LAB_ROOT/client/mcp_probe.py" <<'PROBE_PY'
#!/usr/bin/env python3
"""mcp-probe - a deliberately literal MCP client, used as a diagnostic tool.

It spawns the server over the stdio transport and drives one complete
session: initialize, initialized, logging/setLevel, tools/list, tools/call
(with a progressToken), then closes stdin.

Unlike a production client it does not give the server the benefit of the
doubt. Every line that arrives on stdout must parse as a JSON-RPC message,
and it calls logging/setLevel even when the capability was not advertised,
so that the failure mode is visible rather than assumed.

Usage:  mcp_probe.py [--json] [--timeout SECONDS] [--level LEVEL]
Exit:   0 clean session, 10 transport corruption, 11 protocol failure.
"""

import argparse
import json
import os
import queue
import subprocess
import sys
import threading

HERE = os.path.dirname(os.path.abspath(__file__))
LAB_ROOT = os.environ.get("LAB_ROOT") or os.path.dirname(HERE)
SERVER = os.path.join(LAB_ROOT, "server", "mcp_audit_server.py")
STDERR_LOG = os.path.join(LAB_ROOT, "var", "log", "mcp", "server.stderr.log")

CLIENT_INFO = {"name": "mcp-probe", "version": "0.3.0"}
PROTOCOL_VERSION = "2025-06-18"


class TransportCorruption(Exception):
    def __init__(self, line):
        super().__init__("non JSON-RPC data on stdout")
        self.line = line


class Session:
    def __init__(self, timeout):
        self.timeout = timeout
        self.errfh = open(STDERR_LOG, "ab")
        env = dict(os.environ)
        env["LAB_ROOT"] = LAB_ROOT
        # -u so the server's stdout is unbuffered: this probe measures what
        # the server writes, in the order it writes it.
        self.proc = subprocess.Popen(
            [sys.executable, "-u", SERVER],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=self.errfh,
            cwd=LAB_ROOT,
            env=env,
            text=True,
            bufsize=1,
        )
        self.inbox = queue.Queue()
        self.reader = threading.Thread(target=self._pump, daemon=True)
        self.reader.start()

    def _pump(self):
        for line in self.proc.stdout:
            self.inbox.put(line.rstrip("\n"))
        self.inbox.put(None)

    def send(self, obj):
        self.proc.stdin.write(json.dumps(obj, separators=(",", ":")) + "\n")
        self.proc.stdin.flush()

    def recv(self):
        try:
            raw = self.inbox.get(timeout=self.timeout)
        except queue.Empty:
            raise TimeoutError("no message within %.1fs" % self.timeout)
        if raw is None:
            raise EOFError("server closed stdout")
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            raise TransportCorruption(raw)

    def await_response(self, request_id, collector):
        """Drain notifications until the matching response arrives."""
        while True:
            msg = self.recv()
            if "id" in msg and msg.get("id") == request_id:
                return msg
            method = msg.get("method", "")
            if method == "notifications/message":
                collector["log"].append(msg.get("params") or {})
            elif method == "notifications/progress":
                collector["progress"].append(msg.get("params") or {})
            else:
                collector["other"].append(msg)

    def close(self):
        try:
            self.proc.stdin.close()
        except Exception:
            pass
        try:
            self.proc.wait(timeout=3)
        except Exception:
            self.proc.kill()
        self.errfh.close()


def run(timeout, level):
    report = {
        "transport_clean": True,
        "offending_stdout_line": None,
        "handshake_ok": False,
        "protocol_version": None,
        "server_capabilities": None,
        "logging_capability": False,
        "set_level_ok": False,
        "set_level_error": None,
        "log_notifications": [],
        "info_logs": 0,
        "progress_notifications": 0,
        "tool_call_ok": False,
        "tool_rows": 0,
        "error": None,
    }
    collector = {"log": [], "progress": [], "other": []}
    session = Session(timeout)
    try:
        session.send({
            "jsonrpc": "2.0", "id": 1, "method": "initialize",
            "params": {
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {},
                "clientInfo": CLIENT_INFO,
            },
        })
        init = session.await_response(1, collector)
        if "error" in init:
            report["error"] = "initialize failed: %s" % init["error"]
            return report, 11
        result = init.get("result") or {}
        report["handshake_ok"] = True
        report["protocol_version"] = result.get("protocolVersion")
        caps = result.get("capabilities") or {}
        report["server_capabilities"] = sorted(caps.keys())
        report["logging_capability"] = "logging" in caps

        session.send({"jsonrpc": "2.0", "method": "notifications/initialized"})

        # Called unconditionally: a probe reports what the server does, not
        # what its advertised capabilities promise.
        session.send({
            "jsonrpc": "2.0", "id": 2, "method": "logging/setLevel",
            "params": {"level": level},
        })
        set_level = session.await_response(2, collector)
        if "error" in set_level:
            report["set_level_error"] = set_level["error"]
        else:
            report["set_level_ok"] = True

        session.send({"jsonrpc": "2.0", "id": 3, "method": "tools/list", "params": {}})
        session.await_response(3, collector)

        session.send({
            "jsonrpc": "2.0", "id": 4, "method": "tools/call",
            "params": {
                "name": "query_records",
                "arguments": {"dataset": "incidents", "limit": 3},
                "_meta": {"progressToken": "probe-4"},
            },
        })
        call = session.await_response(4, collector)
        if "error" not in call:
            result = call.get("result") or {}
            report["tool_call_ok"] = not result.get("isError", False)
            try:
                payload = json.loads((result.get("content") or [{}])[0].get("text", "{}"))
                report["tool_rows"] = len(payload.get("rows", []))
            except (ValueError, IndexError, AttributeError):
                pass
    except TransportCorruption as exc:
        report["transport_clean"] = False
        report["offending_stdout_line"] = exc.line
        report["error"] = "stdout carried data that is not a JSON-RPC message"
        session.close()
        report["log_notifications"] = collector["log"]
        report["info_logs"] = sum(1 for m in collector["log"] if m.get("level") == "info")
        report["progress_notifications"] = len(collector["progress"])
        return report, 10
    except (TimeoutError, EOFError) as exc:
        report["error"] = str(exc)
        session.close()
        return report, 11
    finally:
        try:
            session.close()
        except Exception:
            pass

    report["log_notifications"] = collector["log"]
    report["info_logs"] = sum(1 for m in collector["log"] if m.get("level") == "info")
    report["progress_notifications"] = len(collector["progress"])
    return report, 0


def human(report, code):
    def mark(value):
        return "OK  " if value else "FAIL"

    print("MCP probe -> %s" % SERVER)
    print("-" * 71)
    print("  %s transport    stdout carries only JSON-RPC messages" % mark(report["transport_clean"]))
    if not report["transport_clean"]:
        print("       offending line: %r" % report["offending_stdout_line"])
        print("       on the stdio transport stdout IS the message channel;")
        print("       one stray byte desynchronises the whole session.")
    print("  %s handshake    protocolVersion=%s capabilities=%s"
          % (mark(report["handshake_ok"]), report["protocol_version"], report["server_capabilities"]))
    print("  %s logging cap  server advertises the logging capability" % mark(report["logging_capability"]))
    print("  %s setLevel     logging/setLevel accepted" % mark(report["set_level_ok"]))
    if report["set_level_error"]:
        print("       server answered: %s" % json.dumps(report["set_level_error"]))
    print("  %s log stream   %d notifications/message (%d at level=info)"
          % (mark(report["info_logs"] >= 2), len(report["log_notifications"]), report["info_logs"]))
    print("  %s progress     %d notifications/progress"
          % (mark(report["progress_notifications"] > 0), report["progress_notifications"]))
    print("  %s tools/call   query_records returned %d rows"
          % (mark(report["tool_call_ok"]), report["tool_rows"]))
    if report["error"]:
        print("\n  diagnosis: %s" % report["error"])
    print("\n  server stderr: %s" % STDERR_LOG)
    print("  exit code: %d" % code)


def main():
    parser = argparse.ArgumentParser(description="Drive one MCP session and report on it.")
    parser.add_argument("--json", action="store_true", help="emit the raw report as JSON")
    parser.add_argument("--timeout", type=float, default=8.0)
    parser.add_argument("--level", default="info")
    args = parser.parse_args()

    os.makedirs(os.path.dirname(STDERR_LOG), exist_ok=True)
    report, code = run(args.timeout, args.level)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        human(report, code)
    return code


if __name__ == "__main__":
    sys.exit(main())
PROBE_PY
    chmod 0755 "$LAB_ROOT/client/mcp_probe.py"
}

write_checks() {
    cat > "$LAB_ROOT/bin/run-checks.sh" <<'CHECKS_SH'
#!/usr/bin/env bash
# run-checks.sh - the acceptance gate for MCPA 4.4.
#
# Four checks, executed in order. CHECK 4 rotates the audit trail, so it runs
# last. Do not edit this file: it is the specification of "fixed".
set -uo pipefail

LAB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY_BIN="${PY_BIN:-python3}"
REPORT="$LAB_ROOT/var/run/probe-report.json"
AUDIT_LOG="$LAB_ROOT/var/log/mcp/audit.jsonl"

if [ -t 1 ]; then
    G="$(tput setaf 2 2>/dev/null || true)"; R="$(tput setaf 1 2>/dev/null || true)"
    Y="$(tput setaf 3 2>/dev/null || true)"; B="$(tput bold 2>/dev/null || true)"
    O="$(tput sgr0 2>/dev/null || true)"
else
    G=""; R=""; Y=""; B=""; O=""
fi

PASS=0; FAIL=0
pass() { printf '  %sPASS%s  %s\n' "$G" "$O" "$1"; PASS=$((PASS + 1)); }
fail() { printf '  %sFAIL%s  %s\n' "$R" "$O" "$1"; FAIL=$((FAIL + 1)); }
skip() { printf '  %sBLOCKED%s  %s\n' "$Y" "$O" "$1"; FAIL=$((FAIL + 1)); }
head() { printf '\n%s%s%s\n' "$B" "$1" "$O"; }

"$LAB_ROOT/bin/relay-ctl.sh" ensure >/dev/null 2>&1 || true

head "Driving one MCP session"
"$PY_BIN" "$LAB_ROOT/client/mcp_probe.py" --json >"$REPORT" 2>"$LAB_ROOT/var/run/probe.err"
PROBE_RC=$?
printf '  probe exit code: %d  (report: %s)\n' "$PROBE_RC" "$REPORT"

field() {
    "$PY_BIN" - "$REPORT" "$1" <<'PYEOF'
import json, sys
try:
    with open(sys.argv[1]) as handle:
        report = json.load(handle)
except Exception:
    print("")
    sys.exit(0)
value = report.get(sys.argv[2])
if isinstance(value, bool):
    print("true" if value else "false")
elif value is None:
    print("")
else:
    print(value if isinstance(value, (int, float, str)) else json.dumps(value))
PYEOF
}

# --- CHECK 1 -------------------------------------------------------------
head "CHECK 1 - stdio transport purity"
CLEAN="$(field transport_clean)"
if [ "$CLEAN" = "true" ]; then
    pass "every line on the server's stdout parsed as a JSON-RPC message"
else
    fail "stdout carried non-protocol data: $(field offending_stdout_line)"
    printf '        spec: stdout is the message channel; logs belong on stderr.\n'
fi

# --- CHECK 2 -------------------------------------------------------------
head "CHECK 2 - the logging plane is controllable"
if [ "$CLEAN" != "true" ]; then
    skip "cannot evaluate the logging plane while the transport is corrupt"
else
    CAP="$(field logging_capability)"; LVL="$(field set_level_ok)"; INFO="$(field info_logs)"
    [ -z "$INFO" ] && INFO=0
    if [ "$CAP" = "true" ] && [ "$LVL" = "true" ] && [ "$INFO" -ge 2 ]; then
        pass "logging capability advertised, setLevel accepted, ${INFO} info messages received"
    else
        [ "$CAP" = "true" ] || fail "initialize result does not advertise the logging capability"
        [ "$LVL" = "true" ] || fail "logging/setLevel rejected: $(field set_level_error)"
        [ "$INFO" -ge 2 ]   || fail "only ${INFO} notifications/message at level=info (expected >= 2)"
    fi
fi

# --- CHECK 3 -------------------------------------------------------------
head "CHECK 3 - audit records are traceable"
"$PY_BIN" - "$AUDIT_LOG" <<'PYEOF'
import json, sys
path = sys.argv[1]
required = ("request_id", "session_id", "principal")
try:
    with open(path) as handle:
        records = [json.loads(line) for line in handle if line.strip()]
except FileNotFoundError:
    print("NO_LOG")
    sys.exit(2)
except json.JSONDecodeError as exc:
    print("CORRUPT %s" % exc)
    sys.exit(3)
calls = [r for r in records if r.get("event") == "tool.call"]
if not calls:
    print("NO_CALLS")
    sys.exit(2)
missing = set()
for record in calls:
    for key in required:
        if record.get(key) in (None, ""):
            missing.add(key)
if missing:
    print("MISSING %s" % ",".join(sorted(missing)))
    print("SAMPLE %s" % json.dumps(calls[-1]))
    sys.exit(1)
print("OK %d" % len(calls))
PYEOF
C3=$?
C3OUT="$("$PY_BIN" - "$AUDIT_LOG" <<'PYEOF'
import json, sys
try:
    with open(sys.argv[1]) as handle:
        records = [json.loads(line) for line in handle if line.strip()]
    calls = [r for r in records if r.get("event") == "tool.call"]
    print(json.dumps(calls[-1]) if calls else "")
except Exception:
    print("")
PYEOF
)"
case "$C3" in
    0) pass "tool.call records carry request_id, session_id and principal" ;;
    1) fail "tool.call records are not attributable"
       printf '        last record: %s\n' "$C3OUT" ;;
    2) if [ "$CLEAN" != "true" ]; then
           skip "no tool.call records were produced (blocked by CHECK 1)"
       else
           fail "no tool.call records in $AUDIT_LOG - is the relay running?"
       fi ;;
    *) fail "audit trail is not valid JSON Lines" ;;
esac

# --- CHECK 4 -------------------------------------------------------------
head "CHECK 4 - the audit trail survives rotation"
printf '  forcing a rotation...\n'
"$LAB_ROOT/bin/rotate-now.sh" >"$LAB_ROOT/var/run/rotate.log" 2>&1
sed 's/^/        /' "$LAB_ROOT/var/run/rotate.log" | head -n 12
sleep 0.4
"$PY_BIN" - "$LAB_ROOT" <<'PYEOF'
import json, os, sys, time, uuid

lab = sys.argv[1]
fifo = os.path.join(lab, "var/run/audit.fifo")
log = os.path.join(lab, "var/log/mcp/audit.jsonl")
pidfile = os.path.join(lab, "var/run/relay.pid")
marker = "selftest-" + uuid.uuid4().hex[:10]

try:
    pid = int(open(pidfile).read().strip())
    os.kill(pid, 0)
except Exception:
    print("        relay is not running - start it with bin/relay-ctl.sh start")
    sys.exit(2)

for seq in (1, 2, 3):
    record = json.dumps({"event": "relay.selftest", "marker": marker, "seq": seq})
    try:
        fd = os.open(fifo, os.O_WRONLY | os.O_NONBLOCK)
    except OSError as exc:
        print("        cannot write to the audit FIFO: %s" % exc)
        sys.exit(2)
    try:
        os.write(fd, (record + "\n").encode())
    finally:
        os.close(fd)
    time.sleep(0.15)

time.sleep(0.4)
landed = 0
if os.path.exists(log):
    with open(log) as handle:
        landed = sum(1 for line in handle if marker in line)

# Where is the relay actually writing? A process writes to an inode, not to
# a path: after a rename-based rotation the descriptor follows the old file.
live_inode = os.stat(log).st_ino if os.path.exists(log) else -1
misdirected = []
fddir = "/proc/%d/fd" % pid
if os.path.isdir(fddir):
    for entry in sorted(os.listdir(fddir)):
        try:
            target = os.readlink(os.path.join(fddir, entry))
        except OSError:
            continue
        if "/var/log/mcp/" not in target:
            continue
        if target.endswith("(deleted)"):
            misdirected.append("fd %s -> %s" % (entry, target))
            continue
        try:
            if os.stat(target).st_ino != live_inode:
                misdirected.append("fd %s -> %s (inode %d, live file is %d)"
                                   % (entry, target, os.stat(target).st_ino, live_inode))
        except OSError:
            misdirected.append("fd %s -> %s (unstattable)" % (entry, target))

if landed == 3 and not misdirected:
    print("        3/3 post-rotation records landed in the live audit trail")
    sys.exit(0)

print("        %d/3 post-rotation records reached %s" % (landed, log))
for item in misdirected:
    print("        relay descriptor misdirected: %s" % item)
sys.exit(1)
PYEOF
C4=$?
case "$C4" in
    0) pass "records written after rotation land in the live audit trail" ;;
    2) fail "the audit relay is not consuming the FIFO" ;;
    *) fail "rotation orphaned the relay's descriptor - the audit trail went silent" ;;
esac

# --- verdict -------------------------------------------------------------
printf '\n'
printf -- '-----------------------------------------------------------------------\n'
if [ "$FAIL" -eq 0 ]; then
    printf '%sLAB PASSED%s  %d/%d checks green.\n' "$G$B" "$O" "$PASS" "$((PASS + FAIL))"
    printf 'The session is observable, the audit trail is attributable and durable.\n'
    exit 0
fi
printf '%sLAB FAILED%s  %d passed, %d failed. Keep going: %s hints\n' \
    "$R$B" "$O" "$PASS" "$FAIL" "$LAB_ROOT/../$(basename "$0" .sh)"
printf 'Re-run this gate with: %s\n' "$LAB_ROOT/bin/run-checks.sh"
exit 1
CHECKS_SH
    chmod 0755 "$LAB_ROOT/bin/run-checks.sh"
}

write_readme() {
    cat > "$LAB_ROOT/README.txt" <<'READMEFILE'
MCPA 4.4 - Auditability & Observability - break & fix lab
=========================================================

Layout
    server/mcp_audit_server.py     the MCP server (stdio transport)
    client/mcp_probe.py            diagnostic MCP client
    bin/audit-relay.py             audit sink daemon (reads the FIFO)
    bin/relay-ctl.sh               start|ensure|stop|restart|status
    bin/rotate-now.sh              force one rotation of the audit trail
    bin/run-checks.sh              the acceptance gate (do not edit)
    etc/logrotate.d/mcp-audit.conf rotation policy for the audit trail
    var/run/audit.fifo             audit transport between server and relay
    var/log/mcp/audit.jsonl        the audit trail
    var/log/mcp/server.stderr.log  whatever the server writes to stderr
    var/log/mcp/relay.log          relay's own stderr

You may edit anything under this directory EXCEPT bin/run-checks.sh.

Rule of the house
    The logging plane is a convenience for the human at the other end of the
    session; the audit plane is evidence. They fail differently, they are
    fixed differently, and a client must never be able to turn the second one
    off by adjusting the first.
READMEFILE
}

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------
cmd_break() {
    require "$PY_BIN"
    require sed
    require stat
    assert_safe_root

    if [ -d "$LAB_ROOT" ]; then
        warn "a lab already exists at $LAB_ROOT (use '$0 reset' to rebuild it)"
    fi
    confirm

    hdr "Deploying the MCP audit stack into $LAB_ROOT"
    deploy_tree
    write_env
    write_server
    write_probe
    write_relay
    write_relay_ctl
    write_rotate
    write_logrotate_conf
    write_checks
    write_readme
    say "  wrote server, client, relay, rotation policy and the acceptance gate"

    hdr "Starting the audit relay"
    "$LAB_ROOT/bin/relay-ctl.sh" start | sed 's/^/  /'

    hdr "Seeding the audit trail with one session"
    "$PY_BIN" "$LAB_ROOT/client/mcp_probe.py" >/dev/null 2>&1 || true
    say "  done"

    brief
}

brief() {
    hdr "==============  MCPA 4.4 - BREAK & FIX BRIEFING  =============="
    cat <<BRIEF

  SCENARIO

    records-audit is an MCP server that answers questions about incident
    records. It runs over the stdio transport, and every call it serves is
    supposed to leave two traces:

      * live log messages streamed to the client through the MCP logging
        utility (notifications/message), with the verbosity the client picks
        via logging/setLevel;

      * an immutable audit record in ${LAB_ROOT}/var/log/mcp/audit.jsonl,
        written through a FIFO by the audit relay sidecar.

    Last night's deploy shipped four regressions. Compliance is asking for
    the session history of a tool call; the on-call engineer cannot even
    open a session.

  SYMPTOMS YOU WILL SEE

    1. The client dies during the handshake. The probe reports that the
       server's stdout carried something that is not a JSON-RPC message, and
       prints the offending line verbatim. No session can be established.

    2. Once the session opens, the client cannot turn the verbosity up.
       logging/setLevel comes back as JSON-RPC error -32601 (Method not
       found), and the initialize result never mentions the capability. The
       tool executes, but the client watches it in silence.

    3. The audit trail fills up with records that describe WHAT happened and
       never WHO did it or under WHICH request. Correlating a tool call with
       a session, or with the JSON-RPC id the client saw, is impossible.

    4. The moment the audit trail rotates, it goes quiet. The live
       audit.jsonl stops growing while the process cheerfully reports
       success; the bytes are going somewhere else entirely.

  YOUR OBJECTIVE

    Make this exit 0 and print LAB PASSED:

        ${LAB_ROOT}/bin/run-checks.sh

    Four checks, one per regression. They are independent except for the
    first, which blocks the rest: with a corrupt transport there is no
    session to observe.

  RULES

    * Edit anything under ${LAB_ROOT} except bin/run-checks.sh.
    * Do not weaken a check to make it pass. Turning off rotation is not a
      fix; neither is auditing from the client side.
    * The audit plane must not depend on the client's chosen log level.

  START HERE

    cd ${LAB_ROOT}
    ./client/mcp_probe.py                  # human-readable diagnosis
    ./bin/run-checks.sh                    # the gate
    $0 hints 1                             # if you get stuck, per fault
    $0 status                              # live view of the stack

  When the gate is green, read the commented solution at the bottom of this
  script and compare it with what you did.

BRIEF
    rule
}

cmd_check() {
    [ -x "$LAB_ROOT/bin/run-checks.sh" ] || die "no lab at $LAB_ROOT; run '$0' first"
    "$LAB_ROOT/bin/run-checks.sh"
}

cmd_status() {
    [ -d "$LAB_ROOT" ] || die "no lab at $LAB_ROOT; run '$0' first"
    hdr "Relay"
    "$LAB_ROOT/bin/relay-ctl.sh" status 2>&1 | sed 's/^/  /' || true
    hdr "Log directory"
    ls -l "$LAB_ROOT/var/log/mcp/" | sed 's/^/  /'
    hdr "Audit trail (last 3 records)"
    if [ -s "$LAB_ROOT/var/log/mcp/audit.jsonl" ]; then
        tail -n 3 "$LAB_ROOT/var/log/mcp/audit.jsonl" | sed 's/^/  /'
    else
        say "  (empty)"
    fi
    hdr "Server stderr (last 3 lines)"
    if [ -s "$LAB_ROOT/var/log/mcp/server.stderr.log" ]; then
        tail -n 3 "$LAB_ROOT/var/log/mcp/server.stderr.log" | sed 's/^/  /'
    else
        say "  (empty - the server is not logging to stderr)"
    fi
    hdr "Rotation policy"
    sed 's/^/  /' "$LAB_ROOT/etc/logrotate.d/mcp-audit.conf"
}

cmd_hints() {
    local which="${1:-all}"
    if [ "$which" = "all" ] || [ "$which" = "1" ]; then
        hdr "Hints for CHECK 1 - transport"
        cat <<'HINT1'
  See exactly what the server puts on the wire, with no client in the way:

      cd "$LAB_ROOT"
      printf '%s\n' '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"x","version":"0"}}}' \
        | python3 -u server/mcp_audit_server.py | head -n 3

  Then ask the spec one question - on the stdio transport, what is a server
  allowed to write to stdout, and where is it told to write logs instead?
      https://modelcontextprotocol.io/specification/2025-06-18/basic/transports

  Find every place the server writes to stdout:

      grep -n 'print(' server/mcp_audit_server.py
HINT1
    fi
    if [ "$which" = "all" ] || [ "$which" = "2" ]; then
        hdr "Hints for CHECK 2 - logging plane"
        cat <<'HINT2'
      grep -n 'capabilities' server/mcp_audit_server.py
      grep -n 'setLevel\|min_level\|SEVERITY' server/mcp_audit_server.py

  Two separate questions, both required:
    * a client will not use a utility the server never advertised in the
      initialize result;
    * a message less severe than the current minimum level is dropped before
      it is ever sent - and nothing has moved that minimum off its default.
      https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging
HINT2
    fi
    if [ "$which" = "all" ] || [ "$which" = "3" ]; then
        hdr "Hints for CHECK 3 - attributability"
        cat <<'HINT3'
      tail -n 3 var/log/mcp/audit.jsonl | python3 -m json.tool --json-lines 2>/dev/null \
        || tail -n 3 var/log/mcp/audit.jsonl

  Compare what the call sites pass in with what actually reaches the record:

      grep -n 'def audit\|audit(' server/mcp_audit_server.py

  An audit record must answer: when, what, WHO, and under WHICH request id.
  The values already exist in the process - one of them is even handed to
  the function as an argument and then thrown away.
HINT3
    fi
    if [ "$which" = "all" ] || [ "$which" = "4" ]; then
        hdr "Hints for CHECK 4 - durability across rotation"
        cat <<'HINT4'
      bin/relay-ctl.sh status
      ls -l /proc/$(cat var/run/relay.pid)/fd | grep mcp
      stat -c '%i %n' var/log/mcp/audit.jsonl*

  A process writes to an open descriptor, i.e. to an inode, not to a path.
  Renaming the file does not move the descriptor. Two ways out:

    * tell the rotator to signal the writer so it can reopen the path;
    * or tell the rotator to copy the contents and truncate in place.

  The relay already handles SIGHUP (see bin/audit-relay.py). Read what the
  configuration does NOT contain:
      https://man7.org/linux/man-pages/man8/logrotate.8.html
HINT4
    fi
}

cmd_reset() {
    assert_safe_root
    hdr "Resetting the lab"
    if [ -x "$LAB_ROOT/bin/relay-ctl.sh" ]; then
        "$LAB_ROOT/bin/relay-ctl.sh" stop >/dev/null 2>&1 || true
    fi
    rm -rf "${LAB_ROOT:?}"
    LAB_ASSUME_YES=1 cmd_break
}

cmd_cleanup() {
    assert_safe_root
    [ -d "$LAB_ROOT" ] || { say "nothing to clean up at $LAB_ROOT"; return 0; }
    if [ -x "$LAB_ROOT/bin/relay-ctl.sh" ]; then
        "$LAB_ROOT/bin/relay-ctl.sh" stop 2>&1 | sed 's/^/  /' || true
    fi
    rm -rf "${LAB_ROOT:?}"
    say "removed $LAB_ROOT"
}

main() {
    case "${1:-break}" in
        break|deploy|"") cmd_break ;;
        check|verify)    cmd_check ;;
        status)          cmd_status ;;
        hints|hint)      shift || true; cmd_hints "${1:-all}" ;;
        brief)           brief ;;
        reset)           cmd_reset ;;
        cleanup|destroy) cmd_cleanup ;;
        -h|--help|help)
            sed -n '2,60p' "$0" | sed 's/^# \{0,1\}//'
            ;;
        *) die "unknown subcommand: $1 (try --help)" ;;
    esac
}

main "$@"

# =============================================================================
# =============================================================================
#
#   S O L U T I O N   —   do not read before the gate has beaten you twice
#
#   Four regressions, four fixes. Work them in order: with a corrupt
#   transport there is no session, and with no session there is nothing to
#   observe. All paths are relative to $LAB_ROOT.
#
# -----------------------------------------------------------------------------
# FAULT 1 — the server logs to stdout on the stdio transport
# -----------------------------------------------------------------------------
#
#   Diagnosis
#     $ cd "$LAB_ROOT"
#     $ printf '%s\n' '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"x","version":"0"}}}' \
#         | python3 -u server/mcp_audit_server.py | head -n 2
#     2026-09-17T10:04:11.882Z records-audit[41233]: v1.4.0 starting, audit sink /.../audit.fifo
#     {"jsonrpc":"2.0","id":1,"result":{"protocolVersion":"2025-06-18", ...}}
#
#     The first line is not a JSON-RPC message. On the stdio transport the
#     server's stdout IS the message channel — newline-delimited JSON-RPC and
#     nothing else. The spec is explicit: the server MUST NOT write anything
#     to stdout that is not a valid MCP message, and MAY write UTF-8 to
#     stderr for logging.
#     https://modelcontextprotocol.io/specification/2025-06-18/basic/transports
#
#     Any conformant client throws a parse error on that first read, which is
#     why the failure looks like "the server is broken" rather than "someone
#     left a banner in". Note that the banner only appears first because the
#     probe runs the server with -u; with block buffering the same bug shows
#     up as a session that works for a while and then dies mid-stream. The
#     nondeterminism is the bug, not a mitigation.
#
#   Fix — server/mcp_audit_server.py, function _console():
#
#       def _console(text: str) -> None:
#           """Operator-facing, human-readable line. Not a protocol message."""
#           print("%s records-audit[%d]: %s" % (_ts(), os.getpid(), text),
#                 file=sys.stderr, flush=True)
#
#     One line. Every operator-facing message in this server funnels through
#     _console(), which is the point: a single chokepoint for the one stream
#     that must never touch stdout. In your own servers, do the same thing at
#     the framework level — configure the logging handler onto sys.stderr and
#     forbid bare print() in review.
#
#   Verify
#     $ python3 client/mcp_probe.py
#       OK   transport    stdout carries only JSON-RPC messages
#     $ tail -n 2 var/log/mcp/server.stderr.log        # the banner lives here now
#
# -----------------------------------------------------------------------------
# FAULT 2 — the logging capability is not advertised and setLevel is stubbed out
# -----------------------------------------------------------------------------
#
#   Diagnosis
#     $ python3 client/mcp_probe.py
#       OK   handshake    protocolVersion=2025-06-18 capabilities=['tools']
#       FAIL logging cap  server advertises the logging capability
#       FAIL setLevel     logging/setLevel accepted
#            server answered: {"code": -32601, "message": "Method not found: logging/setLevel"}
#       FAIL log stream   1 notifications/message (0 at level=info)
#
#     Two independent defects with one symptom. The initialize result does
#     not declare `logging`, so a real client will never offer the user a
#     verbosity control at all; and even a client that tries anyway is told
#     the method does not exist. Meanwhile STATE["min_level"] sits at its
#     "warning" default, so every info-level message about tool execution is
#     dropped before it reaches the wire. The tool works; nobody can watch it.
#
#   Fix — server/mcp_audit_server.py, in dispatch(), initialize branch:
#
#           return ok(mid, {
#               "protocolVersion": PROTOCOL_VERSION,
#               "capabilities": {
#                   "tools": {"listChanged": False},
#                   "logging": {},                     # <-- declare the utility
#               },
#               "serverInfo": SERVER_INFO,
#               "instructions": "Query incident records. All calls are audited.",
#           })
#
#   Fix — replace the logging/setLevel stub with a real handler:
#
#       if method == "logging/setLevel":
#           level = (params or {}).get("level")
#           if level not in SEVERITY:
#               audit("logging.setlevel.rejected", request_id=mid, level=level)
#               return err(mid, -32602, "Invalid level: %r" % level,
#                          {"supported": sorted(SEVERITY, key=SEVERITY.get)})
#           previous = STATE["min_level"]
#           STATE["min_level"] = level
#           audit("logging.setlevel", request_id=mid, previous=previous, level=level)
#           log_message("notice", "logging", {"min_level": level, "previous": previous})
#           return ok(mid, {})
#
#     Points worth internalising:
#       * levels are RFC 5424 severities (debug .. emergency), and setting a
#         level means "send me this level and everything MORE severe" — the
#         comparison in log_message() is SEVERITY[level] <= SEVERITY[minimum]
#         because lower numbers are more severe;
#         https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging
#         https://datatracker.ietf.org/doc/html/rfc5424
#       * an unknown level is -32602 (Invalid params), not -32601;
#       * the level change is itself an audited event. "Who turned the
#         logging down, and when" is a question incident reviews really ask;
#       * never put secrets, tokens or PII in `data` — notifications/message
#         is client-visible by design, and rate-limiting the stream is the
#         server's job.
#
#   Verify
#     $ python3 client/mcp_probe.py
#       OK   logging cap  server advertises the logging capability
#       OK   setLevel     logging/setLevel accepted
#       OK   log stream   3 notifications/message (2 at level=info)
#       OK   progress     3 notifications/progress
#
# -----------------------------------------------------------------------------
# FAULT 3 — audit records are not attributable
# -----------------------------------------------------------------------------
#
#   Diagnosis
#     $ tail -n 1 var/log/mcp/audit.jsonl
#     {"ts":"2026-09-17T10:07:02.551Z","event":"tool.call","server":"records-audit",
#      "transport":"stdio","tool":"query_records","outcome":"ok","rows":3,"duration_ms":1}
#
#     It records what happened. It does not record who asked, in which
#     session, or under which JSON-RPC request id — so this line cannot be
#     joined to the client's transcript, to the notifications/message stream,
#     or to anything upstream. audit() even receives request_id as an
#     argument and drops it on the floor.
#
#   Fix — server/mcp_audit_server.py, function audit():
#
#       def audit(event: str, request_id=None, **fields) -> None:
#           record = {
#               "ts": _ts(),
#               "event": event,
#               "server": SERVER_INFO["name"],
#               "transport": "stdio",
#               "session_id": STATE["session_id"],     # which session
#               "principal": STATE["principal"],       # who is calling
#               "request_id": request_id,              # which JSON-RPC request
#           }
#           record.update(fields)
#           _audit_write(json.dumps(record, separators=(",", ":")) + "\n")
#
#     The correlation context is fixed in the record builder, not at the call
#     sites, so a new call site cannot forget it. Note that `principal` here
#     is the clientInfo.name the client asserted during initialize — it is an
#     identity claim, not an authenticated one. On a real deployment the
#     principal comes from the authorization layer (the validated token
#     subject on the HTTP transport); clientInfo is self-reported and must
#     never be treated as authentication.
#
#     Also notice what was already correct and must stay that way: audit()
#     does not consult STATE["min_level"]. A client that sets its log level
#     to "emergency" silences the logging plane and changes nothing about the
#     audit trail. If a caller can turn off the record of their own actions,
#     you do not have an audit trail.
#
#   Verify
#     $ python3 client/mcp_probe.py >/dev/null && tail -n 1 var/log/mcp/audit.jsonl \
#         | python3 -m json.tool
#     {
#         "ts": "...", "event": "tool.call", "server": "records-audit",
#         "transport": "stdio", "session_id": "9f1c2b4ad0e7",
#         "principal": "mcp-probe", "request_id": 4,
#         "tool": "query_records", "outcome": "ok", "rows": 3, "duration_ms": 1
#     }
#
# -----------------------------------------------------------------------------
# FAULT 4 — rotation orphans the relay's file descriptor
# -----------------------------------------------------------------------------
#
#   Diagnosis
#     $ bin/rotate-now.sh
#     $ ls -l /proc/$(cat var/run/relay.pid)/fd | grep mcp
#     l-wx------ 1 u u 64 Sep 17 10:09 4 -> /.../var/log/mcp/audit.jsonl.1
#     $ stat -c '%i %n' var/log/mcp/audit.jsonl*
#     2622013 var/log/mcp/audit.jsonl
#     2621998 var/log/mcp/audit.jsonl.1
#
#     The relay holds descriptor 4 open on inode 2621998. logrotate renamed
#     that inode to audit.jsonl.1 and created a fresh audit.jsonl — and never
#     told the writer. The process keeps appending, successfully, to a file
#     nobody reads; after `rotate 5` more cycles the inode is unlinked and
#     the target shows up as "(deleted)", at which point the records are
#     gone with no error anywhere. This is the classic way an audit trail
#     dies silently, and it is why CHECK 4 compares inodes instead of
#     trusting a successful write.
#
#   Fix (preferred) — etc/logrotate.d/mcp-audit.conf, add a postrotate hook
#   that signals the writer to reopen. Use the ABSOLUTE path to the pidfile:
#
#       /path/to/lab/var/log/mcp/audit.jsonl {
#           rotate 5
#           size 1k
#           missingok
#           notifempty
#           create 0640
#           sharedscripts
#           postrotate
#               /bin/kill -HUP "$(cat /path/to/lab/var/run/relay.pid)" 2>/dev/null || true
#           endscript
#       }
#
#     bin/audit-relay.py already implements the other half: SIGHUP sets a
#     flag, and the flag is consumed immediately before the next write, so
#     the descriptor is swapped without any record being written to the
#     retired one. It also stamps a {"event":"relay.reopen"} record into the
#     new file — cheap, and it makes "did the rotation land?" answerable from
#     the trail itself.
#
#   Fix (alternative) — add `copytruncate` and drop `create`:
#
#           copytruncate
#
#     logrotate copies the contents aside and truncates the original in
#     place, so the inode never changes and the writer needs no signal. It is
#     the right answer when you cannot modify or signal the producer, and the
#     wrong one for an audit trail you care about: there is a window between
#     copy and truncate in which records are lost, and no error is raised
#     when that happens. Prefer the signal; keep copytruncate for third-party
#     processes you do not control.
#     https://man7.org/linux/man-pages/man8/logrotate.8.html
#
#   Verify
#     $ bin/rotate-now.sh && sleep 1
#     $ ls -l /proc/$(cat var/run/relay.pid)/fd | grep mcp    # -> audit.jsonl, live inode
#     $ python3 client/mcp_probe.py >/dev/null && tail -n 2 var/log/mcp/audit.jsonl
#
#     If you edit bin/audit-relay.py itself, restart it:
#         bin/relay-ctl.sh restart
#
# -----------------------------------------------------------------------------
# FINAL GATE
# -----------------------------------------------------------------------------
#
#     $ "$LAB_ROOT/bin/run-checks.sh"
#       PASS  every line on the server's stdout parsed as a JSON-RPC message
#       PASS  logging capability advertised, setLevel accepted, 2 info messages received
#       PASS  tool.call records carry request_id, session_id and principal
#       PASS  records written after rotation land in the live audit trail
#     LAB PASSED  4/4 checks green.
#
#     Tear the lab down when you are done:
#         ./mcpa-4.4-break-fix.sh cleanup
#
# -----------------------------------------------------------------------------
# WHAT THIS TOPIC ACTUALLY EXAMINES
# -----------------------------------------------------------------------------
#
#   1. The transport is a contract, not a convention. On stdio, stdout
#      carries framed JSON-RPC and nothing else; stderr is where a server
#      talks to its operator. On the Streamable HTTP transport the same
#      discipline applies to the response body — an unexpected byte before
#      the SSE frame breaks the client just as thoroughly.
#
#   2. Logging is a negotiated capability with a control plane. Declare
#      `logging` in the initialize result, honour logging/setLevel, filter by
#      RFC 5424 severity, attach a `logger` name so the client can route,
#      and keep credentials and PII out of `data`.
#
#   3. Observability and auditability are different requirements with
#      different owners. The client chooses how much it wants to see; nobody
#      gets to choose how much is recorded. Build the audit path so it cannot
#      be muted by a protocol message, and so a record answers when / what /
#      who / which request without a join against something else.
#
#   4. Durability is an operational property, not an application one. Correct
#      code writing to an orphaned descriptor reports nothing but records
#      nothing. Rotation policy, signal handling and descriptor hygiene are
#      part of the audit design, and the only honest test of them is to
#      rotate and then check where the bytes actually went.
#
#   Sources
#     https://training.linuxfoundation.org/certification/model-context-protocol-associate-mcpa/
#     https://modelcontextprotocol.io/specification/2025-06-18/basic/transports
#     https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging
#     https://modelcontextprotocol.io/specification/2025-06-18/basic/utilities/progress
#     https://datatracker.ietf.org/doc/html/rfc5424
#     https://man7.org/linux/man-pages/man8/logrotate.8.html
# =============================================================================