#!/usr/bin/env bash
#
# ======================================================================
#  LPIC-1 - Exam 101-500 (version 5.0) - Topic 101.1
#  "Determine and configure hardware settings"  (exam weight: 3.13)
#
#  BREAK & FIX LAB.  RUN THIS ONLY ON A DISPOSABLE LABORATORY VM.
#  It edits /etc/modprobe.d, /etc/udev/rules.d, /etc/sysctl.d and the
#  CPU hotplug state of the running kernel.  Never run it on a machine
#  you care about.
#
#  What it does: it plants four independent, reversible faults in the
#  hardware/kernel-module layer, prints the symptom and the goal for
#  each one, and then grades your repair with --verify.
#
#  Reference material (official sources):
#    LPI 101-500 objectives .. https://www.lpi.org/our-certifications/exam-101-objectives/
#    modprobe.d(5) .......... https://man7.org/linux/man-pages/man5/modprobe.d.5.html
#    modprobe(8) ............ https://man7.org/linux/man-pages/man8/modprobe.8.html
#    udev(7) ................ https://man7.org/linux/man-pages/man7/udev.7.html
#    udevadm(8) ............. https://man7.org/linux/man-pages/man8/udevadm.8.html
#    sysfs(5) ............... https://man7.org/linux/man-pages/man5/sysfs.5.html
#    proc(5) ................ https://man7.org/linux/man-pages/man5/proc.5.html
#    kernel sysctl docs ..... https://docs.kernel.org/admin-guide/sysctl/kernel.html
#    CPU hotplug docs ....... https://docs.kernel.org/core-api/cpu_hotplug.html
#
#  Usage:
#    sudo ./101.1-break-and-fix.sh            break the system (default)
#    sudo ./101.1-break-and-fix.sh --verify   grade your repair
#    sudo ./101.1-break-and-fix.sh --undo     emergency full restore
#    sudo ./101.1-break-and-fix.sh --help
#
#  The full step-by-step solution is at the END of this file, commented.
#  Do not read it until you have tried the four faults on your own.
# ======================================================================

set -euo pipefail

LAB_ID="lpic1-101.1"
LAB_ROOT="/var/lib/lab-101-1"
STATE_FILE="$LAB_ROOT/state.env"
IMG="$LAB_ROOT/labdisk.img"
MODPROBE_CONF="/etc/modprobe.d/zz-lab-101-1.conf"
UDEV_RULE="/etc/udev/rules.d/99-lab-101-1.rules"
SYSCTL_CONF="/etc/sysctl.d/99-lab-101-1.conf"
SYMLINK_NAME="labdisk"
MARKER="lab-marker: $LAB_ID"

# Modules that are safe to sabotage: never in use on a running VM, but
# present in every mainstream kernel package.  The first one that is
# installed AND not currently loaded wins.
MOD_CANDIDATES=(dummy vcan nbd minix isofs)

if [ -t 1 ]; then
    C_R=$'\e[31m'; C_G=$'\e[32m'; C_Y=$'\e[33m'; C_B=$'\e[1m'; C_0=$'\e[0m'
else
    C_R=""; C_G=""; C_Y=""; C_B=""; C_0=""
fi

info() { printf '%s[lab]%s %s\n'   "$C_B" "$C_0" "$*"; }
warn() { printf '%s[warn]%s %s\n'  "$C_Y" "$C_0" "$*"; }
die()  { printf '%s[error]%s %s\n' "$C_R" "$C_0" "$*" >&2; exit 1; }
pass() { printf '  %sPASS%s  %s\n' "$C_G" "$C_0" "$*"; }
bad()  { printf '  %sFAIL%s  %s\n' "$C_R" "$C_0" "$*"; }
skip() { printf '  %sSKIP%s  %s\n' "$C_Y" "$C_0" "$*"; }
hr()   { printf '%s\n' "======================================================================"; }
have() { command -v "$1" >/dev/null 2>&1; }

# ----------------------------------------------------------------------
# Pre-flight
# ----------------------------------------------------------------------

require_root() {
    [ "$(id -u)" -eq 0 ] || die "this lab must run as root (sudo $0 $*)"
}

require_tools() {
    local missing=()
    local t
    for t in modprobe modinfo lsmod sysctl losetup truncate udevadm readlink; do
        have "$t" || missing+=("$t")
    done
    if [ "${#missing[@]}" -gt 0 ]; then
        die "missing required tools: ${missing[*]} (install kmod, util-linux, systemd-udev, procps-ng)"
    fi
}

confirm() {
    local answer
    if [ "${ASSUME_YES:-0}" = "1" ]; then
        return 0
    fi
    if [ ! -t 0 ]; then
        die "not running on a terminal; re-run with --yes if this really is a throwaway VM"
    fi
    hr
    printf '%s\n' "This script will DELIBERATELY BREAK the kernel-module, udev,"
    printf '%s\n' "sysctl and CPU-hotplug configuration of THIS machine."
    printf '%s\n' "Hostname: $(hostname)   Kernel: $(uname -r)"
    printf '%s\n' "Only continue on a disposable laboratory VM."
    hr
    read -r -p "Type BREAK to continue, anything else to abort: " answer
    [ "$answer" = "BREAK" ] || die "aborted by the user - nothing was changed"
}

# ----------------------------------------------------------------------
# State handling (so --verify and --undo know what was broken)
# ----------------------------------------------------------------------

save_state() {
    mkdir -p "$LAB_ROOT"
    cat > "$STATE_FILE" <<EOF
# $MARKER  - generated by the break phase, consumed by --verify / --undo
LAB_MOD="$LAB_MOD"
LAB_CPU="$LAB_CPU"
LAB_DMESG_ORIG="$LAB_DMESG_ORIG"
LAB_NPROC_ORIG="$LAB_NPROC_ORIG"
EOF
    chmod 0600 "$STATE_FILE"
}

load_state() {
    [ -f "$STATE_FILE" ] || die "no lab state in $STATE_FILE - run the break phase first"
    # shellcheck disable=SC1090
    . "$STATE_FILE"
    LAB_MOD="${LAB_MOD:-}"
    LAB_CPU="${LAB_CPU:-}"
    LAB_DMESG_ORIG="${LAB_DMESG_ORIG:-0}"
    LAB_NPROC_ORIG="${LAB_NPROC_ORIG:-1}"
}

# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------

pick_module() {
    local m
    for m in "${MOD_CANDIDATES[@]}"; do
        modinfo "$m" >/dev/null 2>&1 || continue
        if grep -q "^${m//-/_} " /proc/modules; then
            continue    # already loaded, possibly in use - do not touch it
        fi
        printf '%s\n' "$m"
        return 0
    done
    return 1
}

pick_cpu() {
    local d c
    for d in /sys/devices/system/cpu/cpu[0-9]*; do
        c="${d##*/cpu}"
        if [ "$c" = "0" ]; then continue; fi          # CPU0 is often not hot-unpluggable
        if [ ! -w "$d/online" ]; then continue; fi
        if [ "$(cat "$d/online")" != "1" ]; then continue; fi
        printf '%s\n' "$c"
        return 0
    done
    return 1
}

lab_loopdev() {
    local dev
    dev="$(losetup -O NAME -n -j "$IMG" 2>/dev/null | awk 'NF{print $1; exit}')" || true
    if [ -z "$dev" ]; then
        dev="$(losetup -a 2>/dev/null | grep -F "$IMG" | cut -d: -f1 | head -n1)" || true
    fi
    printf '%s\n' "$dev"
}

ensure_lab_disk() {
    local dev
    mkdir -p "$LAB_ROOT"
    [ -f "$IMG" ] || truncate -s 128M "$IMG"
    dev="$(lab_loopdev)"
    if [ -z "$dev" ]; then
        dev="$(losetup --find --show "$IMG")"
    fi
    printf '%s\n' "$dev"
}

# ----------------------------------------------------------------------
# The four faults
# ----------------------------------------------------------------------

break_fault_a() {
    # FAULT A - kernel module made unloadable through modprobe.d.
    # 'blacklist' stops autoloading by alias; 'install <mod> /bin/false'
    # also defeats an explicit "modprobe <mod>" typed by the admin.
    modprobe -r "$LAB_MOD" >/dev/null 2>&1 || true
    cat > "$MODPROBE_CONF" <<EOF
# $MARKER
# Site hardening policy - unsupported device drivers.
blacklist $LAB_MOD
install $LAB_MOD /bin/false
EOF
    chmod 0644 "$MODPROBE_CONF"
    info "fault A planted: module '$LAB_MOD' cannot be loaded any more"
}

break_fault_b() {
    # FAULT B - udev rule that looks right and never matches:
    #   KERNEL=="loop"                 -> the device is loop0/loop1, not "loop"
    #   ATTR{loop/backing-file}        -> the sysfs attribute is backing_file
    # Both are silent mismatches, not syntax errors, so udev logs nothing.
    cat > "$UDEV_RULE" <<EOF
# $MARKER
# Persistent name for the lab block device.
ACTION!="remove", SUBSYSTEM=="block", KERNEL=="loop", ATTR{loop/backing-file}=="$IMG", SYMLINK+="$SYMLINK_NAME"
EOF
    chmod 0644 "$UDEV_RULE"
    rm -f "/dev/$SYMLINK_NAME"
    udevadm control --reload >/dev/null 2>&1 || true
    udevadm trigger --subsystem-match=block >/dev/null 2>&1 || true
    udevadm settle --timeout=10 >/dev/null 2>&1 || true
    info "fault B planted: /dev/$SYMLINK_NAME is never created by udev"
}

break_fault_c() {
    # FAULT C - the kernel ring buffer is hidden from unprivileged users.
    cat > "$SYSCTL_CONF" <<EOF
# $MARKER
kernel.dmesg_restrict = 1
EOF
    chmod 0644 "$SYSCTL_CONF"
    sysctl -q -w kernel.dmesg_restrict=1
    info "fault C planted: dmesg is now root-only"
}

break_fault_d() {
    # FAULT D - one logical CPU taken offline through sysfs.
    if [ -z "$LAB_CPU" ]; then
        warn "fault D skipped: no hot-pluggable CPU besides cpu0 on this VM"
        return 0
    fi
    printf '0' > "/sys/devices/system/cpu/cpu$LAB_CPU/online"
    info "fault D planted: cpu$LAB_CPU is offline (nproc now $(nproc))"
}

# ----------------------------------------------------------------------
# Break phase
# ----------------------------------------------------------------------

do_break() {
    require_root
    require_tools

    if [ -f "$STATE_FILE" ]; then
        warn "a lab is already planted; re-running is idempotent and will re-break it"
    fi

    LAB_MOD="$(pick_module)" || die "no safe spare module found (tried: ${MOD_CANDIDATES[*]})"
    LAB_CPU="$(pick_cpu)" || LAB_CPU=""
    LAB_DMESG_ORIG="$(sysctl -n kernel.dmesg_restrict 2>/dev/null || echo 0)"
    LAB_NPROC_ORIG="$(nproc)"

    confirm

    local dev
    dev="$(ensure_lab_disk)"
    info "lab block device: $dev  (backing file $IMG)"

    save_state
    break_fault_a
    break_fault_b
    break_fault_c
    break_fault_d

    briefing "$dev"
}

briefing() {
    local dev="$1"
    echo
    hr
    printf '%s\n' " LPIC-1 101.1 - BREAK & FIX - four faults are now active"
    hr
    cat <<EOF

 FAULT A - kernel module (objective keywords: lsmod, modprobe, modinfo, /proc/modules)

   SYMPTOM
     \$ sudo modprobe $LAB_MOD
     modprobe: ERROR: Error running install command '/bin/false' for module $LAB_MOD: retcode 1
     modprobe: ERROR: could not insert '$LAB_MOD': Invalid argument
     \$ lsmod | grep $LAB_MOD        -> no output
     The module file is installed on disk (modinfo finds it), yet it refuses to load.

   YOUR GOAL
     'sudo modprobe $LAB_MOD' succeeds, the module shows up in lsmod, and
     /sys/module/$LAB_MOD/ exists.  No leftover blacklist/install override for it.

   TOOLS TO EXPLORE
     modinfo -n $LAB_MOD | modprobe -n -v $LAB_MOD | modprobe --showconfig
     ls -l /etc/modprobe.d/ /lib/modprobe.d/ | grep -R $LAB_MOD /etc/modprobe.d

 FAULT B - udev / device naming (objective keywords: udev, sysfs, /dev, udevadm)

   SYMPTOM
     The lab disk is attached at $dev and is perfectly usable, but the
     persistent name the lab tooling expects is missing:
     \$ ls -l /dev/$SYMLINK_NAME
     ls: cannot access '/dev/$SYMLINK_NAME': No such file or directory
     A rule for it does exist under /etc/udev/rules.d/ and udev logs no error.

   YOUR GOAL
     udev itself creates /dev/$SYMLINK_NAME pointing at the loop device backed by
     $IMG.  The grader deletes the symlink, reloads and re-triggers udev, so a
     hand-made 'ln -s' will NOT pass.

   TOOLS TO EXPLORE
     udevadm info --query=all --name=$dev
     udevadm info --attribute-walk --name=$dev
     udevadm test /sys/block/${dev##*/}
     udevadm control --reload ; udevadm trigger ; udevadm settle
     cat /sys/block/${dev##*/}/loop/backing_file

 FAULT C - /proc tunable (objective keywords: dmesg, /proc, sysctl)

   SYMPTOM
     As a normal (non-root) user:
     \$ dmesg
     dmesg: read kernel buffer failed: Operation not permitted
     Root still reads it fine, so "it works for me" hides the problem.

   YOUR GOAL
     An unprivileged user can read the kernel ring buffer again, and the fix
     survives a reboot (runtime value 0 AND no config file setting it back to 1).

   TOOLS TO EXPLORE
     sysctl -a | grep dmesg ; cat /proc/sys/kernel/dmesg_restrict
     grep -R dmesg_restrict /etc/sysctl.conf /etc/sysctl.d /usr/lib/sysctl.d
     sysctl --system ; man 5 proc

 FAULT D - CPU hotplug via sysfs (objective keywords: /sys, lscpu, /proc/cpuinfo)

   SYMPTOM
     nproc reports $(nproc) CPU(s) instead of $LAB_NPROC_ORIG; lscpu shows an
     "Off-line CPU(s) list"; /proc/cpuinfo is missing that processor, while the
     hypervisor still exposes it.

   YOUR GOAL
     Every logical CPU is back online (nproc == $LAB_NPROC_ORIG) WITHOUT rebooting.

   TOOLS TO EXPLORE
     lscpu ; grep -c ^processor /proc/cpuinfo
     ls /sys/devices/system/cpu/ ; cat /sys/devices/system/cpu/online
     cat /sys/devices/system/cpu/cpu*/online ; dmesg -T | tail

EOF
    hr
    printf '%s\n' " Grade your repair:   sudo $0 --verify"
    printf '%s\n' " Emergency restore:   sudo $0 --undo"
    hr
}

# ----------------------------------------------------------------------
# Verification
# ----------------------------------------------------------------------

verify_a() {
    local cfg
    cfg="$(modprobe --showconfig 2>/dev/null || modprobe -c 2>/dev/null || true)"
    if printf '%s\n' "$cfg" | grep -Eq "^[[:space:]]*(blacklist|install)[[:space:]]+$LAB_MOD([[:space:]]|$)"; then
        return 1
    fi
    [ -d "/sys/module/${LAB_MOD//-/_}" ] || return 1
    grep -q "^${LAB_MOD//-/_} " /proc/modules || return 1
    return 0
}

verify_b() {
    local dev syspath target
    dev="$(lab_loopdev)"
    if [ -z "$dev" ]; then
        dev="$(losetup --find --show "$IMG")"   # reattach after a reboot
    fi
    syspath="/sys/block/${dev##*/}"
    rm -f "/dev/$SYMLINK_NAME"
    udevadm control --reload >/dev/null 2>&1 || true
    udevadm trigger --action=change "$syspath" >/dev/null 2>&1 || true
    udevadm settle --timeout=10 >/dev/null 2>&1 || true
    [ -L "/dev/$SYMLINK_NAME" ] || return 1
    target="$(readlink -f "/dev/$SYMLINK_NAME")"
    [ "$target" = "$(readlink -f "$dev")" ] || return 1
    return 0
}

verify_c() {
    [ "$(sysctl -n kernel.dmesg_restrict 2>/dev/null || echo 1)" = "0" ] || return 1
    # the fix must also be persistent: no config file may set it back to 1
    if grep -RIsq --include='*.conf' -E '^[[:space:]]*kernel\.dmesg_restrict[[:space:]]*=[[:space:]]*1' \
        /etc/sysctl.d /usr/lib/sysctl.d /run/sysctl.d 2>/dev/null; then
        return 1
    fi
    if grep -Isq -E '^[[:space:]]*kernel\.dmesg_restrict[[:space:]]*=[[:space:]]*1' /etc/sysctl.conf 2>/dev/null; then
        return 1
    fi
    return 0
}

verify_d() {
    [ -n "$LAB_CPU" ] || return 2
    [ "$(cat "/sys/devices/system/cpu/cpu$LAB_CPU/online" 2>/dev/null || echo 0)" = "1" ] || return 1
    [ "$(nproc)" = "$LAB_NPROC_ORIG" ] || return 1
    return 0
}

do_verify() {
    require_root
    require_tools
    load_state

    local rc=0 r
    hr
    printf '%s\n' " LPIC-1 101.1 - grading"
    hr

    if verify_a; then pass "A  module '$LAB_MOD' loads and is present in lsmod"
    else              bad  "A  module '$LAB_MOD' still blocked or not loaded"; rc=1; fi

    if verify_b; then pass "B  udev recreates /dev/$SYMLINK_NAME for the lab disk"
    else              bad  "B  udev does not create /dev/$SYMLINK_NAME"; rc=1; fi

    if verify_c; then pass "C  kernel.dmesg_restrict is 0 and stays 0 after reboot"
    else              bad  "C  dmesg is still restricted (runtime value or config file)"; rc=1; fi

    set +e; verify_d; r=$?; set -e
    case "$r" in
        0) pass "D  all $LAB_NPROC_ORIG logical CPUs are online" ;;
        2) skip "D  no hot-pluggable CPU on this VM - fault not planted" ;;
        *) bad  "D  cpu$LAB_CPU is still offline (nproc=$(nproc), expected $LAB_NPROC_ORIG)"; rc=1 ;;
    esac

    hr
    if [ "$rc" -eq 0 ]; then
        printf '%s\n' "${C_G}All faults repaired.${C_0}  Run 'sudo $0 --undo' to remove the lab leftovers."
    else
        printf '%s\n' "${C_Y}Not there yet.${C_0}  Re-read the symptoms and keep digging."
    fi
    return "$rc"
}

# ----------------------------------------------------------------------
# Emergency restore
# ----------------------------------------------------------------------

do_undo() {
    require_root
    load_state

    rm -f "$MODPROBE_CONF" "$UDEV_RULE" "$SYSCTL_CONF" "/dev/$SYMLINK_NAME"

    sysctl -q -w "kernel.dmesg_restrict=$LAB_DMESG_ORIG" 2>/dev/null || true

    if [ -n "$LAB_CPU" ] && [ -w "/sys/devices/system/cpu/cpu$LAB_CPU/online" ]; then
        printf '1' > "/sys/devices/system/cpu/cpu$LAB_CPU/online" || true
    fi

    udevadm control --reload >/dev/null 2>&1 || true
    udevadm trigger --subsystem-match=block >/dev/null 2>&1 || true
    udevadm settle --timeout=10 >/dev/null 2>&1 || true

    local dev
    dev="$(lab_loopdev)"
    [ -n "$dev" ] && losetup -d "$dev" >/dev/null 2>&1 || true

    rm -rf "$LAB_ROOT"
    info "lab removed: config files deleted, sysctl restored, CPUs online, loop device detached"
    info "the module '$LAB_MOD' may still be loaded; 'modprobe -r $LAB_MOD' if you want it gone"
}

usage() {
    cat <<EOF
LPIC-1 101.1 break & fix lab - disposable VMs only.

  sudo $0 [--break]   plant the four faults (default)
  sudo $0 --verify    grade your repair
  sudo $0 --undo      restore everything and delete the lab
  sudo $0 --yes       non-interactive break (skips the BREAK prompt)
  sudo $0 --help      this text
EOF
}

main() {
    local action="break"
    ASSUME_YES=0
    while [ $# -gt 0 ]; do
        case "$1" in
            --break)          action="break" ;;
            --verify|--check) action="verify" ;;
            --undo|--restore) action="undo" ;;
            --yes|-y)         ASSUME_YES=1 ;;
            --help|-h)        usage; return 0 ;;
            *)                die "unknown option: $1 (try --help)" ;;
        esac
        shift
    done
    case "$action" in
        break)  do_break ;;
        verify) do_verify ;;
        undo)   do_undo ;;
    esac
}

main "$@"

# ======================================================================
#  SOLUTION - do not read before you have worked the four faults.
# ======================================================================
#
#  General method for this objective: the kernel exposes hardware state in
#  three places, and every fault below lives in one of them.
#    /proc  - process and kernel interface (/proc/modules, /proc/cpuinfo,
#             /proc/interrupts, /proc/iomem, /proc/sys/*)
#    /sys   - sysfs, the device model (/sys/module, /sys/block,
#             /sys/devices/system/cpu, /sys/class)
#    /dev   - device nodes, populated by devtmpfs and named by udev
#  Persistent configuration for the first two lives in /etc/modprobe.d and
#  /etc/sysctl.d; for the third, in /etc/udev/rules.d.
#
# ----------------------------------------------------------------------
#  FAULT A - the module that refuses to load
# ----------------------------------------------------------------------
#
#  1) Confirm the module exists on disk, so this is configuration and not a
#     missing kernel package:
#
#       # modinfo -n dummy
#       /lib/modules/6.x.y/kernel/drivers/net/dummy.ko.xz
#
#  2) Ask modprobe what it WOULD do, without doing it.  This is the single
#     most useful command of the objective:
#
#       # modprobe -n -v dummy
#       install /bin/false
#
#     A normal module would print "insmod /lib/modules/.../dummy.ko.xz".
#     "install /bin/false" means some configuration file replaced the load
#     action with a command that always fails.
#
#  3) Dump the effective configuration and find the offending file:
#
#       # modprobe --showconfig | grep -E '(blacklist|install) dummy'
#       blacklist dummy
#       install dummy /bin/false
#
#       # grep -R dummy /etc/modprobe.d /lib/modprobe.d /usr/lib/modprobe.d 2>/dev/null
#       /etc/modprobe.d/zz-lab-101-1.conf:blacklist dummy
#       /etc/modprobe.d/zz-lab-101-1.conf:install dummy /bin/false
#
#     Files are read in lexical order, which is why "zz-" wins over the
#     distribution defaults.  See modprobe.d(5).
#
#  4) Remove the override (or comment out the two lines) and load the module:
#
#       # rm -f /etc/modprobe.d/zz-lab-101-1.conf
#       # modprobe -n -v dummy
#       insmod /lib/modules/6.x.y/kernel/drivers/net/dummy.ko.xz
#       # modprobe dummy
#
#  5) Prove it, from both interfaces:
#
#       # lsmod | grep dummy
#       dummy                  16384  0
#       # grep ^dummy /proc/modules
#       dummy 16384 0 - Live 0xffffffffc0a12000
#       # ls /sys/module/dummy/
#       coresize  drivers  holders  initsize  initstate  notes  refcnt  sections  srcversion  taint  uevent
#
#     Note: "blacklist" alone only stops AUTOloading by alias; an explicit
#     "modprobe dummy" would still have worked.  It was the "install" line
#     that blocked the manual load.  Recognising which of the two you are
#     facing is exactly what the exam asks for.
#
# ----------------------------------------------------------------------
#  FAULT B - the udev symlink that is never created
# ----------------------------------------------------------------------
#
#  1) Identify the real device and check that the kernel side is healthy:
#
#       # losetup -a
#       /dev/loop0: [64768]:1234 (/var/lib/lab-101-1/labdisk.img)
#       # ls -l /dev/loop0 /dev/labdisk
#       brw-rw---- 1 root disk 7, 0 ... /dev/loop0
#       ls: cannot access '/dev/labdisk': No such file or directory
#
#     The node exists (devtmpfs created it); only the udev-managed NAME is
#     missing.  So the fault is in a rule, not in the driver.
#
#  2) Ask udev to replay the rules for that device.  udevadm test is the
#     debugger for this objective:
#
#       # udevadm test /sys/block/loop0 2>&1 | grep -i -E 'labdisk|symlink'
#       (no LINK 'labdisk' line at all)
#
#     The rule is parsed without a syntax error, so it is matching wrongly,
#     not failing to load.
#
#  3) Read the rule and compare each key against reality:
#
#       # cat /etc/udev/rules.d/99-lab-101-1.rules
#       ACTION!="remove", SUBSYSTEM=="block", KERNEL=="loop", \
#         ATTR{loop/backing-file}=="/var/lib/lab-101-1/labdisk.img", SYMLINK+="labdisk"
#
#       # udevadm info --query=all --name=/dev/loop0
#       P: /devices/virtual/block/loop0
#       N: loop0
#       E: SUBSYSTEM=block
#       E: DEVTYPE=disk
#
#       # udevadm info --attribute-walk --name=/dev/loop0 | grep -i backing
#       ATTR{loop/backing_file}="/var/lib/lab-101-1/labdisk.img"
#
#     Two silent mismatches:
#       - KERNEL=="loop"  never matches: the kernel name is "loop0".
#         Use a glob: KERNEL=="loop*".
#       - ATTR{loop/backing-file} does not exist; the sysfs attribute is
#         loop/backing_file (underscore).  A non-existent attribute simply
#         never matches, which is why nothing is logged.
#
#  4) Write the correct rule:
#
#       # cat > /etc/udev/rules.d/99-lab-101-1.rules <<'RULE'
#       ACTION!="remove", SUBSYSTEM=="block", KERNEL=="loop*", \
#         ATTR{loop/backing_file}=="/var/lib/lab-101-1/labdisk.img", SYMLINK+="labdisk"
#       RULE
#
#     (Keep it on one physical line, or end continued lines with a backslash.)
#
#  5) Reload the rule set and replay the event.  Editing a rule file does
#     nothing by itself - this two-step is the point of the exercise:
#
#       # udevadm control --reload
#       # udevadm trigger --action=change /sys/block/loop0
#       # udevadm settle
#       # ls -l /dev/labdisk
#       lrwxrwxrwx 1 root root 5 ... /dev/labdisk -> loop0
#
#  6) Cross-check with the persistent names udev builds by default:
#
#       # ls -l /dev/disk/by-path/ /dev/disk/by-id/ 2>/dev/null | head
#       # udevadm monitor --udev --subsystem-match=block     (watch live events)
#
# ----------------------------------------------------------------------
#  FAULT C - dmesg denied to unprivileged users
# ----------------------------------------------------------------------
#
#  1) Reproduce as a normal user, then read the tunable:
#
#       $ dmesg
#       dmesg: read kernel buffer failed: Operation not permitted
#       # cat /proc/sys/kernel/dmesg_restrict
#       1
#       # sysctl -n kernel.dmesg_restrict
#       1
#
#     kernel.dmesg_restrict=1 means only CAP_SYSLOG (in practice root) may
#     read the ring buffer.  See the kernel sysctl documentation.
#
#  2) Fix it at runtime AND persistently.  Doing only one of the two is the
#     classic half-fix:
#
#       # sysctl -w kernel.dmesg_restrict=0        (runtime, lost on reboot)
#       # grep -R dmesg_restrict /etc/sysctl.conf /etc/sysctl.d /usr/lib/sysctl.d
#       /etc/sysctl.d/99-lab-101-1.conf:kernel.dmesg_restrict = 1
#       # rm -f /etc/sysctl.d/99-lab-101-1.conf
#       # sysctl --system | grep dmesg
#
#     If your site policy needs an explicit value, write
#     "kernel.dmesg_restrict = 0" into /etc/sysctl.d/99-local.conf instead of
#     deleting the file - the grader accepts either, as long as nothing sets 1.
#
#  3) Verify from the unprivileged account:
#
#       $ dmesg -T | tail -n 5
#       [Tue Aug 25 10:12:03 2026] loop0: detected capacity change from 0 to 262144
#
#     Note how dmesg is the primary evidence channel for hardware faults:
#     driver probe failures, missing firmware, IRQ conflicts and USB resets
#     all land here first.
#
# ----------------------------------------------------------------------
#  FAULT D - the missing CPU
# ----------------------------------------------------------------------
#
#  1) Compare what the kernel presents with what the VM really has:
#
#       # nproc
#       1
#       # lscpu | grep -E 'CPU\(s\)|On-line|Off-line'
#       CPU(s):                  2
#       On-line CPU(s) list:     0
#       Off-line CPU(s) list:    1
#       # grep -c ^processor /proc/cpuinfo
#       1
#
#     "CPU(s): 2" with "Off-line CPU(s) list: 1" proves the hardware is
#     present and the kernel deliberately parked it - not a hypervisor issue.
#
#  2) Confirm in sysfs, which is where the state actually lives:
#
#       # cat /sys/devices/system/cpu/online
#       0
#       # cat /sys/devices/system/cpu/present
#       0-1
#       # cat /sys/devices/system/cpu/cpu1/online
#       0
#
#  3) Bring it back online - no reboot needed:
#
#       # echo 1 > /sys/devices/system/cpu/cpu1/online
#       # nproc
#       2
#       # lscpu | grep -E 'On-line|Off-line'
#       On-line CPU(s) list:     0,1
#       # dmesg -T | tail -n 3
#       [...] smpboot: Booting Node 0 Processor 1 APIC 0x1
#
#     A loop for a machine with many parked CPUs:
#       # for c in /sys/devices/system/cpu/cpu[0-9]*/online; do echo 1 > "$c"; done
#
#     Remember that this state is volatile: it resets on reboot unless a boot
#     parameter (maxcpus=, nosmp, possible_cpus=) or a tuning service sets it.
#     If a CPU keeps disappearing after every boot, check /proc/cmdline:
#       # cat /proc/cmdline
#
# ----------------------------------------------------------------------
#  CLOSING THE LAB
# ----------------------------------------------------------------------
#
#       # sudo ./101.1-break-and-fix.sh --verify     grade the four faults
#       # sudo ./101.1-break-and-fix.sh --undo       delete every leftover
#
#  Adjacent commands from the same objective, worth running once on the
#  repaired system so the output is familiar on exam day:
#       lspci -nnk        PCI devices with the driver bound to each one
#       lsusb -t          USB topology by bus and hub
#       lsmod / modinfo   loaded modules and their parameters
#       cat /proc/interrupts /proc/iomem /proc/ioports /proc/dma
#       ls /sys/class/    the device model grouped by class
#       udevadm monitor   kernel and udev events, live
# ======================================================================