#!/usr/bin/env bash
#
# =============================================================================
#  LPIC-1 v5.0 (exams 101-500 / 102-500) - Topic 104.1
#  "Create partitions and filesystems"  (exam weight: 3.12)
#
#  BREAK & FIX LABORATORY
#
#  This script builds a self-contained, file-backed block device, lays a GPT
#  label on it, creates three filesystems (ext4 + vfat + swap), fills the ext4
#  one with data the student must NOT lose, and then breaks the disk in three
#  layered, realistic ways. The student's job is to bring the disk back
#  without recreating the filesystems and without losing a single byte.
#
#  SAFETY MODEL - read this before running anything:
#    * Every destructive operation targets ONLY a loop device whose backing
#      file is the lab image created by this script. Three independent guards
#      are enforced before each dd/sgdisk/mkfs call:
#         1. the device name must match ^/dev/loop[0-9]+(p[1-9])?$
#         2. the device must be a block device
#         3. `losetup -O BACK-FILE` must report our image path
#      A physical disk can therefore never be reached, even by accident.
#    * The real /etc/fstab is never touched.
#    * Still: run this on a DISPOSABLE lab VM. That is the habit the exam,
#      and production, expects you to have.
#
#  USAGE
#    sudo ./104.1-break-and-fix.sh break      # build the lab and break it
#    sudo ./104.1-break-and-fix.sh check      # grade your repair
#    sudo ./104.1-break-and-fix.sh status     # what the lab looks like now
#    sudo ./104.1-break-and-fix.sh reattach   # after a VM reboot
#    sudo ./104.1-break-and-fix.sh cleanup    # remove every trace
#
#  REFERENCES (official)
#    LPI exam 101 objectives ... https://www.lpi.org/our-certifications/exam-101-objectives/
#    GPT on-disk layout ....... https://uefi.org/specifications
#    gdisk / sgdisk ........... https://www.rodsbooks.com/gdisk/
#    ext4 superblock layout ... https://www.kernel.org/doc/html/latest/filesystems/ext4/globals.html
#    e2fsck(8) ................ https://man7.org/linux/man-pages/man8/e2fsck.8.html
#    mke2fs(8) ................ https://man7.org/linux/man-pages/man8/mke2fs.8.html
#    mkswap(8) ................ https://man7.org/linux/man-pages/man8/mkswap.8.html
#    losetup(8) ............... https://man7.org/linux/man-pages/man8/losetup.8.html
#    partx(8) ................. https://man7.org/linux/man-pages/man8/partx.8.html
# =============================================================================

set -Eeuo pipefail

LAB_DIR="${LPIC_LAB_DIR:-/var/tmp/lpic1-104.1-lab}"
IMG="$LAB_DIR/disk.img"
STATE="$LAB_DIR/lab.state"
MNT="$LAB_DIR/mnt"
IMG_SIZE_MB=1024          # 1 GiB backing file, fully allocated (no holes)
P1_SIZE="600M"            # ext4  - must stay >= 512 MiB so mke2fs picks 4 KiB blocks
P2_SIZE="128M"            # vfat
P3_SIZE="128M"            # swap

LOOP=""
FS2_TYPE="vfat"
SWAP_ACTIVATABLE="yes"
DATA_SHA=""

# ---------------------------------------------------------------- primitives

log()  { printf '[*] %s\n' "$*"; }
ok()   { printf '[OK]   %s\n' "$*"; }
bad()  { printf '[FAIL] %s\n' "$*"; }
warn() { printf '[!] %s\n' "$*" >&2; }
die()  { printf '[X] %s\n' "$*" >&2; exit 1; }

trap 'die "aborted at line $LINENO (command: ${BASH_COMMAND})"' ERR

need_root() {
    [[ ${EUID:-$(id -u)} -eq 0 ]] || die "run as root: sudo $0 $*"
}

need_cmd() {
    local missing=()
    local c
    for c in "$@"; do
        command -v "$c" >/dev/null 2>&1 || missing+=("$c")
    done
    if ((${#missing[@]})); then
        die "missing required tools: ${missing[*]}
     Debian/Ubuntu: apt install util-linux gdisk e2fsprogs dosfstools parted
     RHEL/Fedora  : dnf install util-linux gdisk e2fsprogs dosfstools parted"
    fi
}

# Guard 1+2+3: refuse anything that is not our own loop device / partition.
assert_lab_device() {
    local dev="$1" base backing
    [[ "$dev" =~ ^/dev/loop[0-9]+(p[1-9])?$ ]] \
        || die "refusing to touch a device that is not a loop device: $dev"
    [[ -b "$dev" ]] || die "not a block device: $dev"
    base="${dev%%p[0-9]}"
    backing="$(losetup -n -O BACK-FILE "$base" 2>/dev/null || true)"
    [[ "$backing" == "$IMG" ]] \
        || die "loop device $base is not backed by $IMG (backing file: ${backing:-none}) - refusing"
}

save_state() {
    cat >"$STATE" <<EOF
# lab state - generated by $0, do not edit
LOOP="$LOOP"
FS2_TYPE="$FS2_TYPE"
SWAP_ACTIVATABLE="$SWAP_ACTIVATABLE"
DATA_SHA="$DATA_SHA"
EOF
}

load_state() {
    [[ -f "$STATE" ]] || die "no lab found in $LAB_DIR - run: sudo $0 break"
    # shellcheck disable=SC1090
    source "$STATE"
    [[ -n "${LOOP:-}" ]] || die "corrupt state file: $STATE"
}

# Re-attach the image if the loop device went away (reboot, manual losetup -d).
ensure_loop() {
    local current
    current="$(losetup -n -O NAME -j "$IMG" 2>/dev/null | head -n1 || true)"
    if [[ -z "$current" ]]; then
        current="$(losetup --find --show --partscan "$IMG")"
        log "image re-attached as $current"
    fi
    LOOP="$current"
    assert_lab_device "$LOOP"
    save_state
}

rescan_partitions() {
    udevadm settle >/dev/null 2>&1 || true
    partx -u "$LOOP" >/dev/null 2>&1 || partx -a "$LOOP" >/dev/null 2>&1 || true
    blockdev --rereadpt "$LOOP" >/dev/null 2>&1 || true
    udevadm settle >/dev/null 2>&1 || true
}

wait_for_node() {
    local node="$1" i
    for i in $(seq 1 40); do
        [[ -b "$node" ]] && return 0
        sleep 0.1
    done
    return 1
}

release_loop() {
    local dev="$1"
    awk -v d="^$dev" '$1 ~ d { print $1 }' /proc/swaps 2>/dev/null \
        | while read -r s; do swapoff "$s" 2>/dev/null || true; done
    awk -v d="^$dev" '$1 ~ d { print $2 }' /proc/mounts 2>/dev/null \
        | while read -r m; do umount "$m" 2>/dev/null || true; done
    mountpoint -q "$MNT" && umount "$MNT" || true
}

# ------------------------------------------------------------------- payload

write_payload() {
    local target="$1" i
    mkdir -p "$target/payroll" "$target/etc-backup"
    for i in $(seq -w 1 24); do
        printf 'record=%s;employee=EMP-%s;net=%s.00;currency=EUR\n' \
               "$i" "$i" "$((1800 + 10#$i * 37))" >"$target/payroll/slip-$i.csv"
    done
    printf 'THIS FILE MUST SURVIVE THE REPAIR - LPIC-1 104.1 canary\n' \
        >"$target/payroll/CANARY.txt"
    cp /etc/services "$target/etc-backup/services.copy" 2>/dev/null || \
        printf 'fallback payload\n' >"$target/etc-backup/services.copy"
    sync
}

payload_sha() {
    local target="$1"
    find "$target/payroll" "$target/etc-backup" -type f -print0 \
        | LC_ALL=C sort -z \
        | xargs -0 sha256sum \
        | sha256sum \
        | awk '{print $1}'
}

# --------------------------------------------------------------------- setup

do_setup() {
    need_cmd losetup sgdisk gdisk mkfs.ext4 mkswap dd partx blkid sha256sum awk find

    if command -v mkfs.vfat >/dev/null 2>&1; then
        FS2_TYPE="vfat"
    else
        warn "dosfstools not installed - partition 2 will be ext2 instead of vfat"
        FS2_TYPE="ext2"
    fi

    [[ -e "$IMG" ]] && die "a lab image already exists at $IMG - run: sudo $0 cleanup"

    mkdir -p "$LAB_DIR" "$MNT"
    chmod 700 "$LAB_DIR"

    log "creating a ${IMG_SIZE_MB} MiB fully-allocated backing file (no sparse holes - swapon rejects those)"
    dd if=/dev/zero of="$IMG" bs=1M count="$IMG_SIZE_MB" status=none

    LOOP="$(losetup --find --show --partscan "$IMG")"
    assert_lab_device "$LOOP"
    log "backing file attached to $LOOP"

    log "writing a GPT label with three partitions"
    sgdisk --zap-all "$LOOP" >/dev/null
    sgdisk -n "1:2048:+$P1_SIZE" -t 1:8300 -c 1:lpic-data \
           -n "2:0:+$P2_SIZE"    -t 2:0700 -c 2:lpic-vfat \
           -n "3:0:+$P3_SIZE"    -t 3:8200 -c 3:lpic-swap \
           "$LOOP" >/dev/null
    rescan_partitions
    wait_for_node "${LOOP}p3" || die "kernel did not expose the partitions - is loop partscan enabled?"

    assert_lab_device "${LOOP}p1"
    assert_lab_device "${LOOP}p2"
    assert_lab_device "${LOOP}p3"

    log "mkfs.ext4 on ${LOOP}p1 (defaults: 4 KiB blocks, sparse_super backups)"
    mkfs.ext4 -q -L LPICDATA "${LOOP}p1"

    log "mkfs.$FS2_TYPE on ${LOOP}p2"
    if [[ "$FS2_TYPE" == "vfat" ]]; then
        mkfs.vfat -n LPICVFAT "${LOOP}p2" >/dev/null
    else
        mkfs.ext2 -q -L LPICVFAT "${LOOP}p2"
    fi

    log "mkswap on ${LOOP}p3"
    mkswap -L LPICSWAP "${LOOP}p3" >/dev/null

    log "planting the payload the student must not lose"
    mount "${LOOP}p1" "$MNT"
    write_payload "$MNT"
    DATA_SHA="$(payload_sha "$MNT")"
    umount "$MNT"

    mount "${LOOP}p2" "$MNT"
    printf 'firmware image placeholder - vfat control partition\n' >"$MNT/FIRMWARE.BIN"
    sync
    umount "$MNT"

    # Probe once whether this kernel/filesystem combination lets us swap onto a
    # loop device. On some copy-on-write backing filesystems it will not, and
    # that must not turn into a false failure when grading.
    if swapon "${LOOP}p3" >/dev/null 2>&1; then
        swapoff "${LOOP}p3"
        SWAP_ACTIVATABLE="yes"
    else
        SWAP_ACTIVATABLE="no"
        warn "this host refuses swapon on a loop device; grading will accept a valid swap signature instead"
    fi

    e2fsck -fy "${LOOP}p1" >/dev/null 2>&1 || true
    save_state
    ok "lab built: $LOOP (p1=ext4 ${P1_SIZE}, p2=$FS2_TYPE ${P2_SIZE}, p3=swap ${P3_SIZE})"
}

# --------------------------------------------------------------------- break

do_break() {
    release_loop "$LOOP"

    # --- Damage 3 (applied first: it needs the partition nodes to still exist)
    # Erase the swap signature. mkswap writes a 4 KiB header at the start of
    # the device; without it swapon(8) has nothing to identify.
    assert_lab_device "${LOOP}p3"
    log "damage: erasing the swap area signature on ${LOOP}p3"
    dd if=/dev/zero of="${LOOP}p3" bs=4096 count=2 conv=notrunc status=none

    # --- Damage 2
    # Erase the ext4 primary superblock (byte offset 1024, 1 KiB long) plus the
    # first block of group descriptors that follows it. The filesystem data and
    # the backup superblocks are untouched, so this is fully recoverable - but
    # only if you know where the backups live.
    assert_lab_device "${LOOP}p1"
    log "damage: erasing the ext4 primary superblock + first GDT block on ${LOOP}p1"
    dd if=/dev/zero of="${LOOP}p1" bs=1024 seek=1 count=8 conv=notrunc status=none

    # --- Damage 1 (applied last: it makes the partition nodes disappear)
    # Erase LBA 0..33: protective MBR, primary GPT header and the whole primary
    # partition entry array. The backup GPT in the last sectors of the disk is
    # deliberately left intact.
    assert_lab_device "$LOOP"
    log "damage: erasing the protective MBR and the primary GPT (LBA 0-33) on $LOOP"
    dd if=/dev/zero of="$LOOP" bs=512 count=34 conv=notrunc status=none
    sync

    partx -d --nr 1-3 "$LOOP" >/dev/null 2>&1 || true
    blockdev --rereadpt "$LOOP" >/dev/null 2>&1 || true
    udevadm settle >/dev/null 2>&1 || true

    print_briefing
}

print_briefing() {
    local swapnote
    if [[ "$SWAP_ACTIVATABLE" == "yes" ]]; then
        swapnote="swapon must succeed and the area must appear in /proc/swaps."
    else
        swapnote="this host will not swap onto a loop device, so a valid swap signature (blkid TYPE=\"swap\") is enough."
    fi

    cat <<EOF

===============================================================================
 LPIC-1 104.1 - BREAK & FIX - the disk is now broken. Read carefully.
===============================================================================

 The device under repair is:   $LOOP
 (a loop device backed by $IMG - nothing else on this machine is affected)

 WHAT THE DISK LOOKED LIKE BEFORE (this is your target state):

   Label type : GPT
   $LOOP p1   ${P1_SIZE}   type code 8300 "lpic-data"   ext4,  label LPICDATA
   $LOOP p2   ${P2_SIZE}   type code 0700 "lpic-vfat"   $FS2_TYPE, label LPICVFAT
   $LOOP p3   ${P3_SIZE}   type code 8200 "lpic-swap"   swap,  label LPICSWAP

   Partition 1 holds /payroll (25 files) and /etc-backup (1 file).
   Those files are the point of the exercise: they must come back byte for
   byte. Reformatting is not a repair - it is a data loss incident with a
   green exit status.

-------------------------------------------------------------------------------
 SYMPTOM 1 - the disk looks empty
-------------------------------------------------------------------------------
   \$ lsblk $LOOP
        shows the whole device with NO partitions under it
   \$ ls ${LOOP}p*
        ls: cannot access '${LOOP}p*': No such file or directory
   \$ fdisk -l $LOOP
        reports no recognised partition table (or an empty one)

   The partition table header at the very start of the disk was destroyed.
   The filesystems themselves were not moved and were not erased - the kernel
   simply no longer knows where they begin and end. GPT was designed for
   exactly this accident; find what GPT keeps for that purpose and use it.

-------------------------------------------------------------------------------
 SYMPTOM 2 - partition 1 will not mount even once the partitions are back
-------------------------------------------------------------------------------
   \$ mount ${LOOP}p1 /mnt
        mount: /mnt: can't read superblock on ${LOOP}p1.
   \$ dmesg | tail
        EXT4-fs (loopXp1): unable to read superblock
   \$ blkid ${LOOP}p1
        prints nothing at all

   The primary superblock and the first block-group descriptor block are gone.
   ext2/3/4 does not keep exactly one copy of that metadata. Find the copies,
   then tell the checker which copy to use.
   You may NOT run mkfs on this partition. Losing the payload = exercise failed.

-------------------------------------------------------------------------------
 SYMPTOM 3 - the swap area no longer exists
-------------------------------------------------------------------------------
   \$ swapon ${LOOP}p3
        swapon: ${LOOP}p3: read swap header failed
   \$ blkid ${LOOP}p3
        prints nothing

   Only the header was wiped. Nothing on a swap area is worth preserving, so
   here - unlike partition 1 - rebuilding the structure IS the correct answer.
   $swapnote

-------------------------------------------------------------------------------
 YOUR GOAL
-------------------------------------------------------------------------------
   1. Three partitions visible again, at their original offsets, with their
      original GPT type codes and names.
   2. ${LOOP}p1 mounts read-write, fsck reports it clean, and every payload
      file is intact (a SHA-256 of the whole payload is compared).
   3. ${LOOP}p2 still mounts and still contains FIRMWARE.BIN (this partition
      was never damaged - it is your proof that the table was restored at the
      right offsets and not merely re-created by guesswork).
   4. ${LOOP}p3 is a usable swap area again.

   Tools that are in scope for objective 104.1:
      fdisk, gdisk, sgdisk, parted, partx, partprobe, lsblk, blkid,
      mkfs / mke2fs, mkswap, swapon, fsck / e2fsck, dumpe2fs, wipefs

   Grade yourself at any time with:      sudo $0 check
   If the VM reboots, re-attach with:    sudo $0 reattach
   Give up / start over:                 sudo $0 cleanup && sudo $0 break

   The full step-by-step solution is at the bottom of this script, commented
   out. Read it only after you have genuinely tried:   tail -n 130 "$0"
===============================================================================

EOF
}

# --------------------------------------------------------------------- check

do_check() {
    local failures=0
    printf '\n=== GRADING - LPIC-1 104.1 break & fix ===\n\n'

    # --- 1. partition table -------------------------------------------------
    if wait_for_node "${LOOP}p1" && [[ -b "${LOOP}p2" && -b "${LOOP}p3" ]]; then
        ok "partition nodes ${LOOP}p1..p3 exist"
    else
        bad "partitions are still missing - the partition table is not restored"
        printf '       hint: after writing the table, ask the kernel to re-read it (partx -a / partprobe)\n'
        failures=$((failures + 1))
    fi

    if sgdisk -p "$LOOP" 2>/dev/null | grep -q 'GPT: present'; then
        ok "a valid GPT label is present"
    elif sgdisk -p "$LOOP" >/dev/null 2>&1 && [[ -b "${LOOP}p1" ]]; then
        ok "a partition table is present"
    else
        bad "no valid partition table found on $LOOP"
        failures=$((failures + 1))
    fi

    local t1 t3
    t1="$(sgdisk -i 1 "$LOOP" 2>/dev/null | awk -F'[()]' '/Partition GUID code/ {print $2; exit}')"
    t3="$(sgdisk -i 3 "$LOOP" 2>/dev/null | awk -F'[()]' '/Partition GUID code/ {print $2; exit}')"
    if [[ "$t1" == *"Linux filesystem"* ]]; then
        ok "partition 1 type code restored (Linux filesystem / 8300)"
    else
        bad "partition 1 type code is '${t1:-unknown}', expected Linux filesystem (8300)"
        failures=$((failures + 1))
    fi
    if [[ "$t3" == *"swap"* ]]; then
        ok "partition 3 type code restored (Linux swap / 8200)"
    else
        bad "partition 3 type code is '${t3:-unknown}', expected Linux swap (8200)"
        failures=$((failures + 1))
    fi

    # --- 2. ext4 payload ----------------------------------------------------
    if [[ -b "${LOOP}p1" ]] && dumpe2fs -h "${LOOP}p1" >/dev/null 2>&1; then
        ok "ext4 superblock on ${LOOP}p1 is readable again"
        if e2fsck -fn "${LOOP}p1" >/dev/null 2>&1; then
            ok "e2fsck -fn reports the filesystem clean"
        else
            bad "e2fsck still reports errors on ${LOOP}p1 - run a full 'e2fsck -fy' and check again"
            failures=$((failures + 1))
        fi
        mountpoint -q "$MNT" && umount "$MNT" || true
        if mount "${LOOP}p1" "$MNT" 2>/dev/null; then
            local now
            now="$(payload_sha "$MNT" 2>/dev/null || echo none)"
            if [[ "$now" == "$DATA_SHA" ]]; then
                ok "payload intact - SHA-256 of /payroll + /etc-backup matches the original"
            else
                bad "payload does NOT match the original (files lost, altered, or the filesystem was re-created)"
                printf '       expected %s\n       found    %s\n' "$DATA_SHA" "$now"
                printf '       files now present: %s\n' \
                    "$(find "$MNT" -maxdepth 2 -type f 2>/dev/null | wc -l)"
                failures=$((failures + 1))
            fi
            umount "$MNT"
        else
            bad "${LOOP}p1 still refuses to mount read-write"
            failures=$((failures + 1))
        fi
    else
        bad "no readable ext4 superblock on ${LOOP}p1"
        printf '       hint: mke2fs -n <dev> prints where the backup superblocks are; e2fsck -b <block> uses one\n'
        failures=$((failures + 1))
    fi

    # --- 3. untouched control partition ------------------------------------
    if [[ -b "${LOOP}p2" ]]; then
        mountpoint -q "$MNT" && umount "$MNT" || true
        if mount -o ro "${LOOP}p2" "$MNT" 2>/dev/null; then
            if [[ -f "$MNT/FIRMWARE.BIN" || -f "$MNT/firmware.bin" ]]; then
                ok "control partition ${LOOP}p2 intact - the table was restored at the original offsets"
            else
                bad "${LOOP}p2 mounts but FIRMWARE.BIN is gone - the partition boundaries are wrong"
                failures=$((failures + 1))
            fi
            umount "$MNT"
        else
            bad "${LOOP}p2 does not mount - most likely its start sector is off by some sectors"
            failures=$((failures + 1))
        fi
    else
        bad "${LOOP}p2 does not exist"
        failures=$((failures + 1))
    fi

    # --- 4. swap ------------------------------------------------------------
    local stype=""
    [[ -b "${LOOP}p3" ]] && stype="$(blkid -p -o value -s TYPE "${LOOP}p3" 2>/dev/null || true)"
    if [[ "$stype" == "swap" ]]; then
        ok "a valid swap signature exists on ${LOOP}p3"
        if [[ "$SWAP_ACTIVATABLE" == "yes" ]]; then
            if grep -q "^${LOOP}p3 " /proc/swaps || swapon "${LOOP}p3" 2>/dev/null; then
                ok "swap area activates (swapon succeeded)"
                swapoff "${LOOP}p3" 2>/dev/null || true
            else
                bad "the signature is there but swapon still fails on ${LOOP}p3"
                failures=$((failures + 1))
            fi
        fi
    else
        bad "no swap signature on ${LOOP}p3 (blkid TYPE='${stype:-none}')"
        printf '       hint: swap has no data worth saving - mkswap is the right answer here\n'
        failures=$((failures + 1))
    fi

    printf '\n'
    if ((failures == 0)); then
        ok "ALL CHECKS PASSED - the disk is fully recovered and no data was lost."
        printf '    Now explain out loud, without looking: why did the backup GPT survive,\n'
        printf '    and why does ext4 keep more than one superblock?\n\n'
        return 0
    fi
    bad "$failures check(s) still failing - keep going."
    printf '\n'
    return 1
}

# -------------------------------------------------------------------- status

do_status() {
    printf '\nlab image : %s\nloop dev  : %s\n\n' "$IMG" "$LOOP"
    lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL,MOUNTPOINTS "$LOOP" 2>/dev/null || true
    printf '\n--- sgdisk -p ---\n'
    sgdisk -p "$LOOP" 2>&1 | sed 's/^/    /' || true
    printf '\n--- blkid ---\n'
    blkid "${LOOP}"p* 2>/dev/null | sed 's/^/    /' || printf '    (no partitions)\n'
    printf '\n'
}

# ------------------------------------------------------------------- cleanup

do_cleanup() {
    if [[ -f "$STATE" ]]; then
        # shellcheck disable=SC1090
        source "$STATE"
        if [[ -n "${LOOP:-}" && -b "$LOOP" ]]; then
            release_loop "$LOOP"
            losetup -d "$LOOP" 2>/dev/null || true
        fi
    fi
    local dev
    for dev in $(losetup -n -O NAME -j "$IMG" 2>/dev/null || true); do
        release_loop "$dev"
        losetup -d "$dev" 2>/dev/null || true
    done
    [[ "$LAB_DIR" == /var/tmp/* || "$LAB_DIR" == /tmp/* ]] \
        || die "refusing to remove a lab directory outside /tmp or /var/tmp: $LAB_DIR"
    rm -rf "${LAB_DIR:?}"
    ok "lab removed - no loop devices, no image, nothing left behind"
}

# ---------------------------------------------------------------------- main

main() {
    local action="${1:-break}"
    case "$action" in
        break)
            need_root "$@"
            need_cmd losetup dd sgdisk
            if [[ -f "$STATE" ]]; then
                die "a lab already exists. Grade it with '$0 check' or remove it with '$0 cleanup'."
            fi
            printf '\nThis builds a file-backed lab disk and deliberately destroys structures on it.\n'
            printf 'It only ever writes to its own loop device (%s).\n' "$IMG"
            printf 'Run it on a disposable lab VM.\n\n'
            if [[ "${LPIC_LAB_CONFIRM:-}" != "yes" ]]; then
                read -r -p "Type 'yes' to build and break the lab: " answer
                [[ "$answer" == "yes" ]] || die "cancelled"
            fi
            do_setup
            do_break
            ;;
        check)
            need_root "$@"; load_state; ensure_loop; rescan_partitions; do_check
            ;;
        status)
            need_root "$@"; load_state; ensure_loop; do_status
            ;;
        reattach)
            need_root "$@"; load_state; ensure_loop; rescan_partitions
            ok "image attached at $LOOP"
            ;;
        cleanup)
            need_root "$@"; do_cleanup
            ;;
        brief|briefing)
            load_state; ensure_loop; print_briefing
            ;;
        *)
            printf 'usage: %s {break|check|status|brief|reattach|cleanup}\n' "$0" >&2
            exit 2
            ;;
    esac
}

main "$@"

# =============================================================================
#  S O L U T I O N   -   step by step
#  Stop here unless you have already tried. Everything below is commented out.
# =============================================================================
#
#  Throughout, replace /dev/loopX with the device the briefing printed
#  (`losetup -j /var/tmp/lpic1-104.1-lab/disk.img` tells you which one it is).
#
# -----------------------------------------------------------------------------
#  STEP 0 - observe before you touch anything
# -----------------------------------------------------------------------------
#   lsblk /dev/loopX
#   fdisk -l /dev/loopX
#   gdisk -l /dev/loopX
#
#   gdisk is the informative one here. It prints something like:
#
#     Caution: invalid main GPT header, but valid backup; regenerating main header
#     using backup!
#     Warning: Invalid CRC on main header data; loaded backup partition table.
#     ...
#     Partition table scan:
#       MBR: not present
#       BSD: not present
#       APM: not present
#       GPT: damaged
#
#   That single line - "valid backup" - is the whole reason this is repairable.
#   A GPT disk carries TWO copies of the header and of the partition entry
#   array: the primary at LBA 1 (entries at LBA 2-33) and the backup in the
#   LAST sectors of the disk. Only the primary was destroyed.
#
# -----------------------------------------------------------------------------
#  STEP 1 - rebuild the primary GPT from the backup GPT
# -----------------------------------------------------------------------------
#   gdisk /dev/loopX
#     r        <- recovery & transformation menu
#     b        <- use the backup GPT header to rebuild the main header
#     v        <- verify: should now report "No problems found"
#     p        <- print the table; check the three partitions are back with
#                 their sizes (600 MiB / 128 MiB / 128 MiB), type codes
#                 8300 / 0700 / 8200 and names lpic-data / lpic-vfat / lpic-swap
#     w        <- write the table to disk and confirm with 'Y'
#
#   Equivalent non-interactive form (sgdisk loads the backup automatically when
#   the primary is unreadable, so simply writing the table back repairs it):
#     sgdisk --verify /dev/loopX
#     sgdisk --move-second-header /dev/loopX      # rewrites both copies
#
#   Then make the KERNEL re-read the table - writing it to disk is not enough:
#     partx -a /dev/loopX        # or: partprobe /dev/loopX
#     lsblk /dev/loopX
#
#   You should now see loopXp1, loopXp2 and loopXp3 again. Verify immediately
#   that the untouched partition is healthy - that is your proof the offsets
#   are correct and not merely plausible:
#     mount -o ro /dev/loopXp2 /mnt && ls -l /mnt && umount /mnt
#
#   Note on MBR disks: the same accident on MBR (dd of the first 512 bytes) is
#   NOT recoverable this way, because MBR keeps a single copy of the table.
#   That is why `sfdisk --dump /dev/sda > table.txt` (restored with
#   `sfdisk /dev/sda < table.txt`) belongs in every backup plan.
#
# -----------------------------------------------------------------------------
#  STEP 2 - recover the ext4 filesystem from a backup superblock
# -----------------------------------------------------------------------------
#   Confirm the damage first:
#     blkid /dev/loopXp1                 # prints nothing
#     dumpe2fs -h /dev/loopXp1           # "Couldn't find valid filesystem superblock"
#     mount /dev/loopXp1 /mnt            # "can't read superblock"
#
#   Find the backup superblocks. mke2fs -n computes the layout it WOULD create
#   and writes nothing at all - it is the safe way to ask "where would the
#   backups be?" for a filesystem created with the same defaults:
#
#     mke2fs -n /dev/loopXp1
#       ...
#       Superblock backups stored on blocks:
#               32768, 98304
#
#   (dumpe2fs on a healthy ext4 shows the same numbers. With the default
#   sparse_super feature, backups live in block groups 1, 3, 5, 7, 9, 25, 27,
#   49, 81 ... - with 4 KiB blocks and 32768 blocks per group, group 1 starts
#   at block 32768. On a filesystem smaller than 512 MiB mke2fs picks 1 KiB
#   blocks instead and the first backup is at block 8193 - always ASK the tool,
#   never memorise one number.)
#
#   Repair using the backup. -b selects the alternate superblock, -B states the
#   block size explicitly because the primary superblock that would normally
#   declare it is gone, -f forces a full check and -y answers yes to every
#   question:
#
#     e2fsck -f -y -b 32768 -B 4096 /dev/loopXp1
#
#   Expected output (abridged):
#     Pass 1: Checking inodes, blocks, and sizes
#     Pass 2: Checking directory structure
#     Pass 3: Checking directory connectivity
#     Pass 4: Checking reference counts
#     Pass 5: Checking group summary information
#     Free blocks count wrong for group #0 (...): FIXED
#     LPICDATA: ***** FILE SYSTEM WAS MODIFIED *****
#
#   e2fsck copies the backup superblock and the backup group descriptors over
#   the primary ones when it writes out, so the filesystem is fully repaired,
#   not just readable through a detour. Confirm and re-check:
#
#     e2fsck -f -y /dev/loopXp1          # second run must be clean
#     blkid /dev/loopXp1                 # LABEL="LPICDATA" TYPE="ext4"
#     mount /dev/loopXp1 /mnt
#     ls -l /mnt/payroll | head          # 24 slips + CANARY.txt
#     cat /mnt/payroll/CANARY.txt
#     umount /mnt
#
#   If files had ended up in /mnt/lost+found, that is e2fsck telling you it
#   reconnected orphaned inodes - inspect them there before declaring victory.
#
#   What you must NOT do: mkfs.ext4 /dev/loopXp1. It succeeds instantly, the
#   partition mounts, every check except the data check goes green, and the
#   payroll files are gone forever.
#
# -----------------------------------------------------------------------------
#  STEP 3 - rebuild the swap area
# -----------------------------------------------------------------------------
#   Swap holds no persistent data, so re-creating the structure is correct:
#
#     blkid /dev/loopXp3                 # prints nothing - signature gone
#     mkswap -L LPICSWAP /dev/loopXp3
#       Setting up swapspace version 1, size = 128 MiB (134213632 bytes)
#       LABEL=LPICSWAP, UUID=....
#     swapon /dev/loopXp3
#     swapon --show                      # or: cat /proc/swaps
#     swapoff /dev/loopXp3
#
#   Two details the exam likes:
#     * mkswap generates a NEW UUID. Any /etc/fstab entry written as
#       UUID=<old> will now fail at boot - re-read the UUID with
#       `blkid /dev/loopXp3` and update fstab (or use LABEL=, which mkswap -L
#       preserved on purpose).
#     * The GPT type code 8200 does not make a partition swap; only mkswap
#       does. The type code is metadata for tools and firmware. Conversely,
#       systemd-gpt-auto-generator DOES act on 8200, so on a real system a
#       correct type code is what makes swap activate without an fstab entry.
#
# -----------------------------------------------------------------------------
#  STEP 4 - verify like an SRE, not like a student
# -----------------------------------------------------------------------------
#     lsblk -o NAME,SIZE,TYPE,FSTYPE,LABEL,UUID /dev/loopX
#     sgdisk -v /dev/loopX               # "No problems found"
#     e2fsck -fn /dev/loopXp1            # clean, and it modified nothing
#     sudo ./104.1-break-and-fix.sh check
#
# -----------------------------------------------------------------------------
#  WHAT TO TAKE AWAY
# -----------------------------------------------------------------------------
#   1. Redundancy is on the disk already: GPT keeps a backup header + entry
#      array at the end of the device; ext2/3/4 keeps backup superblocks and
#      group descriptors in selected block groups. Both are free, both are
#      already there, and both are useless if you do not know they exist.
#   2. Writing a partition table and having the kernel USE it are two separate
#      events - partx -a / partprobe / blockdev --rereadpt bridge them, and a
#      busy device may refuse the re-read until you unmount.
#   3. The order of repair is bottom-up: partition table, then filesystem
#      metadata, then activation (mount / swapon). Debugging a mount failure
#      before the partition even exists is wasted effort.
#   4. mkfs is never a repair. It is the fastest way to convert a recoverable
#      incident into a permanent one.
#   5. Before any partitioning work on a real machine:
#        sfdisk --dump /dev/sda > /root/sda.table          # MBR and GPT
#        sgdisk --backup=/root/sda.gpt /dev/sda            # GPT, binary
#        blkid > /root/blkid.txt                           # UUIDs for fstab
# =============================================================================