#!/usr/bin/env bash
#
# ============================================================================
#  LPIC-1 (101-500 / 102-500) — Topic 107.2
#  Automate system administration tasks by scheduling jobs
#
#  BREAK & FIX LABORATORY — cron / anacron / at / systemd timers
#
#  WARNING: THIS SCRIPT INTENTIONALLY BREAKS JOB SCHEDULING ON THIS MACHINE.
#  Run it ONLY inside a disposable lab VM (snapshot it first).
#  It must be run as root. It never touches user data outside the paths
#  it creates, and every original file it modifies is backed up under
#  /root/107.2-lab-backup/ so an instructor can always recover the box.
#
#  Reference: LPI Exam 101/102 objectives — https://www.lpi.org/our-certifications/exam-101-objectives/
#             crontab(5), crontab(1), cron(8), anacrontab(5), at(1),
#             systemd.timer(5), systemd.time(7)
# ============================================================================

set -o nounset
set -o pipefail

readonly LAB_TAG="107.2"
readonly BACKUP_DIR="/root/107.2-lab-backup"
readonly REPORT_DIR="/var/log/billing-report"
readonly REPORT_SCRIPT="/usr/local/bin/billing-report.sh"
readonly LAB_USER="billing"
readonly SYSTEM_CRON_FILE="/etc/cron.d/billing-report"
readonly ANACRON_JOB="/etc/cron.daily/billing-rotate"
readonly TIMER_UNIT="/etc/systemd/system/billing-metrics.timer"
readonly SERVICE_UNIT="/etc/systemd/system/billing-metrics.service"
readonly METRICS_FILE="/var/lib/billing-metrics.txt"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

say()  { printf '\033[1;36m[%s]\033[0m %s\n' "$LAB_TAG" "$*"; }
warn() { printf '\033[1;33m[%s]\033[0m %s\n' "$LAB_TAG" "$*"; }
die()  { printf '\033[1;31m[%s] FATAL:\033[0m %s\n' "$LAB_TAG" "$*" >&2; exit 1; }

require_root() {
    [ "$(id -u)" -eq 0 ] || die "This lab must be run as root (try: sudo $0)."
}

require_lab_vm() {
    # Cheap guard rails. A disposable lab VM is expected; refuse on anything
    # that looks like it might matter to someone.
    if [ -f /etc/lpi-lab-vm ]; then
        return 0
    fi
    cat <<'EOF'

  ###################################################################
  #  This script DELIBERATELY BREAKS cron, at, and systemd timers.  #
  #  Only run it on a THROWAWAY lab VM you can roll back.           #
  ###################################################################

EOF
    printf 'Type exactly  BREAK MY LAB VM  to continue: '
    read -r confirmation
    [ "$confirmation" = "BREAK MY LAB VM" ] || die "Aborted. Nothing was changed."
    : > /etc/lpi-lab-vm
}

backup_file() {
    # backup_file <path> — preserve the original once, never overwrite a backup
    local src="$1"
    local dst="$BACKUP_DIR/$(printf '%s' "${src#/}" | tr '/' '_')"
    mkdir -p "$BACKUP_DIR"
    if [ -e "$src" ] && [ ! -e "$dst" ]; then
        cp -a "$src" "$dst"
    fi
}

detect_cron_service() {
    # Debian/Ubuntu call it cron.service; RHEL/Fedora/SUSE call it crond.service
    if systemctl list-unit-files 2>/dev/null | grep -q '^crond\.service'; then
        printf 'crond'
    elif systemctl list-unit-files 2>/dev/null | grep -q '^cron\.service'; then
        printf 'cron'
    else
        printf 'cron'
    fi
}

detect_at_service() {
    if systemctl list-unit-files 2>/dev/null | grep -q '^atd\.service'; then
        printf 'atd'
    else
        printf 'atd'
    fi
}

# ---------------------------------------------------------------------------
# Scenario setup — build a plausible, working production-ish job set FIRST,
# so the student sees a system that used to work and now does not.
# ---------------------------------------------------------------------------

build_working_scenario() {
    say "Building the 'before' state: a working scheduled billing pipeline..."

    getent passwd "$LAB_USER" >/dev/null 2>&1 || \
        useradd --create-home --shell /bin/bash --comment "Billing batch user" "$LAB_USER"

    mkdir -p "$REPORT_DIR"
    chown "$LAB_USER:$LAB_USER" "$REPORT_DIR"

    cat > "$REPORT_SCRIPT" <<'SCRIPT'
#!/bin/bash
# Billing report generator. Appends one line per successful run.
# Deliberately trivial: this lab is about SCHEDULING, not about the payload.
set -euo pipefail
OUT="/var/log/billing-report/report.log"
mkdir -p "$(dirname "$OUT")"
printf '%s billing report generated by %s (PATH=%s)\n' \
    "$(date --iso-8601=seconds)" "$(id -un)" "${PATH}" >> "$OUT"
SCRIPT
    chmod 0755 "$REPORT_SCRIPT"

    # A per-user crontab for the billing user, installed the supported way.
    crontab -u "$LAB_USER" - <<'CRONTAB'
# Billing pipeline — per-user crontab (crontab -e as the billing user)
MAILTO=""
*/2 * * * * /usr/local/bin/billing-report.sh
CRONTAB

    # A system-wide crontab fragment, which carries a USER field (crontab(5)).
    cat > "$SYSTEM_CRON_FILE" <<'CRONDFILE'
# /etc/cron.d/billing-report — system crontab fragment.
# NOTE the sixth field: system crontabs take a user name, user crontabs do not.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
*/5 * * * *  root  /usr/local/bin/billing-report.sh
CRONDFILE
    chmod 0644 "$SYSTEM_CRON_FILE"

    # An anacron-style daily job (/etc/cron.daily is run by anacron or by the
    # cron daily wrapper depending on the distribution).
    cat > "$ANACRON_JOB" <<'DAILY'
#!/bin/sh
# Rotate yesterday's billing report. Run out of /etc/cron.daily.
LOG=/var/log/billing-report/report.log
[ -f "$LOG" ] && mv "$LOG" "$LOG.$(date +%Y%m%d)"
exit 0
DAILY
    chmod 0755 "$ANACRON_JOB"

    # A systemd timer doing the same class of work the modern way.
    cat > "$SERVICE_UNIT" <<'SERVICE'
[Unit]
Description=Collect billing metrics

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo "$(date --iso-8601=seconds) metrics collected" >> /var/lib/billing-metrics.txt'
SERVICE

    cat > "$TIMER_UNIT" <<'TIMER'
[Unit]
Description=Collect billing metrics every 3 minutes

[Timer]
OnCalendar=*:0/3
Persistent=true
Unit=billing-metrics.service

[Install]
WantedBy=timers.target
TIMER

    systemctl daemon-reload >/dev/null 2>&1 || true
    systemctl enable --now billing-metrics.timer >/dev/null 2>&1 || \
        warn "Could not enable billing-metrics.timer (is this a systemd host?)."

    local cron_svc at_svc
    cron_svc="$(detect_cron_service)"
    at_svc="$(detect_at_service)"
    systemctl enable --now "${cron_svc}.service" >/dev/null 2>&1 || \
        warn "Could not start ${cron_svc}.service."
    systemctl enable --now "${at_svc}.service"   >/dev/null 2>&1 || \
        warn "Could not start ${at_svc}.service — install the 'at' package if missing."

    : > "$METRICS_FILE" 2>/dev/null || true

    say "Baseline built. All four scheduling mechanisms are configured and running."
}

# ---------------------------------------------------------------------------
# THE BREAKAGE
#
# Five independent faults, each one a classic 107.2 failure mode. They are
# deliberately *plausible*: every one of them is something a real admin has
# done to a real box on a Friday afternoon.
# ---------------------------------------------------------------------------

break_1_cron_deny() {
    # cron.allow / cron.deny (crontab(1), cron(8) ACCESS CONTROL).
    # If cron.allow exists, ONLY the users listed in it may use crontab.
    # Here we create a cron.allow that omits the billing user, so the user is
    # locked out of their own crontab. Note cron.allow wins over cron.deny.
    say "Fault 1/5: tightening crontab access control..."
    local dir
    for dir in /etc /etc/cron.d; do :; done
    backup_file /etc/cron.allow
    backup_file /etc/cron.deny
    rm -f /etc/cron.deny
    cat > /etc/cron.allow <<'ALLOW'
root
operations
ALLOW
    chmod 0600 /etc/cron.allow

    backup_file /etc/at.deny
    backup_file /etc/at.allow
    rm -f /etc/at.allow
    # at.deny lists users who may NOT use at/batch.
    printf '%s\n' "$LAB_USER" >> /etc/at.deny
    chmod 0640 /etc/at.deny
}

break_2_corrupt_user_crontab() {
    # Two faults in one file, both invisible until you actually read crontab(5):
    #   a) a six-field line in a USER crontab — the sixth field is parsed as
    #      part of the command, or the line is rejected entirely.
    #   b) an unescaped '%' in the command. In crontab(5) a bare % means
    #      "newline, and everything after it is stdin for the command".
    #   c) DOW/DOM interaction: when BOTH day-of-month and day-of-week are
    #      restricted, cron runs the job if EITHER matches (an OR, not an AND).
    say "Fault 2/5: rewriting the ${LAB_USER} crontab..."
    crontab -u "$LAB_USER" -l > "$BACKUP_DIR/crontab.${LAB_USER}" 2>/dev/null || true

    # Write the broken crontab directly into the spool so that the syntax
    # checks in crontab(1) do not save the student from the exercise.
    local spool
    for spool in /var/spool/cron/crontabs /var/spool/cron; do
        [ -d "$spool" ] || continue
        cat > "${spool}/${LAB_USER}" <<'BADCRON'
# Billing pipeline — per-user crontab
MAILTO=""
# Report is supposed to run every two minutes:
*/2 * * * * billing /usr/local/bin/billing-report.sh
# Month-end stamp, "only on the 1st, and only on Mondays":
0 6 1 * 1 /usr/bin/date +%Y-%m-%d >> /var/log/billing-report/stamp.log
BADCRON
        chown "$LAB_USER:crontab" "${spool}/${LAB_USER}" 2>/dev/null || \
            chown "$LAB_USER:$LAB_USER" "${spool}/${LAB_USER}" 2>/dev/null || true
        chmod 0600 "${spool}/${LAB_USER}"
        break
    done
}

break_3_environment_and_perms() {
    # The single most common cron complaint on the planet: "it works when I
    # run it by hand and does nothing from cron". cron gives the job a
    # minimal environment — no ~/.bashrc, no ~/.profile, a short PATH — and
    # here we make the script depend on something only an interactive login
    # would have, then also strip its execute bit.
    say "Fault 3/5: adjusting the report script and its environment..."
    backup_file "$REPORT_SCRIPT"
    cat > "$REPORT_SCRIPT" <<'SCRIPT'
#!/bin/bash
set -euo pipefail
# BILLING_HOME comes from /etc/profile.d/billing.sh, which cron never sources.
OUT="${BILLING_HOME}/report.log"
# 'billing-helper' lives in /opt/billing/bin, which is only on an interactive PATH.
billing-helper >> "$OUT"
SCRIPT
    chmod 0644 "$REPORT_SCRIPT"   # execute bit intentionally removed

    mkdir -p /opt/billing/bin
    cat > /opt/billing/bin/billing-helper <<'HELPER'
#!/bin/bash
printf '%s billing report generated by %s\n' "$(date --iso-8601=seconds)" "$(id -un)"
HELPER
    chmod 0755 /opt/billing/bin/billing-helper

    cat > /etc/profile.d/billing.sh <<'PROFILE'
export BILLING_HOME=/var/log/billing-report
export PATH="$PATH:/opt/billing/bin"
PROFILE
    chmod 0644 /etc/profile.d/billing.sh
}

break_4_crond_file_rules() {
    # /etc/cron.d and /etc/cron.daily files are silently ignored when they
    # break run-parts / cron naming and permission rules:
    #   - run-parts skips names containing a dot or other invalid characters
    #   - cron refuses /etc/cron.d files that are group- or world-writable
    #   - a crontab file whose last line has no trailing newline may be skipped
    say "Fault 4/5: renaming and re-permissioning the drop-in job files..."
    backup_file "$SYSTEM_CRON_FILE"
    backup_file "$ANACRON_JOB"

    # cron.d fragment: given a suffix run-parts/cron will not accept, made
    # world-writable, and stripped of its trailing newline.
    rm -f "$SYSTEM_CRON_FILE"
    printf '%s' \
'SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
*/5 * * * *  root  /usr/local/bin/billing-report.sh' \
        > /etc/cron.d/billing-report.bak
    chmod 0666 /etc/cron.d/billing-report.bak

    # cron.daily job: execute bit removed, so run-parts will not run it.
    chmod 0644 "$ANACRON_JOB" 2>/dev/null || true

    # And anacron is told the job already ran today, plus a delay long enough
    # that it will not fire again in this lab session.
    backup_file /etc/anacrontab
    if [ -f /etc/anacrontab ]; then
        sed -i 's/^START_HOURS_RANGE=.*/START_HOURS_RANGE=3-4/' /etc/anacrontab 2>/dev/null || true
    fi
    if [ -d /var/spool/anacron ]; then
        backup_file /var/spool/anacron/cron.daily
        date +%Y%m%d > /var/spool/anacron/cron.daily 2>/dev/null || true
    fi
}

break_5_systemd_timer() {
    # systemd timers fail in their own idioms:
    #   - an OnCalendar expression that is syntactically valid but means
    #     something the admin did not intend (or is simply invalid, which
    #     makes the unit fail to load)
    #   - Unit= pointing at a service that does not exist
    #   - the timer left disabled after an edit, so nothing is ever queued
    say "Fault 5/5: editing the systemd timer..."
    backup_file "$TIMER_UNIT"
    backup_file "$SERVICE_UNIT"

    systemctl disable --now billing-metrics.timer >/dev/null 2>&1 || true

    cat > "$TIMER_UNIT" <<'TIMER'
[Unit]
Description=Collect billing metrics every 3 minutes

[Timer]
# Intended: every 3 minutes. This is not that.
OnCalendar=*-*-* *:*:00/3
Persistent=true
Unit=billing-metric.service

[Install]
WantedBy=timers.target
TIMER

    systemctl daemon-reload >/dev/null 2>&1 || true
}

break_6_stop_the_daemons() {
    # Nothing scheduled runs if the scheduler is not running. Both daemons are
    # stopped AND masked, so a plain 'systemctl start' returns an error the
    # student has to read carefully.
    say "Fault 6/6: stopping the scheduling daemons..."
    local cron_svc at_svc
    cron_svc="$(detect_cron_service)"
    at_svc="$(detect_at_service)"
    systemctl stop "${cron_svc}.service" >/dev/null 2>&1 || true
    systemctl mask "${cron_svc}.service" >/dev/null 2>&1 || true
    systemctl stop "${at_svc}.service"   >/dev/null 2>&1 || true
    systemctl disable "${at_svc}.service" >/dev/null 2>&1 || true
    printf '%s\n' "$cron_svc" > "$BACKUP_DIR/cron-service-name"
    printf '%s\n' "$at_svc"   > "$BACKUP_DIR/at-service-name"
}

# ---------------------------------------------------------------------------
# The briefing the student reads
# ---------------------------------------------------------------------------

print_briefing() {
    local cron_svc at_svc
    cron_svc="$(cat "$BACKUP_DIR/cron-service-name" 2>/dev/null || echo cron)"
    at_svc="$(cat "$BACKUP_DIR/at-service-name" 2>/dev/null || echo atd)"

cat <<BRIEF

================================================================================
 LPIC-1 107.2 — BREAK & FIX: "The billing jobs stopped running"
================================================================================

THE TICKET
----------
  Overnight, every scheduled job on this host stopped producing output. The
  billing team reports that /var/log/billing-report/report.log has not been
  updated since yesterday, and the metrics file /var/lib/billing-metrics.txt
  is empty. Nobody admits to changing anything. Four different scheduling
  mechanisms are involved and ALL of them are currently broken:

    1. the per-user crontab of the '${LAB_USER}' user
    2. the system crontab fragment in /etc/cron.d/
    3. the daily job in /etc/cron.daily/ (run by anacron / run-parts)
    4. the systemd timer 'billing-metrics.timer'

  On top of that, the '${LAB_USER}' user can no longer edit their own crontab,
  and cannot schedule a one-shot job with 'at'.

SYMPTOMS YOU WILL SEE
---------------------
  * '/var/log/billing-report/report.log' never gets a new line, no matter how
    long you wait.

  * '/var/lib/billing-metrics.txt' stays empty (0 bytes).

  * As the billing user:
        \$ su - ${LAB_USER} -c 'crontab -e'
        You (${LAB_USER}) are not allowed to use this program (crontab)
        See crontab(1) for more information

        \$ su - ${LAB_USER} -c 'echo /bin/true | at now + 1 minute'
        You do not have permission to use at.

  * As root:
        \$ systemctl status ${cron_svc}
        ● ${cron_svc}.service
             Loaded: masked (Reason: Unit ${cron_svc}.service is masked.)
             Active: inactive (dead)

        \$ systemctl start ${cron_svc}
        Failed to start ${cron_svc}.service: Unit ${cron_svc}.service is masked.

        \$ systemctl list-timers --all | grep billing
        (either nothing at all, or a timer that never has a NEXT value)

        \$ systemctl status billing-metrics.timer
             Active: inactive (dead)
        ... and once started, journalctl reports a failure to resolve the
        Unit= it points at.

  * Running the report script by hand also fails now:
        \$ /usr/local/bin/billing-report.sh
        bash: /usr/local/bin/billing-report.sh: Permission denied

    ...and after you fix that, it still behaves differently under cron than it
    does in your shell. That difference is the whole point of the exercise.

YOUR OBJECTIVE — "done" means ALL of the following are true
-----------------------------------------------------------
  [ ] A. The cron daemon and the at daemon are both running and enabled at boot.

  [ ] B. User '${LAB_USER}' can run 'crontab -e' and 'at' again, WITHOUT you
         simply deleting all access control — the access files must end up in a
         state you can justify to an auditor, and you must be able to explain
         the precedence between cron.allow and cron.deny, and between at.allow
         and at.deny.

  [ ] C. '/var/log/billing-report/report.log' gains a new line at least every
         two minutes, produced by the '${LAB_USER}' user's own crontab.

  [ ] D. The /etc/cron.d/ fragment runs its job as root every five minutes.
         You must be able to state, from crontab(5), the ONE structural
         difference between a system crontab and a user crontab that makes the
         current file wrong even after you fix its name and permissions.

  [ ] E. The /etc/cron.daily/ job is once again eligible to run, and you can
         demonstrate it by invoking the daily set the way the system does,
         rather than by calling the script directly.

  [ ] F. 'systemctl list-timers' shows billing-metrics.timer with a real NEXT
         timestamp roughly three minutes out, and
         '/var/lib/billing-metrics.txt' grows. Fix the OnCalendar expression so
         it means "every three minutes" and verify your expression BEFORE
         reloading, using the tool systemd ships for exactly that.

  [ ] G. Explain, in one sentence each:
           - why '0 6 1 * 1 ...' does not mean "6 AM on the first of the month
             when that day is a Monday";
           - why the '%' in a crontab command line is not the '%' you typed;
           - why the script worked in your shell and not under cron.

TOOLS YOU SHOULD BE REACHING FOR
--------------------------------
    man 5 crontab      man 1 crontab      man 8 cron
    man 5 anacrontab   man 1 at           man 8 run-parts
    man 5 systemd.timer                   man 7 systemd.time
    crontab -l -u <user>                  crontab -e
    systemctl status | list-timers --all | cat -l
    systemd-analyze calendar '<expr>'
    journalctl -u <unit> -f
    journalctl _COMM=cron    /var/log/cron    /var/log/syslog
    atq / atrm / at -c <jobid>
    run-parts --test /etc/cron.daily

RULES
-----
  * Do NOT read the commented solution at the bottom of this script until you
    have either fixed it or spent a genuine 45 minutes on it.
  * Do not "fix" anything by disabling security: emptying /etc/cron.allow of
    all meaning, or chmod 777 on the cron.d fragment, is a fail.
  * Everything you need is discoverable from the man pages and the logs.

  A backup of every file this lab modified is in ${BACKUP_DIR}
  (for your instructor — using it is also a fail).

================================================================================
BRIEF
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

main() {
    require_root
    require_lab_vm
    mkdir -p "$BACKUP_DIR"
    chmod 0700 "$BACKUP_DIR"

    build_working_scenario
    say "Baseline is running. Breaking it in 3 seconds..."
    sleep 3

    break_1_cron_deny
    break_2_corrupt_user_crontab
    break_3_environment_and_perms
    break_4_crond_file_rules
    break_5_systemd_timer
    break_6_stop_the_daemons

    print_briefing
}

main "$@"

# ============================================================================
#
#   S O L U T I O N   —   S T O P   R E A D I N G   I F   Y O U   H A V E
#   N O T   T R I E D   Y E T
#
# ============================================================================
#
# ---------------------------------------------------------------------------
# STEP 0 — Triage: is the scheduler even alive?
# ---------------------------------------------------------------------------
#
#   Before reading a single crontab, confirm the daemons. A perfect crontab on
#   a dead daemon produces exactly the same symptom as a broken crontab.
#
#     # systemctl status cron    # Debian/Ubuntu
#     # systemctl status crond   # RHEL/Fedora/SUSE
#     ● cron.service
#          Loaded: masked (Reason: Unit cron.service is masked.)
#          Active: inactive (dead)
#
#   'masked' is not 'disabled'. A masked unit is symlinked to /dev/null and
#   CANNOT be started until it is unmasked — this is why 'systemctl start'
#   returns "Unit is masked" instead of just working.
#
#     # systemctl unmask cron
#     Removed /etc/systemd/system/cron.service.
#     # systemctl enable --now cron
#     # systemctl is-active cron
#     active
#
#     # systemctl enable --now atd
#     # systemctl is-active atd
#     active
#
#   Objective A is now met. Confirm with:
#     # systemctl list-unit-files | grep -E '^(cron|crond|atd)\.service'
#     cron.service     enabled  enabled
#     atd.service      enabled  enabled
#
# ---------------------------------------------------------------------------
# STEP 1 — Access control: cron.allow / cron.deny and at.allow / at.deny
# ---------------------------------------------------------------------------
#
#   Symptom:
#     # su - billing -c 'crontab -l'
#     You (billing) are not allowed to use this program (crontab)
#
#   The rule, from crontab(1) and cron(8):
#
#     * If /etc/cron.allow EXISTS, it is authoritative: only users listed in
#       it may use crontab. /etc/cron.deny is then IGNORED ENTIRELY.
#     * If cron.allow does NOT exist, cron.deny is consulted: everyone except
#       the users listed there may use crontab.
#     * If NEITHER file exists, behaviour is distribution-dependent — on
#       Debian all users may use cron; on some builds only root may.
#     * root is always allowed regardless.
#
#     The at(1) pair works identically: at.allow wins over at.deny, and if
#     neither exists, only root may use at.
#
#   Inspect:
#     # ls -l /etc/cron.allow /etc/cron.deny /etc/at.allow /etc/at.deny
#     -rw------- 1 root root 20 ... /etc/cron.allow
#     ls: cannot access '/etc/cron.deny': No such file or directory
#     ls: cannot access '/etc/at.allow': No such file or directory
#     -rw-r----- 1 root daemon 12 ... /etc/at.deny
#
#     # cat /etc/cron.allow
#     root
#     operations
#
#   The billing user is missing from the allow-list, and is explicitly present
#   in at.deny. The correct fix is NOT to delete the allow-list (that changes
#   the policy of the whole machine); it is to add the one account that is
#   supposed to be there, and to remove the one wrong deny entry:
#
#     # printf 'billing\n' >> /etc/cron.allow
#     # chmod 0600 /etc/cron.allow
#     # sed -i '/^billing$/d' /etc/at.deny
#
#   Verify:
#     # su - billing -c 'crontab -l' >/dev/null && echo OK
#     OK
#     # su - billing -c 'echo /bin/true | at now + 1 minute'
#     warning: commands will be executed using /bin/sh
#     job 1 at Thu Aug 27 12:34:00 2026
#     # atq
#     1       Thu Aug 27 12:34:00 2026 a billing
#
#   (Inspect the queued job's saved environment with 'at -c 1'; remove it with
#   'atrm 1'. Note that at snapshots your entire environment at submit time —
#   the opposite of cron's behaviour, and a favourite exam distinction.)
#
#   Objective B met.
#
# ---------------------------------------------------------------------------
# STEP 2 — The user crontab: field count, '%', and the DOM/DOW trap
# ---------------------------------------------------------------------------
#
#     # crontab -l -u billing
#     # Billing pipeline — per-user crontab
#     MAILTO=""
#     */2 * * * * billing /usr/local/bin/billing-report.sh
#     0 6 1 * 1 /usr/bin/date +%Y-%m-%d >> /var/log/billing-report/stamp.log
#
#   Three defects:
#
#   (a) SIX time-ish fields in a USER crontab. Format, per crontab(5):
#
#         user crontab:    m h dom mon dow  COMMAND
#         system crontab:  m h dom mon dow  USER  COMMAND
#                          (/etc/crontab and /etc/cron.d/* only)
#
#       Here 'billing' is being taken as the first word of the command, so
#       cron tries to execute a program literally named 'billing'. In the log:
#
#         # journalctl -u cron --since '-10 min' | tail -3
#         CRON[1841]: (billing) CMD (billing /usr/local/bin/billing-report.sh)
#         CRON[1840]: (CRON) info (No MTA installed, discarding output)
#
#       That "No MTA" line is the second lesson: cron mails stdout/stderr to
#       the job owner, and with no mail transport the evidence is discarded.
#       Set MAILTO to a real address, or redirect the job's output to a file,
#       or you are debugging blind.
#
#       Fix: drop the user field.
#
#         */2 * * * * /usr/local/bin/billing-report.sh
#
#   (b) The '%' in '/usr/bin/date +%Y-%m-%d'. In crontab(5), an unescaped '%'
#       is translated to a NEWLINE, and everything after the first '%' becomes
#       standard input to the command. So cron actually runs:
#
#         /usr/bin/date +
#       with stdin:
#         Y-m-d >> /var/log/billing-report/stamp.log
#
#       ...which is why the redirect never happens and 'date' errors out. Each
#       '%' must be escaped with a backslash:
#
#         0 6 1 * 1 /usr/bin/date +\%Y-\%m-\%d >> /var/log/billing-report/stamp.log
#
#       (In a system crontab or a cron.d fragment the same rule applies. The
#       robust habit is to put anything non-trivial in a script and call the
#       script — a crontab line is not a shell script.)
#
#   (c) The day-of-month / day-of-week OR. From crontab(5):
#
#         "Note: The day of a command's execution can be specified in the
#          following two fields — day of month, and day of week. If both
#          fields are restricted (i.e. are not *), the command will be run
#          when EITHER field matches the current time."
#
#       So '0 6 1 * 1' means 06:00 on the 1st of every month, AND ALSO 06:00
#       every Monday — not the intersection. To get "the 1st, only if it is a
#       Monday" you must test inside the command:
#
#         0 6 1 * *  [ "$(date +\%u)" -eq 1 ] && /usr/local/bin/month-start.sh
#
#   Install the corrected crontab the supported way — never by editing the
#   spool file directly, because 'crontab -e'/'crontab <file>' is what triggers
#   cron to re-read it and what runs the syntax check:
#
#     # crontab -u billing - <<'EOF'
#     MAILTO=root
#     */2 * * * * /usr/local/bin/billing-report.sh
#     0 6 1 * *  [ "$(date +\%u)" -eq 1 ] && /usr/bin/date +\%Y-\%m-\%d >> /var/log/billing-report/stamp.log
#     EOF
#     # crontab -l -u billing
#
# ---------------------------------------------------------------------------
# STEP 3 — Permissions and the cron environment
# ---------------------------------------------------------------------------
#
#     # ls -l /usr/local/bin/billing-report.sh
#     -rw-r--r-- 1 root root 214 ... /usr/local/bin/billing-report.sh
#
#   No execute bit. cron invokes the command through /bin/sh -c, so this gives
#   "Permission denied" in the mail/log, not a shell error you can see.
#
#     # chmod 0755 /usr/local/bin/billing-report.sh
#
#   Now run it as the billing user, non-interactively, which is the closest
#   cheap approximation of what cron does:
#
#     # su billing -s /bin/sh -c '/usr/local/bin/billing-report.sh'
#     /usr/local/bin/billing-report.sh: line 4: BILLING_HOME: unbound variable
#
#   The script depends on /etc/profile.d/billing.sh. cron does NOT run a login
#   shell and does NOT source /etc/profile, ~/.profile or ~/.bashrc. What cron
#   actually provides (crontab(5)) is essentially:
#
#     SHELL=/bin/sh
#     PATH=/usr/bin:/bin          (short! not your interactive PATH)
#     LOGNAME, HOME               (from /etc/passwd)
#     MAILTO                      (if set in the crontab)
#
#   plus whatever VAR=value assignments appear in the crontab itself. Prove it
#   to yourself with a throwaway job:
#
#     * * * * * env > /tmp/cron-env.txt
#     # diff <(sort /tmp/cron-env.txt) <(env | sort)
#
#   There are three legitimate fixes, in descending order of preference:
#
#     1. Make the script self-sufficient — the correct production answer.
#          #!/bin/bash
#          set -euo pipefail
#          export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/billing/bin
#          BILLING_HOME="${BILLING_HOME:-/var/log/billing-report}"
#          /opt/billing/bin/billing-helper >> "$BILLING_HOME/report.log"
#
#        Absolute paths for every binary, and defaults for every variable.
#
#     2. Set the variables in the crontab itself. crontab(5) allows
#        assignments before the job lines; they are NOT shell, so no quotes
#        are expanded and no other variables are interpolated:
#          PATH=/usr/local/bin:/usr/bin:/bin:/opt/billing/bin
#          BILLING_HOME=/var/log/billing-report
#          */2 * * * * /usr/local/bin/billing-report.sh
#
#     3. Source the profile explicitly from the job line — works, but couples
#        a batch job to interactive login configuration; use only when you
#        cannot change the script:
#          */2 * * * * . /etc/profile.d/billing.sh; /usr/local/bin/billing-report.sh
#
#   Apply fix 1, then confirm the directory is writable by the job's user:
#
#     # install -d -o billing -g billing -m 0755 /var/log/billing-report
#     # su billing -s /bin/sh -c '/usr/local/bin/billing-report.sh' && tail -1 /var/log/billing-report/report.log
#     2026-08-27T12:40:01+00:00 billing report generated by billing
#
#   Wait two minutes and confirm cron itself is doing it:
#
#     # sleep 130; tail -2 /var/log/billing-report/report.log
#     # journalctl -u cron --since '-5 min' | grep billing
#     CRON[2210]: (billing) CMD (/usr/local/bin/billing-report.sh)
#
#   Objective C met.
#
# ---------------------------------------------------------------------------
# STEP 4 — /etc/cron.d: file name, permissions, trailing newline, USER field
# ---------------------------------------------------------------------------
#
#     # ls -l /etc/cron.d/
#     -rw-rw-rw- 1 root root 133 ... billing-report.bak
#
#   Three separate reasons this file is inert:
#
#   (a) THE NAME. Files in /etc/cron.d are processed with run-parts naming
#       rules: the name must consist only of upper/lower case letters, digits,
#       underscores and hyphens. A '.' anywhere in the name — '.bak', '.conf',
#       '.disabled' — makes the file INVISIBLE to cron. This is why renaming a
#       cron.d file to 'foo.bak' is the standard way to disable it, and why
#       'foo.conf' silently never runs. Verify the rule on your distro with:
#
#         # run-parts --test /etc/cron.d
#         (the .bak file is absent from the output)
#
#   (b) THE PERMISSIONS. cron refuses any file in /etc/cron.d (and /etc/crontab
#       itself) that is writable by group or other, and logs it:
#
#         # journalctl -u cron | grep -i cron.d
#         cron[701]: (*system*) INSECURE MODE (mode 0600 expected) (/etc/cron.d/...)
#
#       Required: owned by root, mode 0644 (some builds accept 0600).
#
#   (c) THE MISSING TRAILING NEWLINE. A crontab file must end with a newline;
#       cron may silently drop the final line otherwise. Check with:
#
#         # tail -c 1 /etc/cron.d/billing-report | xxd
#         00000000: 0a                                       .
#
#   And the structural point Objective D asks about: /etc/cron.d files and
#   /etc/crontab are SYSTEM crontabs, so they have SIX fields before the
#   command — the sixth is the USER to run as. That is the exact opposite of
#   Step 2(a): the user field is REQUIRED here and FORBIDDEN there. Getting
#   this backwards is the single most common cron mistake there is.
#
#   Fix:
#     # mv /etc/cron.d/billing-report.bak /etc/cron.d/billing-report
#     # chown root:root /etc/cron.d/billing-report
#     # chmod 0644 /etc/cron.d/billing-report
#     # printf '\n' >> /etc/cron.d/billing-report      # ensure trailing newline
#     # cat /etc/cron.d/billing-report
#     SHELL=/bin/bash
#     PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#     */5 * * * *  root  /usr/local/bin/billing-report.sh
#
#   cron re-reads /etc/cron.d automatically (it stats the directory every
#   minute); no restart is needed, and restarting to "make it pick up" is a
#   habit worth unlearning. Confirm:
#
#     # journalctl -u cron --since '-6 min' | grep 'CMD'
#     CRON[2402]: (root) CMD (/usr/local/bin/billing-report.sh)
#
#   Objective D met.
#
# ---------------------------------------------------------------------------
# STEP 5 — /etc/cron.daily and anacron
# ---------------------------------------------------------------------------
#
#     # ls -l /etc/cron.daily/billing-rotate
#     -rw-r--r-- 1 root root 138 ... /etc/cron.daily/billing-rotate
#
#   /etc/cron.{hourly,daily,weekly,monthly} are executed by run-parts, which
#   runs only files that are EXECUTABLE and whose names pass the same naming
#   rule as Step 4(a). No execute bit means the job simply never runs, with no
#   error anywhere.
#
#     # chmod 0755 /etc/cron.daily/billing-rotate
#     # run-parts --test /etc/cron.daily
#     /etc/cron.daily/billing-rotate
#     ...
#
#   '--test' prints what WOULD run without running it — that is the way to
#   demonstrate Objective E, rather than executing the script by hand (calling
#   it directly proves the script works, not that the system will call it).
#
#   Now the anacron side. anacron exists for machines that are not on 24/7: it
#   works in DAYS, not clock times, and runs a job if the recorded timestamp is
#   older than the period.
#
#     # cat /etc/anacrontab
#     SHELL=/bin/sh
#     PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#     RANDOM_DELAY=45
#     START_HOURS_RANGE=3-4
#     # period  delay  job-identifier  command
#     1         5      cron.daily      run-parts --report /etc/cron.daily
#     7         25     cron.weekly     run-parts --report /etc/cron.weekly
#     @monthly  45     cron.monthly    run-parts --report /etc/cron.monthly
#
#   Fields, per anacrontab(5): PERIOD in days (or @daily/@weekly/@monthly),
#   DELAY in minutes after anacron starts, a JOB-ID used as the timestamp file
#   name, and the command. START_HOURS_RANGE bounds the hours during which
#   jobs may start; RANDOM_DELAY adds jitter so a fleet does not stampede.
#
#   The timestamps live in /var/spool/anacron/, one file per job-id, each
#   containing the YYYYMMDD of the last successful run:
#
#     # cat /var/spool/anacron/cron.daily
#     20260827
#
#   Because that is today's date, anacron considers cron.daily already done.
#   To force a run now, ignoring both the timestamp and the hours range:
#
#     # anacron -f -n -d cron.daily
#         -f  force: ignore the timestamps
#         -n  now: ignore the delay
#         -d  foreground, log to stderr instead of syslog
#
#   Or reset the timestamp so the normal schedule picks it up:
#     # date -d yesterday +%Y%m%d > /var/spool/anacron/cron.daily
#
#   (Restore START_HOURS_RANGE to your distribution's default if you widened
#   it; the lab narrowed it to 3-4 to keep the job from firing mid-session.)
#
#   Objective E met.
#
# ---------------------------------------------------------------------------
# STEP 6 — The systemd timer
# ---------------------------------------------------------------------------
#
#     # systemctl list-timers --all | grep billing
#     (nothing — the timer is disabled AND stopped)
#
#     # systemctl status billing-metrics.timer
#     ● billing-metrics.timer - Collect billing metrics every 3 minutes
#          Loaded: loaded (/etc/systemd/system/billing-metrics.timer; disabled)
#          Active: inactive (dead)
#
#     # systemctl start billing-metrics.timer
#     Failed to start billing-metrics.timer: Unit billing-metric.service not found.
#
#   Two faults:
#
#   (a) 'Unit=billing-metric.service' — singular, and no such unit exists. The
#       Unit= directive names the service the timer activates; when omitted it
#       defaults to the same base name as the timer with a .service suffix.
#       The typo is why the timer will not even start.
#
#   (b) 'OnCalendar=*-*-* *:*:00/3'. This is a SECONDS expression: it means
#       "every third second starting at second 0, of every minute" — not every
#       three minutes. Never guess at a calendar expression; systemd ships a
#       validator, and using it is the point of Objective F:
#
#         # systemd-analyze calendar '*-*-* *:*:00/3'
#         Original form: *-*-* *:*:00/3
#         Normalized form: *-*-* *:*:00/3
#            Next elapse: Thu 2026-08-27 12:45:03 UTC
#               (in UTC): Thu 2026-08-27 12:45:03 UTC
#               From now: 1s left
#
#         # systemd-analyze calendar --iterations=4 '*:0/3'
#         Original form: *:0/3
#         Normalized form: *-*-* *:00/3:00
#            Next elapse: Thu 2026-08-27 12:48:00 UTC
#               From now: 2min 14s left
#            Iter. #2: Thu 2026-08-27 12:51:00 UTC
#            Iter. #3: Thu 2026-08-27 12:54:00 UTC
#            Iter. #4: Thu 2026-08-27 12:57:00 UTC
#
#       '*:0/3' — every third MINUTE from minute 0 — is what was intended.
#       ('OnUnitActiveSec=3min' is the other correct answer, and a different
#       thing: monotonic, relative to the last activation, rather than wall
#       clock. Use OnCalendar when the wall-clock instant matters, monotonic
#       timers when the interval between runs matters.)
#
#   Fix the unit:
#     # cat /etc/systemd/system/billing-metrics.timer
#     [Unit]
#     Description=Collect billing metrics every 3 minutes
#
#     [Timer]
#     OnCalendar=*:0/3
#     Persistent=true
#     Unit=billing-metrics.service
#
#     [Install]
#     WantedBy=timers.target
#
#   Then — and this order matters — reload, enable, start, verify:
#
#     # systemd-analyze verify /etc/systemd/system/billing-metrics.timer
#     # systemctl daemon-reload
#     # systemctl enable --now billing-metrics.timer
#     Created symlink /etc/systemd/system/timers.target.wants/billing-metrics.timer → ...
#     # systemctl list-timers billing-metrics.timer
#     NEXT                        LEFT     LAST  PASSED  UNIT                   ACTIVATES
#     Thu 2026-08-27 12:48:00 UTC 2min 9s  -     -       billing-metrics.timer  billing-metrics.service
#
#     # sleep 200; cat /var/lib/billing-metrics.txt
#     2026-08-27T12:48:00+00:00 metrics collected
#     # systemctl status billing-metrics.service
#          Active: inactive (dead) since ...   <-- correct for Type=oneshot
#     # journalctl -u billing-metrics.service --since '-10 min'
#
#   Note 'Persistent=true': if the machine was off when the timer should have
#   fired, systemd runs it once immediately at next boot — the systemd
#   equivalent of what anacron does for cron. Timestamps for that live under
#   /var/lib/systemd/timers/.
#
#   Objective F met.
#
# ---------------------------------------------------------------------------
# STEP 7 — Objective G: the three one-sentence answers
# ---------------------------------------------------------------------------
#
#   * '0 6 1 * 1' does not mean "the 1st when it is a Monday" because when
#     BOTH day-of-month and day-of-week are restricted, cron ORs them — it
#     runs on the 1st of the month AND on every Monday — so an AND has to be
#     expressed as a test inside the command with dom or dow left as '*'.
#
#   * A bare '%' in a crontab command is not passed to the shell: crontab(5)
#     turns the first '%' into a newline and feeds everything after it to the
#     command on standard input, so 'date +%Y' runs as 'date +' with 'Y' as
#     stdin — it must be written '\%'.
#
#   * The script worked in your shell and not under cron because cron starts
#     the job with a minimal, non-login environment (SHELL=/bin/sh,
#     PATH=/usr/bin:/bin, HOME and LOGNAME from /etc/passwd) and never sources
#     /etc/profile, /etc/profile.d/*, ~/.profile or ~/.bashrc, so anything
#     your interactive login exported simply is not there.
#
# ---------------------------------------------------------------------------
# STEP 8 — Full verification sweep
# ---------------------------------------------------------------------------
#
#     # systemctl is-active cron atd && systemctl is-enabled cron atd
#     # su - billing -c 'crontab -l' >/dev/null && echo "crontab access OK"
#     # su - billing -c 'echo /bin/true | at now + 1 minute' && atq
#     # crontab -l -u billing
#     # ls -l /etc/cron.d/billing-report /etc/cron.daily/billing-rotate
#     # run-parts --test /etc/cron.daily | grep billing-rotate
#     # systemd-analyze calendar --iterations=3 '*:0/3'
#     # systemctl list-timers billing-metrics.timer
#     # sleep 310
#     # wc -l /var/log/billing-report/report.log   # >= 3 new lines (2-min + 5-min jobs)
#     # wc -l /var/lib/billing-metrics.txt         # >= 1 new line
#     # journalctl -u cron --since '-10 min' | grep CMD
#     # journalctl -u billing-metrics.service --since '-10 min'
#
#   All eight lines clean == lab complete.
#
# ---------------------------------------------------------------------------
# TEARDOWN (optional — or just roll back the VM snapshot)
# ---------------------------------------------------------------------------
#
#     # systemctl disable --now billing-metrics.timer
#     # rm -f /etc/systemd/system/billing-metrics.{timer,service}
#     # systemctl daemon-reload
#     # crontab -r -u billing
#     # rm -f /etc/cron.d/billing-report /etc/cron.daily/billing-rotate
#     # rm -f /usr/local/bin/billing-report.sh /etc/profile.d/billing.sh
#     # rm -rf /opt/billing /var/log/billing-report /var/lib/billing-metrics.txt
#     # sed -i '/^billing$/d' /etc/cron.allow
#     # cp -a /root/107.2-lab-backup/etc_anacrontab /etc/anacrontab   # if modified
#     # userdel -r billing
#     # rm -f /etc/lpi-lab-vm
#
# ---------------------------------------------------------------------------
# SOURCES
# ---------------------------------------------------------------------------
#   LPI Exam 101-500 objectives — https://www.lpi.org/our-certifications/exam-101-objectives/
#   LPI Exam 102-500 objectives — https://www.lpi.org/our-certifications/exam-102-objectives/
#   crontab(5), crontab(1), cron(8), anacron(8), anacrontab(5), at(1),
#     run-parts(8) — man-pages shipped with cron/anacron/at on the system
#   systemd.timer(5)  — https://www.freedesktop.org/software/systemd/man/systemd.timer.html
#   systemd.time(7)   — https://www.freedesktop.org/software/systemd/man/systemd.time.html
#   systemd-analyze(1) — https://www.freedesktop.org/software/systemd/man/systemd-analyze.html
# ============================================================================