#!/usr/bin/env bash
# ==============================================================================
# LPI-702: BSD Specialist (Exam 702-100, v1.0)
# Topic 713.7: Manage User Sessions (Weight: 1.67)
#
# Official Reference Sources:
# - LPI BSD Specialist Overview: https://www.lpi.org/our-certifications/bsd-specialist-overview/
# - FreeBSD Manual Page - w(1): https://man.freebsd.org/cgi/man.cgi?query=w&sektion=1
# - FreeBSD Manual Page - utmpx(5): https://man.freebsd.org/cgi/man.cgi?query=utmpx&sektion=5
# - FreeBSD Manual Page - login.conf(5): https://man.freebsd.org/cgi/man.cgi?query=login.conf&sektion=5
# - FreeBSD Manual Page - cap_mkdb(1): https://man.freebsd.org/cgi/man.cgi?query=cap_mkdb&sektion=1
# ==============================================================================
# ARCHITECTURAL OVERVIEW & INTERNAL MECHANICS
# ------------------------------------------------------------------------------
# User session management in BSD and Unix systems relies on three core subsystems:
#
# 1. User Accounting & Session Tracking Database (utmpx / utmp / wtmp / lastlog):
#    - Active user sessions are tracked in runtime state databases:
#      * FreeBSD / Modern BSD: /var/run/utx.active (active), /var/log/utx.log (history), /var/log/utx.lastlogin
#      * Linux / Traditional BSD: /var/run/utmp (active), /var/log/wtmp (history), /var/log/lastlog
#    - Core CLI tools (`w`, `who`, `last`, `ac`, `lastlog`) query these binary database structures.
#    - If accounting files suffer permission corruption or descriptor read blocks, utilities fail silently
#      or return empty session tables.
#
# 2. Login Resource Capabilities & Session Limits (login.conf & cap_mkdb):
#    - Master resource constraints (maxlogins, cputime, memoryuse, priority, umask) are configured in /etc/login.conf.
#    - The BSD login/PAM subsystem reads the hashed capability database /etc/login.conf.db generated by running `cap_mkdb /etc/login.conf`.
#    - Editing /etc/login.conf without compiling it via `cap_mkdb` causes system drift where active limits
#      do not match text configuration.
#
# 3. Inter-Session Communication & TTY Permissions (mesg & wall):
#    - Broadcast messages via `wall` or directed session writes via `write` require target TTY nodes
#      (e.g., /dev/pts/*, /dev/tty*) to have group-write permissions (gid `tty`).
#    - The `mesg` utility toggles session write permission (`mesg y` / `mesg n`).
# ==============================================================================

set -euo pipefail

BACKUP_DIR="/var/tmp/lpi713_7_backup"
TARGET_USER="sre_student"

ensure_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        echo "[ERROR] This lab script must be executed as root (sudo)." >&2
        exit 1
    fi
}

setup_lab_environment() {
    echo "[+] Setting up lab baseline environment..."
    mkdir -p "${BACKUP_DIR}"

    # Create target user if missing
    if ! id "${TARGET_USER}" &>/dev/null; then
        useradd -m -s /bin/bash "${TARGET_USER}" 2>/dev/null || pw useradd "${TARGET_USER}" -m -s /bin/sh 2>/dev/null || true
        echo "${TARGET_USER}:SRE_Lab_2026!" | chpasswd 2>/dev/null || true
    fi

    # Backup critical session files
    [[ -f /etc/login.conf ]] && cp /etc/login.conf "${BACKUP_DIR}/login.conf.bak"
    [[ -f /etc/login.conf.db ]] && cp /etc/login.conf.db "${BACKUP_DIR}/login.conf.db.bak"
    [[ -f /var/run/utmp ]] && cp /var/run/utmp "${BACKUP_DIR}/utmp.bak"
    [[ -f /var/run/utx.active ]] && cp /var/run/utx.active "${BACKUP_DIR}/utx.active.bak"
}

inject_breakage() {
    echo "[+] Injecting controlled production breakage..."

    # Break 1: Corrupt session accounting file permissions
    # Truncate and remove read permissions for non-root users on active session tracking databases
    for utmp_file in /var/run/utmp /var/run/utx.active; do
        if [[ -f "${utmp_file}" ]]; then
            chmod 0000 "${utmp_file}"
        else
            touch "${utmp_file}"
            chmod 0000 "${utmp_file}"
        fi
    done

    # Break 2: Inject strict maxlogins session limit & compile binary capability database
    if [[ -f /etc/login.conf ]]; then
        # Check if default class exists, inject maxlogins restriction
        if grep -q "default:" /etc/login.conf; then
            sed -i.tmp 's/default:/default:\n\t:maxlogins=1:/g' /etc/login.conf 2>/dev/null || true
        else
            echo -e "default:\n\t:maxlogins=1:\n\t:tc=staff:" >> /etc/login.conf
        fi

        # Compile hashed database if cap_mkdb is present (BSD environment)
        if command -v cap_mkdb &>/dev/null; then
            cap_mkdb /etc/login.conf
        fi
    fi

    # Break 3: Globally force mesg n in shell profiles to block inter-user session messaging
    cat << 'EOF' > /etc/profile.d/break_session_msg.sh
# System wide session enforcement
if [ -n "$TTY" ] || [ -t 0 ]; then
    mesg n 2>/dev/null || true
fi
EOF
    chmod 644 /etc/profile.d/break_session_msg.sh

    echo "[+] Breakage injected successfully."
}

print_student_instructions() {
    cat << 'EOF'

===============================================================================
  LPI-702 LAB SCENARIO: TROUBLESHOOTING BSD USER SESSION MANAGEMENT
===============================================================================

[Symptom Report]
An SRE team member reported three distinct incidents on this production node:

1. Session Monitoring Failure:
   Running `w` or `who` as a standard user fails to report active user sessions
   or returns permission denied errors accessing accounting structures.

2. Session Limit Restriction & Configuration Drift:
   User 'sre_student' is unable to establish concurrent logins. Furthermore,
   modifications made to text files in /etc/login.conf do not take effect because
   the binary database /etc/login.conf.db is out of sync.

3. Session Broadcast Failure:
   Emergency broadcast messages via `wall` are silently rejected or suppressed
   for active interactive terminal sessions.

-------------------------------------------------------------------------------
[Student Objectives]
1. Restore standard session visibility so `w`, `who`, and `last` function cleanly
   for unprivileged users.
2. Inspect and fix session login limits in `/etc/login.conf`, recompile the binary
   capability database using `cap_mkdb`, and verify the `maxlogins` behavior.
3. Fix system-wide profile overrides blocking inter-user terminal messaging (`mesg y`).

-------------------------------------------------------------------------------
[Useful Diagnostic Commands & Expected Outputs]

Command 1: Check permissions of user accounting databases
$ ls -la /var/run/utmp /var/run/utx.active
Expected healthy permissions:
-rw-r--r-- 1 root utmp (or wheel)

Command 2: Verify active user sessions
$ w
EXPECTED OUTPUT FORMAT:
 20:49:30 up 2 days,  4:12,  2 users,  load average: 0.05, 0.03, 0.01
 USER         TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
 sre_student  pts/0    192.168.1.50     20:10    0.00s  0.02s  0.00s w

Command 3: Inspect login capability database state
$ cap_mkdb -v /etc/login.conf
EXPECTED OUTPUT FORMAT:
 cap_mkdb: /etc/login.conf: 2 entries processed

Command 4: Verify terminal message permission status
$ mesg
EXPECTED OUTPUT FORMAT:
 is y

===============================================================================
EOF
}

main() {
    ensure_root
    setup_lab_environment
    inject_breakage
    print_student_instructions
}

main "$@"

# ==============================================================================
# SOLUTION / RESTORATION STEPS (UNCOMMENT TO READ OR EXECUTE AUTOMATICALLY)
# ==============================================================================
# To resolve all issues step-by-step, run the following commands as root:
#
# STEP 1: Fix Session Accounting File Permissions
# ------------------------------------------------------------------------------
# Restore standard permissions (0644) on active accounting database files:
#
#   chmod 0644 /var/run/utmp 2>/dev/null || true
#   chmod 0644 /var/run/utx.active 2>/dev/null || true
#   chmod 0644 /var/log/wtmp 2>/dev/null || true
#   chmod 0644 /var/log/utx.log 2>/dev/null || true
#
# Verify session accounting works again:
#   w
#   who
#   last -n 5
#
# STEP 2: Resolve Login Capability Drift and Session Limits
# ------------------------------------------------------------------------------
# Edit /etc/login.conf to remove or adjust the restricted maxlogins setting:
#
#   sed -i 's/:maxlogins=1://g' /etc/login.conf
#
# Recompile the BSD login capability binary database (CRITICAL STEP):
#
#   if command -v cap_mkdb &>/dev/null; then
#       cap_mkdb /etc/login.conf
#   fi
#
# Verify the binary capability database /etc/login.conf.db is updated:
#   ls -la /etc/login.conf.db
#
# STEP 3: Remove Profile Overrides Blocking Terminal Messages
# ------------------------------------------------------------------------------
# Remove the broken shell profile hook forcing `mesg n`:
#
#   rm -f /etc/profile.d/break_session_msg.sh
#
# Enable terminal write permissions in current session:
#   mesg y
#
# Test broadcast system messaging:
#   echo "Maintenance complete" | wall
#
# STEP 4: Automated Lab Cleanup / Full System Restoration
# ------------------------------------------------------------------------------
#   if [[ -d "/var/tmp/lpi713_7_backup" ]]; then
#       [[ -f "/var/tmp/lpi713_7_backup/login.conf.bak" ]] && cp "/var/tmp/lpi713_7_backup/login.conf.bak" /etc/login.conf
#       [[ -f "/var/tmp/lpi713_7_backup/login.conf.db.bak" ]] && cp "/var/tmp/lpi713_7_backup/login.conf.db.bak" /etc/login.conf.db
#       if command -v cap_mkdb &>/dev/null && [[ -f /etc/login.conf ]]; then
#           cap_mkdb /etc/login.conf
#       fi
#       chmod 0644 /var/run/utmp /var/run/utx.active 2>/dev/null || true
#       rm -rf "/var/tmp/lpi713_7_backup" /etc/profile.d/break_session_msg.sh
#       echo "[+] System fully restored to pre-lab state."
#   fi
# ==============================================================================