#!/usr/bin/env python3
"""Regenerate the API reference inside DEVELOPERS.md from the running app.

Hand-written endpoint tables rot: a parameter changes, the table does not, and
the reader trusts it anyway. This reads the FastAPI application object — the
same source `/openapi.json` is served from — and rewrites only the block
between the markers, leaving every hand-written word alone.

    scripts/gen_api_docs.py            # rewrite the block
    scripts/gen_api_docs.py --check    # fail if it is stale (for make verify)

Free: imports the app, calls no network, spends no quota.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

DOC = REPO / "DEVELOPERS.md"
START = "<!-- API-REFERENCE:START -->"
END = "<!-- API-REFERENCE:END -->"

# Endpoints that exist but are not part of the public contract: auth is a
# deny-all placeholder and the health probe is for Kubernetes.
PRIVATE = {"/api/login", "/api/logout", "/api/me", "/healthz", "/"}


def table() -> str:
    from teach.api import app

    rows = ["| Method | Path | What it returns |", "|---|---|---|"]
    seen = set()
    for route in sorted(app.routes, key=lambda r: getattr(r, "path", "")):
        path = getattr(route, "path", "")
        if not path.startswith("/api") or path in PRIVATE or path in seen:
            continue
        seen.add(path)
        for method in sorted(getattr(route, "methods", set()) - {"HEAD", "OPTIONS"}):
            doc = (route.endpoint.__doc__ or "").strip().splitlines()
            summary = doc[0].rstrip(".") if doc else ""
            rows.append(f"| `{method}` | `{path}` | {summary} |")
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the block is out of date")
    args = parser.parse_args()

    if not DOC.exists():
        print(f"{DOC} does not exist.")
        return 1
    text = DOC.read_text()
    if START not in text or END not in text:
        print(f"Markers {START} / {END} not found in {DOC.name}.")
        return 1

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    block = (f"{START}\n<!-- Generated by scripts/gen_api_docs.py from the FastAPI app. "
             f"Do not edit by hand. -->\n\n{table()}\n\n{END}")
    updated = head + block + tail

    if args.check:
        if updated != text:
            print("DEVELOPERS.md API reference is stale — run scripts/gen_api_docs.py")
            return 1
        print("DEVELOPERS.md API reference matches the application.")
        return 0

    if updated == text:
        print("DEVELOPERS.md already current.")
        return 0
    DOC.write_text(updated)
    print("DEVELOPERS.md API reference regenerated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
