#!/usr/bin/env python3
"""Generates STATUS.md: cert x language x lab matrix, and path x video language matrix.

It is always read from the actual filesystem (file counts), never manually
updated — the lesson of this session is that "N/N topics" proves nothing unless
content.md, exercises.md, and break_fix.sh are counted separately (see
CHANGELOG.md 2026-07-16/17). Run again after any generation to keep the state updated:

    .venv/bin/python3 scripts/status_matrix.py
"""
import sys
from pathlib import Path

import yaml

from teach.core import quality

REPO = Path(__file__).resolve().parent.parent
LANGS = ["es", "en", "fr", "de", "zh", "ja", "pt"]
VIDEO_LANGS = ["es", "en", "de", "zh", "ja"]


def cert_topics(cert_id: str) -> list[dict]:
    path = REPO / "certs" / f"{cert_id}.md"
    if not path.exists():
        return []
    front = yaml.safe_load(path.read_text().split("---")[1])
    return front.get("topics") or []


def lang_cell(cert_dir: Path, lang: str, n: int) -> str:
    """Cuenta solo el material que llega al piso de calidad de pipeline.yaml.

    Contar archivos existentes marcaba ✅ una certificación entera cuyos temas
    promediaban un noveno del tamaño habitual y a la que le faltaba la sección
    de respuestas. Un archivo presente pero por debajo del estándar es trabajo
    pendiente, no trabajo hecho, y la matriz tiene que decir eso.
    """
    files = list(cert_dir.glob(f"*/{lang}/content.md"))
    exercises = list(cert_dir.glob(f"*/{lang}/exercises.md"))
    c = sum(1 for f in files if not quality.check_file(f))
    e = sum(1 for f in exercises if not quality.check_file(f))
    below = (len(files) - c) + (len(exercises) - e)

    if c == n and e == n:
        return "✅"
    if not files and not exercises:
        return "❌"
    cell = f"🔶 {c}/{n}c·{e}/{n}e"
    return f"{cell} ⚠️{below}" if below else cell


def lab_cell(cert_dir: Path, n: int) -> str:
    lab = len(list(cert_dir.glob("*/lab/break_fix.sh")))
    if lab == n:
        return "✅"
    if lab == 0:
        return "❌"
    return f"🔶 {lab}/{n}"


def main() -> None:
    catalog = yaml.safe_load((REPO / "catalog.yaml").read_text())
    lines = [
        "# Content Status",
        "",
        "Generated by `scripts/status_matrix.py` from the actual filesystem "
        "— run again after any generation, do not edit directly. Counts only "
        "material that meets the quality floor in `pipeline.yaml`, not files "
        "that merely exist: a topic present but below the floor is pending "
        "work, not finished work.",
        "",
        "✅ complete · 🔶 partial (details) · ⚠️N N files below the quality "
        "floor · ❌ not started · – N/A (syllabus not snapshotted yet)",
        "",
        "## Certifications",
        "",
        "| Cert | Topics | " + " | ".join(l.upper() for l in LANGS) + " | Labs |",
        "|---|---|" + "---|" * len(LANGS) + "---|",
    ]
    for cert_id, cert in catalog["certs"].items():
        topics = cert_topics(cert_id)
        n = len(topics)
        cert_dir = REPO / "certs" / cert_id
        if n == 0:
            row = [f"`{cert_id}`", "–"] + ["–"] * len(LANGS) + ["–"]
        else:
            row = [f"`{cert_id}`", str(n)]
            row += [lang_cell(cert_dir, lang, n) for lang in LANGS]
            row.append(lab_cell(cert_dir, n))
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## Path Videos", "",
              "| Path | " + " | ".join(l.upper() for l in VIDEO_LANGS) + " |",
              "|---|" + "---|" * len(VIDEO_LANGS)]
    for slug, path in (catalog.get("paths") or {}).items():
        if path.get("type"):
            continue  # achievements/info do not have video
        row = [f"`{slug}`"]
        for lang in VIDEO_LANGS:
            video = REPO / "media" / "paths" / slug / lang / "video.mp4"
            row.append("✅" if video.exists() else "❌")
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## Certification Videos", "",
              "| Cert | " + " | ".join(l.upper() for l in VIDEO_LANGS) + " |",
              "|---|" + "---|" * len(VIDEO_LANGS)]
    for cert_id in catalog["certs"]:
        row = [f"`{cert_id}`"]
        for lang in VIDEO_LANGS:
            video = REPO / "media" / "certs" / cert_id / lang / "video.mp4"
            row.append("✅" if video.exists() else "❌")
        lines.append("| " + " | ".join(row) + " |")

    (REPO / "STATUS.md").write_text("\n".join(lines) + "\n")
    print("Wrote STATUS.md")


if __name__ == "__main__":
    sys.exit(main())
