#!/usr/bin/env python3
"""Generates STATUS.md: cert x language x lab matrix, and path x video language matrix.

It is always read from the actual filesystem (file counts), never manually
updated — the lesson of this session is that "N/N topics" proves nothing unless
content.md, exercises.md, and break_fix.sh are counted separately (see
CHANGELOG.md 2026-07-16/17). Run again after any generation to keep the state updated:

    .venv/bin/python3 scripts/status_matrix.py
"""
import sys
from pathlib import Path

import yaml

from teach.core import certs, quality, video

REPO = Path(__file__).resolve().parent.parent
STATUS = REPO / "STATUS.md"
# Derived, never declared here. A private copy of these lists is the exact defect
# this repo has hit three times: the matrix reported on the languages it had been
# told about and stayed silent about the rest, which reads as "nothing missing".
#
# LANGS       every language the platform supports (teach/core/certs.py)
# VIDEO_LANGS only those Piper can actually speak — a video column for a language
#             with no voice would be permanently red for something that cannot be
#             done at all, which is noise rather than a finding.
LANGS = list(certs.LANGS)
VIDEO_LANGS = [l for l in certs.LANGS if l in video.VOICES]


def cert_topics(cert_id: str) -> list[dict]:
    path = REPO / "certs" / f"{cert_id}.md"
    if not path.exists():
        return []
    front = yaml.safe_load(path.read_text().split("---")[1])
    return front.get("topics") or []


def lang_cell(cert_dir: Path, lang: str, n: int) -> str:
    """Count only material that meets the quality floor in pipeline.yaml.

    Counting files that merely exist marked a whole certification ✅ while its
    topics averaged a ninth of the usual size and had no answers section. A
    file that is present but below the standard is pending work, not finished
    work, and the matrix has to say so.
    """
    files = list(cert_dir.glob(f"*/{lang}/content.md"))
    exercises = list(cert_dir.glob(f"*/{lang}/exercises.md"))
    c = sum(1 for f in files if not quality.check_file(f))
    e = sum(1 for f in exercises if not quality.check_file(f))
    below = (len(files) - c) + (len(exercises) - e)

    if c == n and e == n:
        return "✅"
    if not files and not exercises:
        return "❌"
    cell = f"🔶 {c}/{n}c·{e}/{n}e"
    return f"{cell} ⚠️{below}" if below else cell


def lab_cell(cert_dir: Path, n: int) -> str:
    lab = len(list(cert_dir.glob("*/lab/break_fix.sh")))
    if lab == n:
        return "✅"
    if lab == 0:
        return "❌"
    return f"🔶 {lab}/{n}"


def refresh() -> bool:
    """Regenerate STATUS.md from disk. True if it changed.

    The single implementation every caller shares — `make cert`, `make publish`,
    the unattended timer and the CLI all land here rather than each shelling out
    to a script and each getting it slightly wrong. Importable on purpose:

        from status_matrix import refresh
        refresh()

    Idempotent by construction: it derives everything from the filesystem, so
    running it twice produces the same bytes and running it never is the only way
    to be wrong. STATUS.md sat a day stale reporting kcsa at 2/42 when it was
    42/42, because the one path that does most of the generating did not call it.
    """
    before = STATUS.read_text() if STATUS.exists() else None
    _write()
    return STATUS.read_text() != before


def _write() -> None:
    catalog = yaml.safe_load((REPO / "catalog.yaml").read_text())
    lines = [
        "# Content Status",
        "",
        "Generated by `scripts/status_matrix.py` from the actual filesystem "
        "— run again after any generation, do not edit directly. Counts only "
        "material that meets the quality floor in `pipeline.yaml`, not files "
        "that merely exist: a topic present but below the floor is pending "
        "work, not finished work.",
        "",
        "✅ complete · 🔶 partial (details) · ⚠️N N files below the quality "
        "floor · ❌ not started · – N/A (syllabus not snapshotted yet)",
        "",
        "## Certifications",
        "",
        "| Cert | Topics | " + " | ".join(l.upper() for l in LANGS) + " | Labs |",
        "|---|---|" + "---|" * len(LANGS) + "---|",
    ]
    for cert_id, cert in catalog["certs"].items():
        topics = cert_topics(cert_id)
        n = len(topics)
        cert_dir = REPO / "certs" / cert_id
        if n == 0:
            row = [f"`{cert_id}`", "–"] + ["–"] * len(LANGS) + ["–"]
        else:
            row = [f"`{cert_id}`", str(n)]
            row += [lang_cell(cert_dir, lang, n) for lang in LANGS]
            row.append(lab_cell(cert_dir, n))
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## Path Videos", "",
              "| Path | " + " | ".join(l.upper() for l in VIDEO_LANGS) + " |",
              "|---|" + "---|" * len(VIDEO_LANGS)]
    for slug, path in (catalog.get("paths") or {}).items():
        if path.get("type"):
            continue  # achievements/info do not have video
        row = [f"`{slug}`"]
        for lang in VIDEO_LANGS:
            video = REPO / "media" / "paths" / slug / lang / "video.mp4"
            row.append("✅" if video.exists() else "❌")
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## Certification Videos", "",
              "| Cert | " + " | ".join(l.upper() for l in VIDEO_LANGS) + " |",
              "|---|" + "---|" * len(VIDEO_LANGS)]
    for cert_id in catalog["certs"]:
        row = [f"`{cert_id}`"]
        for lang in VIDEO_LANGS:
            rendered = REPO / "media" / "certs" / cert_id / lang / "video.mp4"
            row.append("✅" if rendered.exists() else "❌")
        lines.append("| " + " | ".join(row) + " |")

    (REPO / "STATUS.md").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    print("STATUS.md updated" if refresh() else "STATUS.md already current")
