#!/usr/bin/env bash
# ==============================================================================
# CNCF KCSA (Kubernetes and Cloud Native Security Associate) Certification Lab
# Domain 3.1: Pod Security Standards (PSS) & Pod Security Admission (PSA)
# Role: Senior SRE / Principal Platform Architect Instructor
# ==============================================================================
#
# OFFICIAL REFERENCES & SOURCES:
# - KCSA Curriculum: https://github.com/cncf/curriculum/raw/master/KCSA%20Curriculum.pdf
# - K8s Pod Security Standards: https://kubernetes.io/docs/concepts/security/pod-security-standards/
# - K8s Pod Security Admission: https://kubernetes.io/docs/concepts/security/pod-security-admission/
# - K8s PSA Configuration: https://kubernetes.io/docs/tasks/configure-pod-security/enforce-standards-admission-controller/
#
# ARCHITECTURAL MECHANICS & DEEP DIVE:
# ------------------------------------------------------------------------------
# 1. Pod Security Standards (PSS) define three isolation profiles:
#    - Privileged: Unrestricted execution (equivalent to root host access).
#    - Baseline: Prevents known privilege escalations with minimal restrictions.
#    - Restricted: Hardened profile following security best practices (requires
#      dropping ALL capabilities, disabling privilege escalation, enforcing non-root
#      execution, and requiring seccomp profiles).
#
# 2. Pod Security Admission (PSA) operates as a built-in admission controller.
#    It evaluates incoming Pod creation requests against PSS profiles using:
#    - Namespace Labels: `pod-security.kubernetes.io/<mode>: <level>`
#    - Modes: `enforce` (rejects non-compliant pods), `audit` (logs violation),
#      `warn` (returns warning header to user).
#
# PRODUCTION TRADE-OFFS & TROUBLESHOOTING LESSON:
# ------------------------------------------------------------------------------
# When applying PSA labels to a namespace, Deployment creation succeeds because
# PSA inspects Pod objects, not Deployments. However, the ReplicaSet controller
# fails asynchronously when attempting to spawn Pods, resulting in READY 0/N.
# SREs must inspect ReplicaSet events (`kubectl describe rs`) to uncover admission
# rejection errors generated by PSA.
# ==============================================================================

set -euo pipefail

# ANSI Color Codes for Lab Formatting
COLOR_RED='\033[0;31m'
COLOR_GREEN='\033[0;32m'
COLOR_YELLOW='\033[0;33m'
COLOR_BLUE='\033[0;34m'
COLOR_NC='\033[0m'

NAMESPACE="finance-prod"
DEPLOYMENT_NAME="payment-processor"

echo -e "${COLOR_BLUE}[+] Verifying environment pre-requisites...${COLOR_NC}"
if ! command -v kubectl &> /dev/null; then
    echo -e "${COLOR_RED}[!] Error: 'kubectl' executable not found in PATH.${COLOR_NC}"
    exit 1
fi

if ! kubectl cluster-info &> /dev/null; then
    echo -e "${COLOR_RED}[!] Error: Cannot connect to active Kubernetes cluster via KUBECONFIG.${COLOR_NC}"
    exit 1
fi

echo -e "${COLOR_BLUE}[+] Injecting production fault for Topic 3.1 (Pod Security Standards)...${COLOR_NC}"

# 1. Reset target namespace state
kubectl delete namespace "${NAMESPACE}" --ignore-not-found=true --wait=true &> /dev/null || true

# 2. Create namespace with Restricted Pod Security Admission (PSA) enforcement
kubectl create namespace "${NAMESPACE}"
kubectl label --overwrite namespace "${NAMESPACE}" \
  pod-security.kubernetes.io/enforce=restricted \
  pod-security.kubernetes.io/enforce-version=latest \
  pod-security.kubernetes.io/warn=restricted \
  pod-security.kubernetes.io/warn-version=latest

# 3. Deploy non-compliant workload (Missing mandatory securityContext fields required by PSS Restricted)
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${DEPLOYMENT_NAME}
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT_NAME}
    spec:
      containers:
      - name: processor
        image: busybox:1.36
        command: ["sh", "-c", "sleep 3600"]
        ports:
        - containerPort: 8080
EOF

echo -e "\n${COLOR_YELLOW}==============================================================================${COLOR_NC}"
echo -e "${COLOR_YELLOW}                 LAB SCENARIO INJECTED: BREAK & FIX READY                     ${COLOR_NC}"
echo -e "${COLOR_YELLOW}==============================================================================${COLOR_NC}"
echo -e "Environment Details:"
echo -e "  - Namespace: ${NAMESPACE}"
echo -e "  - Deployment: ${DEPLOYMENT_NAME}"
echo -e "  - PSS Policy: pod-security.kubernetes.io/enforce=restricted"
echo -e ""
echo -e "${COLOR_RED}SYMPTOMS OBSERVED:${COLOR_NC}"
echo -e "  1. Check deployment status:"
echo -e "     $ kubectl get deployment ${DEPLOYMENT_NAME} -n ${NAMESPACE}"
echo -e "     Expected Output: READY 0/2"
echo -e ""
echo -e "  2. Check replica set status & admission events:"
echo -e "     $ kubectl describe rs -n ${NAMESPACE} -l app=${DEPLOYMENT_NAME}"
echo -e "     Expected Output (Events section):"
echo -e "       Warning  FailedCreate  ...  replicaset-controller  Error creating: pods \"...\" is forbidden:"
echo -e "       violates PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false, unrestricted capabilities,"
echo -e "       runAsNonRoot != true, seccompProfile"
echo -e ""
echo -e "${COLOR_GREEN}STUDENT GOAL:${COLOR_NC}"
echo -e "  1. Modify the Deployment spec in namespace '${NAMESPACE}' to strictly comply with"
echo -e "     the PSS 'Restricted' profile without removing or relaxing namespace labels."
echo -e "  2. Achieve 2/2 Ready pods running under namespace security enforcement."
echo -e "${COLOR_YELLOW}==============================================================================${COLOR_NC}\n"

# ==============================================================================
# INSTRUCTOR SOLUTION & DIAGNOSTIC WALKTHROUGH (COMMENTED OUT)
# ==============================================================================
#
# STEP 1: DIAGNOSIS & INSPECTION
# ------------------------------------------------------------------------------
# Run CLI diagnostic command to inspect ReplicaSet events:
# $ kubectl describe rs -n finance-prod
#
# Expected CLI Event Output:
#   Type     Reason        Age                   From                   Message
#   ----     ------        ----                  ----                   -------
#   Warning  FailedCreate  12s (x4 over 45s)     replicaset-controller  Error creating: pods "payment-processor-75d5f8b9b4-2x9zp" is forbidden:
#   violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "processor" must set allowPrivilegeEscalation=false),
#   unrestricted capabilities (container "processor" must set securityContext.capabilities.drop=["ALL"]),
#   runAsNonRoot != true (pod or container "processor" must set securityContext.runAsNonRoot=true),
#   seccompProfile (pod or container "processor" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
#
# STEP 2: ROOT CAUSE ANALYSIS
# ------------------------------------------------------------------------------
# The namespace enforces `pod-security.kubernetes.io/enforce=restricted`.
# The Pod template inside the Deployment lacks the required Pod-level and Container-level
# `securityContext` parameters mandated by the Kubernetes PSS Restricted Specification.
#
# STEP 3: CORRECTION / REMEDIATION MANIFEST
# ------------------------------------------------------------------------------
# Create a compliant deployment manifest (e.g., `solution-deployment.yaml`):
#
# cat <<'EOF' > solution-deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: payment-processor
#   namespace: finance-prod
#   labels:
#     app: payment-processor
#     tier: api
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: payment-processor
#   template:
#     metadata:
#       labels:
#         app: payment-processor
#     spec:
#       securityContext:
#         runAsNonRoot: true
#         runAsUser: 10001
#         runAsGroup: 10001
#         fsGroup: 10001
#         seccompProfile:
#           type: RuntimeDefault
#       containers:
#       - name: processor
#         image: busybox:1.36
#         command: ["sh", "-c", "sleep 3600"]
#         ports:
#         - containerPort: 8080
#         securityContext:
#           allowPrivilegeEscalation: false
#           capabilities:
#             drop:
#             - ALL
# EOF
#
# STEP 4: APPLY & VERIFY
# ------------------------------------------------------------------------------
# $ kubectl apply -f solution-deployment.yaml
# deployment.apps/payment-processor configured
#
# $ kubectl get pods -n finance-prod
# NAME                                 READY   STATUS    RESTARTS   AGE
# payment-processor-689b94b59c-6x52p   1/1     Running   0          5s
# payment-processor-689b94b59c-jkhv8   1/1     Running   0          5s
#
# $ kubectl get deployment payment-processor -n finance-prod
# NAME                READY   UP-TO-DATE   AVAILABLE   AGE
# payment-processor   2/2     2            2           2m
# ==============================================================================